/* ********************************************************************************************************************
 * 일 마감 관련 테이블 및 마이그레이션 쿼리
 *
 * @author wisehouse@finger.co.kr
 ******************************************************************************************************************** */
CREATE TABLE XDAYSUM
(
    CHACD CHAR(8) NOT NULL
  , SETTLE_DT CHAR(8) NOT NULL
  , NOTICE_COUNT NUMBER(9) DEFAULT 0 NOT NULL
  , NOTICE_AMOUNT NUMBER(14) DEFAULT 0 NOT NULL
  , NOTICE_FEE NUMBER(14) DEFAULT 0 NOT NULL
  , VAS_COUNT NUMBER(9) DEFAULT 0 NOT NULL
  , VAS_AMOUNT NUMBER(14) DEFAULT 0 NOT NULL
  , VAS_FEE NUMBER(14) DEFAULT 0 NOT NULL
  , VAS_BANK_FEE NUMBER(14) DEFAULT 0 NOT NULL
  , DCD_COUNT NUMBER(9) DEFAULT 0 NOT NULL
  , DCD_AMOUNT NUMBER(14) DEFAULT 0 NOT NULL
  , DCS_COUNT NUMBER(9) DEFAULT 0 NOT NULL
  , DCS_AMOUNT NUMBER(14) DEFAULT 0 NOT NULL
  , DVA_COUNT NUMBER(9) DEFAULT 0 NOT NULL
  , DVA_AMOUNT NUMBER(14) DEFAULT 0 NOT NULL
  , OCD_COUNT NUMBER(9) DEFAULT 0 NOT NULL
  , OCD_AMOUNT NUMBER(14) DEFAULT 0 NOT NULL
  , SMS_COUNT NUMBER(9) DEFAULT 0 NOT NULL
  , SMS_FEE NUMBER(14) DEFAULT 0 NOT NULL
  , LMS_COUNT NUMBER(9) DEFAULT 0 NOT NULL
  , LMS_FEE NUMBER(14) DEFAULT 0 NOT NULL
  , CREATE_DATE DATE DEFAULT SYSDATE NOT NULL
  , CREATE_USER VARCHAR2(100) NOT NULL
  , MODIFY_DATE DATE DEFAULT SYSDATE NOT NULL
  , MODIFY_USER VARCHAR2(100) NOT NULL
);

COMMENT ON COLUMN XDAYSUM.CHACD IS '기관코드';

COMMENT ON COLUMN XDAYSUM.SETTLE_DATE IS '정산일자';

COMMENT ON COLUMN XDAYSUM.NOTICE_COUNT IS '청구건수';

COMMENT ON COLUMN XDAYSUM.NOTICE_AMOUNT IS '청구금액';

COMMENT ON COLUMN XDAYSUM.NOTICE_FEE IS '청구수수료';

COMMENT ON COLUMN XDAYSUM.VAS_COUNT IS '가상계좌입금건수';

COMMENT ON COLUMN XDAYSUM.VAS_AMOUNT IS '가상계좌입금금액';

COMMENT ON COLUMN XDAYSUM.VAS_FEE IS '가상계좌입금수수료';

COMMENT ON COLUMN XDAYSUM.VAS_BANK_FEE IS '가상계좌입금은행수수료';

COMMENT ON COLUMN XDAYSUM.DCD_COUNT IS '오프라인카드결제건수';

COMMENT ON COLUMN XDAYSUM.DCD_AMOUNT IS '오프라인카드결제금액';

COMMENT ON COLUMN XDAYSUM.DCS_COUNT IS '창구현금수납건수';

COMMENT ON COLUMN XDAYSUM.DCS_AMOUNT IS '청구현금수납금액';

COMMENT ON COLUMN XDAYSUM.DVA_COUNT IS '계좌이체수납건수';

COMMENT ON COLUMN XDAYSUM.DVA_AMOUNT IS '계좌이체수납금액';

COMMENT ON COLUMN XDAYSUM.OCD_COUNT IS '온라인카드결제건수';

COMMENT ON COLUMN XDAYSUM.OCD_AMOUNT IS '온라인카드결제금액';

COMMENT ON COLUMN XDAYSUM.SMS_COUNT IS 'SMS 건수';

COMMENT ON COLUMN XDAYSUM.SMS_FEE IS 'SMS 사용료';

COMMENT ON COLUMN XDAYSUM.LMS_COUNT IS 'LMS 건수';

COMMENT ON COLUMN XDAYSUM.LMS_FEE IS 'LMS 사용료';

COMMENT ON COLUMN XDAYSUM.CREATE_DATE IS '등록일시';

COMMENT ON COLUMN XDAYSUM.CREATE_USER IS '등록자';

COMMENT ON COLUMN XDAYSUM.MODIFY_DATE IS '변경일시';

COMMENT ON COLUMN XDAYSUM.MODIFY_USER IS '변경자';

INSERT INTO XDAYSUM (CHACD, SETTLE_DT, CREATE_USER, MODIFY_USER)
  SELECT CHACD, SETTLE_DT, 'wisehouse', 'wisehouse' FROM (
                                                           SELECT CHACD, NOTIDAY AS SETTLE_DT
                                                           FROM XDAYSUMNOTI
                                                           UNION
                                                           SELECT CHACD, RCPDAY
                                                           FROM XDAYSUMRCP
                                                           UNION
                                                           SELECT CHACD, RCPDAY
                                                           FROM XDAYSUMRCPETC
                                                           UNION
                                                           SELECT CHACD, SMSDAY
                                                           FROM XDAYSUMSMS
                                                         ) X;

UPDATE XDAYSUM A
SET NOTICE_COUNT=(SELECT NOTICNT FROM XDAYSUMNOTI WHERE CHACD=A.CHACD AND NOTIDAY=A.SETTLE_DT),
  NOTICE_AMOUNT=(SELECT NOTIAMT FROM XDAYSUMNOTI WHERE CHACD=A.CHACD AND NOTIDAY=A.SETTLE_DT)
WHERE (CHACD, SETTLE_DT) IN (SELECT CHACD, NOTIDAY FROM XDAYSUMNOTI);

UPDATE XDAYSUM A
SET VAS_COUNT=(SELECT RCPCNT FROM XDAYSUMRCP WHERE CHACD=A.CHACD AND RCPDAY=A.SETTLE_DT),
  VAS_AMOUNT=(SELECT RCPAMT FROM XDAYSUMRCP WHERE CHACD=A.CHACD AND RCPDAY=A.SETTLE_DT)
WHERE (CHACD, SETTLE_DT) IN (SELECT CHACD, RCPDAY FROM XDAYSUMRCP);

UPDATE XDAYSUM A
SET DCD_COUNT=(SELECT NVL(DCDCNT, 0) FROM XDAYSUMRCPETC WHERE CHACD=A.CHACD AND RCPDAY=A.SETTLE_DT),
  DCD_AMOUNT=(SELECT NVL(DCDAMT, 0) FROM XDAYSUMRCPETC WHERE CHACD=A.CHACD AND RCPDAY=A.SETTLE_DT),
  OCD_COUNT=(SELECT NVL(OCDCNT, 0) FROM XDAYSUMRCPETC WHERE CHACD=A.CHACD AND RCPDAY=A.SETTLE_DT),
  OCD_AMOUNT=(SELECT NVL(OCDAMT, 0) FROM XDAYSUMRCPETC WHERE CHACD=A.CHACD AND RCPDAY=A.SETTLE_DT),
  DCS_COUNT=(SELECT NVL(DCSCNT, 0) FROM XDAYSUMRCPETC WHERE CHACD=A.CHACD AND RCPDAY=A.SETTLE_DT),
  DCS_AMOUNT=(SELECT NVL(DCSAMT, 0) FROM XDAYSUMRCPETC WHERE CHACD=A.CHACD AND RCPDAY=A.SETTLE_DT),
  DVA_COUNT=(SELECT NVL(DVACNT, 0) FROM XDAYSUMRCPETC WHERE CHACD=A.CHACD AND RCPDAY=A.SETTLE_DT),
  DVA_AMOUNT=(SELECT NVL(DVAAMT, 0) FROM XDAYSUMRCPETC WHERE CHACD=A.CHACD AND RCPDAY=A.SETTLE_DT)
WHERE (CHACD, SETTLE_DT) IN (SELECT CHACD, RCPDAY FROM XDAYSUMRCPETC);

UPDATE XDAYSUM A
SET SMS_COUNT=(SELECT NVL(SMSCNT, 0) FROM XDAYSUMSMS WHERE CHACD=A.CHACD AND SMSDAY=A.SETTLE_DT),
  LMS_COUNT=(SELECT NVL(LMSCNT, 0) FROM XDAYSUMSMS WHERE CHACD=A.CHACD AND SMSDAY=A.SETTLE_DT)
WHERE (CHACD, SETTLE_DT) IN (SELECT CHACD, SMSDAY FROM XDAYSUMSMS);

UPDATE XDAYSUM
SET SMS_FEE=SMS_COUNT*20,
  LMS_FEE=LMS_COUNT*40;

UPDATE XDAYSUM A
SET NOTICE_FEE=NOTICE_COUNT*(SELECT NOTCNTFEE FROM XCHALIST WHERE CHACD=A.CHACD),
  VAS_FEE=VAS_COUNT*(SELECT RCPCNTFEE FROM XCHALIST WHERE CHACD=A.CHACD),
  VAS_BANK_FEE=VAS_COUNT*(SELECT RCPBNKFEE FROM XCHALIST WHERE CHACD=A.CHACD)
;

ALTER TABLE XCHALIST
ADD (MNLRCPREQTY CHAR(1 BYTE) );
COMMENT ON COLUMN XCHALIST.MNLRCPREQTY IS '수기수납 현금영수증 자동발급';

UPDATE XCHALIST B
SET MNLRCPREQTY = (SELECT A.RCPREQTY from XCHALIST A where A.CHACD = B.CHACD);