/* @author jhjeong@finger.co.kr 
 * @modified 2018. 10. 15. 
 * 납부자 > 선택납부 처리용 필드생성 */

ALTER TABLE XNOTIDET 
ADD (PICKRCPYN CHAR(1 BYTE) );

COMMENT ON COLUMN XNOTIDET.NOTIDETCD IS '청구항목상세';

COMMENT ON COLUMN XNOTIDET.NOTIMASCD IS '청구마스터키';

COMMENT ON COLUMN XNOTIDET.DETKEY IS '항목거래번호';

COMMENT ON COLUMN XNOTIDET.PAYITEMCD IS '청구항목코드';

COMMENT ON COLUMN XNOTIDET.ADJFIREGKEY IS '분할입금계좌';

COMMENT ON COLUMN XNOTIDET.PAYITEMNAME IS '청구항목명';

COMMENT ON COLUMN XNOTIDET.PAYITEMAMT IS '청구항목금액';

COMMENT ON COLUMN XNOTIDET.PAYITEMSELYN IS '청구항목필수여부';

COMMENT ON COLUMN XNOTIDET.RCPITEMYN IS '현금영수증대상여부';

COMMENT ON COLUMN XNOTIDET.CHAOFFNO IS '사업자번호';

COMMENT ON COLUMN XNOTIDET.CUSOFFNO IS '현금영수증고객발급번호';

COMMENT ON COLUMN XNOTIDET.PTRITEMNAME IS '고지서출력대체항목명';

COMMENT ON COLUMN XNOTIDET.PTRITEMREMARK IS '고지서출력 비고';

COMMENT ON COLUMN XNOTIDET.PTRITEMORDER IS '고지서출력순서';

COMMENT ON COLUMN XNOTIDET.NOTIDETST IS '상태 [PA00:임시, PA02:미납, PA03:수납, PA04:일부납, PA05:초과납, PA06:환불]';

COMMENT ON COLUMN XNOTIDET.MAKEDT IS '조작일시';

COMMENT ON COLUMN XNOTIDET.MAKER IS '조작자';

COMMENT ON COLUMN XNOTIDET.REGDT IS '등록일시';

COMMENT ON COLUMN XNOTIDET.CHATRTY IS '기관접속형태';

COMMENT ON COLUMN XNOTIDET.BATCHSEQ IS '배치순번';

COMMENT ON COLUMN XNOTIDET.PICKRCPYN IS '선택납부여부';

/* @
 * @modified 2018. 10. 22.
 * 고지출력의뢰 정렬순서 */

ALTER TABLE XNOTIMASREQ
ADD (SORT_1_CD CHAR(6) );

ALTER TABLE XNOTIMASREQ
ADD (SORT_2_CD CHAR(6) );

COMMENT ON COLUMN XNOTIMASREQ.SORT_1_CD IS '정렬1 코드';

COMMENT ON COLUMN XNOTIMASREQ.SORT_2_CD IS '정렬2 코드';


REM INSERTING into FW_CODE
SET DEFINE OFF;
Insert into FW_CODE (CODE,CODE_GROUP,NAME,DESCRIPTION,MODIFY_USER,MODIFY_DATE) values ('N00001','N0','고객명',null,'wisehouse',to_date('2018-10-22 01:09:44','YYYY-MM-DD HH24:MI:SS'));
Insert into FW_CODE (CODE,CODE_GROUP,NAME,DESCRIPTION,MODIFY_USER,MODIFY_DATE) values ('N00002','N0','고객구분1',null,'wisehouse',to_date('2018-10-22 01:09:44','YYYY-MM-DD HH24:MI:SS'));
Insert into FW_CODE (CODE,CODE_GROUP,NAME,DESCRIPTION,MODIFY_USER,MODIFY_DATE) values ('N00003','N0','고객구분2',null,'wisehouse',to_date('2018-10-22 01:09:44','YYYY-MM-DD HH24:MI:SS'));
Insert into FW_CODE (CODE,CODE_GROUP,NAME,DESCRIPTION,MODIFY_USER,MODIFY_DATE) values ('N00004','N0','고객구분3',null,'wisehouse',to_date('2018-10-22 01:09:44','YYYY-MM-DD HH24:MI:SS'));
Insert into FW_CODE (CODE,CODE_GROUP,NAME,DESCRIPTION,MODIFY_USER,MODIFY_DATE) values ('N00005','N0','고객구분4',null,'wisehouse',to_date('2018-10-22 01:09:44','YYYY-MM-DD HH24:MI:SS'));