--------------------------------------------------------
--  DDL for Table XNOTIMASREQDET
--------------------------------------------------------

  CREATE TABLE "XNOTIMASREQDET"
   (	"NOTIMASREQCD" CHAR(8 BYTE),
	"SEQ_NO" CHAR(10 BYTE),
	"TITLE" CHAR(20 BYTE),
	"CUSALS" CHAR(30 BYTE),
	"CONTENT" CHAR(1600 BYTE),
	"CHANAME" CHAR(30 BYTE),
	"TELNO" CHAR(15 BYTE),
	"OPT_CONTENT" CHAR(120 BYTE),
	"FOOTER1" CHAR(120 BYTE),
	"FOOTER2" CHAR(120 BYTE),
	"FOOTER3" CHAR(120 BYTE),
	"OWNERTEL" CHAR(15 BYTE),
	"ADDRESS" CHAR(150 BYTE),
	"NOTIMASCD" CHAR(20 BYTE),
	"VANO" CHAR(15 BYTE),
	"CUSNAME" CHAR(30 BYTE),
	"CUSGUBN1" CHAR(20 BYTE),
	"CUSGUBN2" CHAR(20 BYTE),
	"CUSGUBN3" CHAR(20 BYTE),
	"CUSGUBN4" CHAR(20 BYTE),
	"NOTIAMT" CHAR(12 BYTE),
	"DUE_DT" CHAR(8 BYTE),
	"ITEM1_NAME" CHAR(30 BYTE),
	"ITEM1_AMT" CHAR(12 BYTE),
	"ITEM1_REMARK" CHAR(50 BYTE),
	"ITEM2_NAME" CHAR(30 BYTE),
	"ITEM2_AMT" CHAR(12 BYTE),
	"ITEM2_REMARK" CHAR(50 BYTE),
	"ITEM3_NAME" CHAR(30 BYTE),
	"ITEM3_AMT" CHAR(12 BYTE),
	"ITEM3_REMARK" CHAR(50 BYTE),
	"ITEM4_NAME" CHAR(30 BYTE),
	"ITEM4_AMT" CHAR(12 BYTE),
	"ITEM4_REMARK" CHAR(50 BYTE),
	"ITEM5_NAME" CHAR(30 BYTE),
	"ITEM5_AMT" CHAR(12 BYTE),
	"ITEM5_REMARK" CHAR(50 BYTE),
	"ITEM6_NAME" CHAR(30 BYTE),
	"ITEM6_AMT" CHAR(12 BYTE),
	"ITEM6_REMARK" CHAR(50 BYTE),
	"ITEM7_NAME" CHAR(30 BYTE),
	"ITEM7_AMT" CHAR(12 BYTE),
	"ITEM7_REMARK" CHAR(50 BYTE),
	"ITEM8_NAME" CHAR(30 BYTE),
	"ITEM8_AMT" CHAR(12 BYTE),
	"ITEM8_REMARK" CHAR(50 BYTE),
	"ITEM9_NAME" CHAR(30 BYTE),
	"ITEM9_AMT" CHAR(12 BYTE),
	"ITEM9_REMARK" CHAR(50 BYTE)
   );

   COMMENT ON COLUMN "XNOTIMASREQDET"."NOTIMASREQCD" IS '출력의뢰번호';
   COMMENT ON COLUMN "XNOTIMASREQDET"."SEQ_NO" IS '순번 - 출력의뢰번호별 ';
   COMMENT ON COLUMN "XNOTIMASREQDET"."TITLE" IS '고지서 제목';
   COMMENT ON COLUMN "XNOTIMASREQDET"."CUSALS" IS '고객 호칭';
   COMMENT ON COLUMN "XNOTIMASREQDET"."CONTENT" IS '본문';
   COMMENT ON COLUMN "XNOTIMASREQDET"."CHANAME" IS '고지서 기관명';
   COMMENT ON COLUMN "XNOTIMASREQDET"."TELNO" IS '고지서 연락처';
   COMMENT ON COLUMN "XNOTIMASREQDET"."OPT_CONTENT" IS '추가 메시지';
   COMMENT ON COLUMN "XNOTIMASREQDET"."FOOTER1" IS '푸터1';
   COMMENT ON COLUMN "XNOTIMASREQDET"."FOOTER2" IS '푸터2';
   COMMENT ON COLUMN "XNOTIMASREQDET"."FOOTER3" IS '푸터3';
   COMMENT ON COLUMN "XNOTIMASREQDET"."OWNERTEL" IS '기관 대표번호';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ADDRESS" IS '기관 주소';
   COMMENT ON COLUMN "XNOTIMASREQDET"."NOTIMASCD" IS '청구번호';
   COMMENT ON COLUMN "XNOTIMASREQDET"."VANO" IS '가상계좌번호';
   COMMENT ON COLUMN "XNOTIMASREQDET"."CUSNAME" IS '고객명';
   COMMENT ON COLUMN "XNOTIMASREQDET"."CUSGUBN1" IS '고객구분1';
   COMMENT ON COLUMN "XNOTIMASREQDET"."CUSGUBN2" IS '고객구분2';
   COMMENT ON COLUMN "XNOTIMASREQDET"."CUSGUBN3" IS '고객구분3';
   COMMENT ON COLUMN "XNOTIMASREQDET"."CUSGUBN4" IS '고객구분4';
   COMMENT ON COLUMN "XNOTIMASREQDET"."NOTIAMT" IS '청구총액';
   COMMENT ON COLUMN "XNOTIMASREQDET"."DUE_DT" IS '납부마감일자';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ITEM1_NAME" IS '청구항목1 이름';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ITEM1_AMT" IS '청구항목1 금액';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ITEM1_REMARK" IS '청구항목1 비고';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ITEM2_NAME" IS '청구항목2 이름';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ITEM2_AMT" IS '청구항목2 금액';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ITEM2_REMARK" IS '청구항목2 비고';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ITEM3_NAME" IS '청구항목3 이름';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ITEM3_AMT" IS '청구항목3 금액';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ITEM3_REMARK" IS '청구항목3 비고';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ITEM4_NAME" IS '청구항목4 이름';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ITEM4_AMT" IS '청구항목4 금액';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ITEM4_REMARK" IS '청구항목4 비고';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ITEM5_NAME" IS '청구항목5 이름';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ITEM5_AMT" IS '청구항목5 금액';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ITEM5_REMARK" IS '청구항목5 비고';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ITEM6_NAME" IS '청구항목6 이름';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ITEM6_AMT" IS '청구항목6 금액';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ITEM6_REMARK" IS '청구항목6 비고';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ITEM7_NAME" IS '청구항목7 이름';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ITEM7_AMT" IS '청구항목7 금액';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ITEM7_REMARK" IS '청구항목7 비고';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ITEM8_NAME" IS '청구항목8 이름';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ITEM8_AMT" IS '청구항목8 금액';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ITEM8_REMARK" IS '청구항목8 비고';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ITEM9_NAME" IS '청구항목9 이름';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ITEM9_AMT" IS '청구항목9 금액';
   COMMENT ON COLUMN "XNOTIMASREQDET"."ITEM9_REMARK" IS '청구항목9 비고';
--------------------------------------------------------
--  DDL for Index XNOTIMASREQDET_PK
--------------------------------------------------------
  CREATE UNIQUE INDEX "XNOTIMASREQDET_PK" ON "XNOTIMASREQDET" ("NOTIMASREQCD", "SEQ_NO") ;

--------------------------------------------------------
--  Constraints for Table XNOTIMASREQDET
--------------------------------------------------------
  ALTER TABLE "XNOTIMASREQDET" ADD CONSTRAINT "XNOTIMASREQDET_PK" PRIMARY KEY ("NOTIMASREQCD", "SEQ_NO");
  ALTER TABLE "XNOTIMASREQDET" MODIFY ("SEQ_NO" NOT NULL ENABLE);
  ALTER TABLE "XNOTIMASREQDET" MODIFY ("NOTIMASREQCD" NOT NULL ENABLE);



--------------------------------------------------------
--  DDL for Table XNOTIMASREQ
--------------------------------------------------------
  ALTER TABLE "XNOTIMASREQ"
  ADD (
    "DLVR_TYPE_CD" CHAR(6 BYTE) DEFAULT 'N00001',
    "MAKER" VARCHAR2(100 BYTE) NOT NULL,
    "MAKEDT" DATE NOT NULL,
    "RES_STS_CD" CHAR(6 BYTE) DEFAULT 'N11000',
    "FILEDT" CHAR(8 BYTE)
  );

  COMMENT ON COLUMN "XNOTIMASREQ"."DLVR_TYPE_CD" IS '배송 구분 코드 (N0)';
  COMMENT ON COLUMN "XNOTIMASREQ"."MAKER" IS '변경자';
  COMMENT ON COLUMN "XNOTIMASREQ"."MAKEDT" IS '변경일자';
  COMMENT ON COLUMN "XNOTIMASREQ"."RES_STS_CD" IS '처리 상태 코드 (N1)';
  COMMENT ON COLUMN "XNOTIMASREQ"."FILEDT" IS '파일 날짜 (yyyyMMdd)';

  ALTER TABLE XNOTIMASREQ
  DROP CONSTRAINT XNOTIMASREQ_PK;

  ALTER TABLE XNOTIMASREQ
  ADD CONSTRAINT XNOTIMASREQ_PK PRIMARY KEY
  (
    NOTIMASREQCD
  )
  ENABLE;


  UPDATE "XNOTIMASREQ"
  SET DLVR_TYPE_CD='N00001',
      MAKER=CHACD
      MAKEDT=REGDT
      RES_STS_CD='N12000'
  ;

--------------------------------------------------------
--  DDL for Table XCHALIST
--------------------------------------------------------
  ALTER TABLE "XCHALIST"
  ADD (
    "PRN_FREE_YN" CHAR(1 BYTE) DEFAULT 'N' NOT NULL
  )

  COMMENT ON COLUMN "XCHALIST"."PRN_FREE_YN" IS '출력 요금 면제 여부'

--------------------------------------------------------
--  DDL for Table XDAYSUM
--------------------------------------------------------
  ALTER TABLE "XDAYSUM"
  ADD (
    "PRN_COUNT" NUMBER(9, 0) DEFAULT 0 NOT NULL,
    "PRN_FEE" NUMBER(14, 0) DEFAULT 0 NOT NULL
  )

  COMMENT ON COLUMN "XDAYSUM"."PRN_COUNT" IS '출력 건수';
  COMMENT ON COLUMN "XDAYSUM"."PRN_FEE" IS '출력 요금';


--------------------------------------------------------
--  DDL for Table XMONTHSUM
--------------------------------------------------------
  ALTER TABLE "XMONTHSUM"
  ADD (
    "PRNCNT" NUMBER(9, 0) DEFAULT 0 NOT NULL,
    "PRNFEE" NUMBER(14, 0) DEFAULT 0 NOT NULL
  )

  COMMENT ON COLUMN "XMONTHSUM"."PRNCNT" IS '출력 건수';
  COMMENT ON COLUMN "XMONTHSUM"."PRNFEE" IS '출력 요금';
