/* ********************************************************************************************************************
 * XCHALIST 기관정보 테이블 MAND_RCP_YN 추가 생성
 *
 * @author denny91@finger.co.kr
 ******************************************************************************************************************** */
ALTER TABLE XCHALIST
ADD (MAND_RCP_YN CHAR(1 BYTE) DEFAULT 'N' );
COMMENT ON COLUMN XCASHMAS.MAND_RCP_YN is '현금영수증 의무발행여부';

CREATE SEQUENCE XCASHHST_ID_SEQ INCREMENT BY 1 START WITH 10000000000000000000 MAXVALUE 99999999999999999999 MINVALUE 10000000000000000000;

CREATE TABLE XCASHHST
(
CASHMASCD CHAR(20 BYTE) NOT NULL ENABLE,
REQUEST_USER VARCHAR2(20 BYTE) NOT NULL ENABLE,
REQUEST_DATE DATE NOT NULL ENABLE,
REQUEST_TYPE_CD CHAR(1 BYTE) NOT NULL ENABLE,
RESULT_CD CHAR(1 BYTE),
RESPONSE_USER VARCHAR2(20 BYTE),
RESPONSE_DATE DATE,
CUSOFFNO CHAR(20 BYTE),
RCPAMT NUMBER(14,0) NOT NULL ENABLE,
TAX NUMBER(14,0),
FW_CASH_RECEIPT_MASTER_ID CHAR(20 BYTE),
CHACD CHAR(8 BYTE) NOT NULL ENABLE,
CASHHST_ID CHAR(20 BYTE) NOT NULL ENABLE,
CONSTRAINT XCASHHST_PK PRIMARY KEY (CASHHST_ID)
);

COMMENT ON COLUMN XCASHHST.CASHMASCD IS 'CASHMASCD';
COMMENT ON COLUMN XCASHHST.REQUEST_USER IS '조작자';
COMMENT ON COLUMN XCASHHST.REQUEST_DATE IS '조작일시';
COMMENT ON COLUMN XCASHHST.REQUEST_TYPE_CD IS '(I 발행,U 재발행,D 취소)';
COMMENT ON COLUMN XCASHHST.RESULT_CD IS '(0 성공,1 실패,2 철회, 3 요청(빈값))';
COMMENT ON COLUMN XCASHHST.RESPONSE_USER IS '수신자';
COMMENT ON COLUMN XCASHHST.RESPONSE_DATE IS '수신일시';
COMMENT ON COLUMN XCASHHST.CUSOFFNO IS '현금영수증 발행번호';
COMMENT ON COLUMN XCASHHST.RCPAMT IS '거래금액';
COMMENT ON COLUMN XCASHHST.TAX IS '부가세';
COMMENT ON COLUMN XCASHHST.FW_CASH_RECEIPT_MASTER_ID IS 'FW_CASH_RECEIPT_MASTER_ID';
COMMENT ON COLUMN XCASHHST.CHACD IS '기관코드';
COMMENT ON COLUMN XCASHHST.CASHHST_ID IS 'ID';