package kr.co.finger.shinhandamoa.data.table.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AtreqExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table atreq
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table atreq
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table atreq
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atreq
     *
     * @mbg.generated
     */
    public AtreqExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atreq
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atreq
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atreq
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atreq
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atreq
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atreq
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atreq
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atreq
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atreq
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table atreq
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table atreq
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCmidIsNull() {
            addCriterion("cmid is null");
            return (Criteria) this;
        }

        public Criteria andCmidIsNotNull() {
            addCriterion("cmid is not null");
            return (Criteria) this;
        }

        public Criteria andCmidEqualTo(String value) {
            addCriterion("cmid =", value, "cmid");
            return (Criteria) this;
        }

        public Criteria andCmidNotEqualTo(String value) {
            addCriterion("cmid <>", value, "cmid");
            return (Criteria) this;
        }

        public Criteria andCmidGreaterThan(String value) {
            addCriterion("cmid >", value, "cmid");
            return (Criteria) this;
        }

        public Criteria andCmidGreaterThanOrEqualTo(String value) {
            addCriterion("cmid >=", value, "cmid");
            return (Criteria) this;
        }

        public Criteria andCmidLessThan(String value) {
            addCriterion("cmid <", value, "cmid");
            return (Criteria) this;
        }

        public Criteria andCmidLessThanOrEqualTo(String value) {
            addCriterion("cmid <=", value, "cmid");
            return (Criteria) this;
        }

        public Criteria andCmidLike(String value) {
            addCriterion("cmid like", value, "cmid");
            return (Criteria) this;
        }

        public Criteria andCmidNotLike(String value) {
            addCriterion("cmid not like", value, "cmid");
            return (Criteria) this;
        }

        public Criteria andCmidIn(List<String> values) {
            addCriterion("cmid in", values, "cmid");
            return (Criteria) this;
        }

        public Criteria andCmidNotIn(List<String> values) {
            addCriterion("cmid not in", values, "cmid");
            return (Criteria) this;
        }

        public Criteria andCmidBetween(String value1, String value2) {
            addCriterion("cmid between", value1, value2, "cmid");
            return (Criteria) this;
        }

        public Criteria andCmidNotBetween(String value1, String value2) {
            addCriterion("cmid not between", value1, value2, "cmid");
            return (Criteria) this;
        }

        public Criteria andTrxkeyIsNull() {
            addCriterion("trxkey is null");
            return (Criteria) this;
        }

        public Criteria andTrxkeyIsNotNull() {
            addCriterion("trxkey is not null");
            return (Criteria) this;
        }

        public Criteria andTrxkeyEqualTo(String value) {
            addCriterion("trxkey =", value, "trxkey");
            return (Criteria) this;
        }

        public Criteria andTrxkeyNotEqualTo(String value) {
            addCriterion("trxkey <>", value, "trxkey");
            return (Criteria) this;
        }

        public Criteria andTrxkeyGreaterThan(String value) {
            addCriterion("trxkey >", value, "trxkey");
            return (Criteria) this;
        }

        public Criteria andTrxkeyGreaterThanOrEqualTo(String value) {
            addCriterion("trxkey >=", value, "trxkey");
            return (Criteria) this;
        }

        public Criteria andTrxkeyLessThan(String value) {
            addCriterion("trxkey <", value, "trxkey");
            return (Criteria) this;
        }

        public Criteria andTrxkeyLessThanOrEqualTo(String value) {
            addCriterion("trxkey <=", value, "trxkey");
            return (Criteria) this;
        }

        public Criteria andTrxkeyLike(String value) {
            addCriterion("trxkey like", value, "trxkey");
            return (Criteria) this;
        }

        public Criteria andTrxkeyNotLike(String value) {
            addCriterion("trxkey not like", value, "trxkey");
            return (Criteria) this;
        }

        public Criteria andTrxkeyIn(List<String> values) {
            addCriterion("trxkey in", values, "trxkey");
            return (Criteria) this;
        }

        public Criteria andTrxkeyNotIn(List<String> values) {
            addCriterion("trxkey not in", values, "trxkey");
            return (Criteria) this;
        }

        public Criteria andTrxkeyBetween(String value1, String value2) {
            addCriterion("trxkey between", value1, value2, "trxkey");
            return (Criteria) this;
        }

        public Criteria andTrxkeyNotBetween(String value1, String value2) {
            addCriterion("trxkey not between", value1, value2, "trxkey");
            return (Criteria) this;
        }

        public Criteria andChacdIsNull() {
            addCriterion("chacd is null");
            return (Criteria) this;
        }

        public Criteria andChacdIsNotNull() {
            addCriterion("chacd is not null");
            return (Criteria) this;
        }

        public Criteria andChacdEqualTo(String value) {
            addCriterion("chacd =", value, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdNotEqualTo(String value) {
            addCriterion("chacd <>", value, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdGreaterThan(String value) {
            addCriterion("chacd >", value, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdGreaterThanOrEqualTo(String value) {
            addCriterion("chacd >=", value, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdLessThan(String value) {
            addCriterion("chacd <", value, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdLessThanOrEqualTo(String value) {
            addCriterion("chacd <=", value, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdLike(String value) {
            addCriterion("chacd like", value, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdNotLike(String value) {
            addCriterion("chacd not like", value, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdIn(List<String> values) {
            addCriterion("chacd in", values, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdNotIn(List<String> values) {
            addCriterion("chacd not in", values, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdBetween(String value1, String value2) {
            addCriterion("chacd between", value1, value2, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdNotBetween(String value1, String value2) {
            addCriterion("chacd not between", value1, value2, "chacd");
            return (Criteria) this;
        }

        public Criteria andChatelnoIsNull() {
            addCriterion("chatelno is null");
            return (Criteria) this;
        }

        public Criteria andChatelnoIsNotNull() {
            addCriterion("chatelno is not null");
            return (Criteria) this;
        }

        public Criteria andChatelnoEqualTo(String value) {
            addCriterion("chatelno =", value, "chatelno");
            return (Criteria) this;
        }

        public Criteria andChatelnoNotEqualTo(String value) {
            addCriterion("chatelno <>", value, "chatelno");
            return (Criteria) this;
        }

        public Criteria andChatelnoGreaterThan(String value) {
            addCriterion("chatelno >", value, "chatelno");
            return (Criteria) this;
        }

        public Criteria andChatelnoGreaterThanOrEqualTo(String value) {
            addCriterion("chatelno >=", value, "chatelno");
            return (Criteria) this;
        }

        public Criteria andChatelnoLessThan(String value) {
            addCriterion("chatelno <", value, "chatelno");
            return (Criteria) this;
        }

        public Criteria andChatelnoLessThanOrEqualTo(String value) {
            addCriterion("chatelno <=", value, "chatelno");
            return (Criteria) this;
        }

        public Criteria andChatelnoLike(String value) {
            addCriterion("chatelno like", value, "chatelno");
            return (Criteria) this;
        }

        public Criteria andChatelnoNotLike(String value) {
            addCriterion("chatelno not like", value, "chatelno");
            return (Criteria) this;
        }

        public Criteria andChatelnoIn(List<String> values) {
            addCriterion("chatelno in", values, "chatelno");
            return (Criteria) this;
        }

        public Criteria andChatelnoNotIn(List<String> values) {
            addCriterion("chatelno not in", values, "chatelno");
            return (Criteria) this;
        }

        public Criteria andChatelnoBetween(String value1, String value2) {
            addCriterion("chatelno between", value1, value2, "chatelno");
            return (Criteria) this;
        }

        public Criteria andChatelnoNotBetween(String value1, String value2) {
            addCriterion("chatelno not between", value1, value2, "chatelno");
            return (Criteria) this;
        }

        public Criteria andCustelnoIsNull() {
            addCriterion("custelno is null");
            return (Criteria) this;
        }

        public Criteria andCustelnoIsNotNull() {
            addCriterion("custelno is not null");
            return (Criteria) this;
        }

        public Criteria andCustelnoEqualTo(String value) {
            addCriterion("custelno =", value, "custelno");
            return (Criteria) this;
        }

        public Criteria andCustelnoNotEqualTo(String value) {
            addCriterion("custelno <>", value, "custelno");
            return (Criteria) this;
        }

        public Criteria andCustelnoGreaterThan(String value) {
            addCriterion("custelno >", value, "custelno");
            return (Criteria) this;
        }

        public Criteria andCustelnoGreaterThanOrEqualTo(String value) {
            addCriterion("custelno >=", value, "custelno");
            return (Criteria) this;
        }

        public Criteria andCustelnoLessThan(String value) {
            addCriterion("custelno <", value, "custelno");
            return (Criteria) this;
        }

        public Criteria andCustelnoLessThanOrEqualTo(String value) {
            addCriterion("custelno <=", value, "custelno");
            return (Criteria) this;
        }

        public Criteria andCustelnoLike(String value) {
            addCriterion("custelno like", value, "custelno");
            return (Criteria) this;
        }

        public Criteria andCustelnoNotLike(String value) {
            addCriterion("custelno not like", value, "custelno");
            return (Criteria) this;
        }

        public Criteria andCustelnoIn(List<String> values) {
            addCriterion("custelno in", values, "custelno");
            return (Criteria) this;
        }

        public Criteria andCustelnoNotIn(List<String> values) {
            addCriterion("custelno not in", values, "custelno");
            return (Criteria) this;
        }

        public Criteria andCustelnoBetween(String value1, String value2) {
            addCriterion("custelno between", value1, value2, "custelno");
            return (Criteria) this;
        }

        public Criteria andCustelnoNotBetween(String value1, String value2) {
            addCriterion("custelno not between", value1, value2, "custelno");
            return (Criteria) this;
        }

        public Criteria andSendmsgIsNull() {
            addCriterion("sendmsg is null");
            return (Criteria) this;
        }

        public Criteria andSendmsgIsNotNull() {
            addCriterion("sendmsg is not null");
            return (Criteria) this;
        }

        public Criteria andSendmsgEqualTo(String value) {
            addCriterion("sendmsg =", value, "sendmsg");
            return (Criteria) this;
        }

        public Criteria andSendmsgNotEqualTo(String value) {
            addCriterion("sendmsg <>", value, "sendmsg");
            return (Criteria) this;
        }

        public Criteria andSendmsgGreaterThan(String value) {
            addCriterion("sendmsg >", value, "sendmsg");
            return (Criteria) this;
        }

        public Criteria andSendmsgGreaterThanOrEqualTo(String value) {
            addCriterion("sendmsg >=", value, "sendmsg");
            return (Criteria) this;
        }

        public Criteria andSendmsgLessThan(String value) {
            addCriterion("sendmsg <", value, "sendmsg");
            return (Criteria) this;
        }

        public Criteria andSendmsgLessThanOrEqualTo(String value) {
            addCriterion("sendmsg <=", value, "sendmsg");
            return (Criteria) this;
        }

        public Criteria andSendmsgLike(String value) {
            addCriterion("sendmsg like", value, "sendmsg");
            return (Criteria) this;
        }

        public Criteria andSendmsgNotLike(String value) {
            addCriterion("sendmsg not like", value, "sendmsg");
            return (Criteria) this;
        }

        public Criteria andSendmsgIn(List<String> values) {
            addCriterion("sendmsg in", values, "sendmsg");
            return (Criteria) this;
        }

        public Criteria andSendmsgNotIn(List<String> values) {
            addCriterion("sendmsg not in", values, "sendmsg");
            return (Criteria) this;
        }

        public Criteria andSendmsgBetween(String value1, String value2) {
            addCriterion("sendmsg between", value1, value2, "sendmsg");
            return (Criteria) this;
        }

        public Criteria andSendmsgNotBetween(String value1, String value2) {
            addCriterion("sendmsg not between", value1, value2, "sendmsg");
            return (Criteria) this;
        }

        public Criteria andMsgtypeIsNull() {
            addCriterion("msgtype is null");
            return (Criteria) this;
        }

        public Criteria andMsgtypeIsNotNull() {
            addCriterion("msgtype is not null");
            return (Criteria) this;
        }

        public Criteria andMsgtypeEqualTo(String value) {
            addCriterion("msgtype =", value, "msgtype");
            return (Criteria) this;
        }

        public Criteria andMsgtypeNotEqualTo(String value) {
            addCriterion("msgtype <>", value, "msgtype");
            return (Criteria) this;
        }

        public Criteria andMsgtypeGreaterThan(String value) {
            addCriterion("msgtype >", value, "msgtype");
            return (Criteria) this;
        }

        public Criteria andMsgtypeGreaterThanOrEqualTo(String value) {
            addCriterion("msgtype >=", value, "msgtype");
            return (Criteria) this;
        }

        public Criteria andMsgtypeLessThan(String value) {
            addCriterion("msgtype <", value, "msgtype");
            return (Criteria) this;
        }

        public Criteria andMsgtypeLessThanOrEqualTo(String value) {
            addCriterion("msgtype <=", value, "msgtype");
            return (Criteria) this;
        }

        public Criteria andMsgtypeLike(String value) {
            addCriterion("msgtype like", value, "msgtype");
            return (Criteria) this;
        }

        public Criteria andMsgtypeNotLike(String value) {
            addCriterion("msgtype not like", value, "msgtype");
            return (Criteria) this;
        }

        public Criteria andMsgtypeIn(List<String> values) {
            addCriterion("msgtype in", values, "msgtype");
            return (Criteria) this;
        }

        public Criteria andMsgtypeNotIn(List<String> values) {
            addCriterion("msgtype not in", values, "msgtype");
            return (Criteria) this;
        }

        public Criteria andMsgtypeBetween(String value1, String value2) {
            addCriterion("msgtype between", value1, value2, "msgtype");
            return (Criteria) this;
        }

        public Criteria andMsgtypeNotBetween(String value1, String value2) {
            addCriterion("msgtype not between", value1, value2, "msgtype");
            return (Criteria) this;
        }

        public Criteria andSendstatuscdIsNull() {
            addCriterion("sendstatuscd is null");
            return (Criteria) this;
        }

        public Criteria andSendstatuscdIsNotNull() {
            addCriterion("sendstatuscd is not null");
            return (Criteria) this;
        }

        public Criteria andSendstatuscdEqualTo(String value) {
            addCriterion("sendstatuscd =", value, "sendstatuscd");
            return (Criteria) this;
        }

        public Criteria andSendstatuscdNotEqualTo(String value) {
            addCriterion("sendstatuscd <>", value, "sendstatuscd");
            return (Criteria) this;
        }

        public Criteria andSendstatuscdGreaterThan(String value) {
            addCriterion("sendstatuscd >", value, "sendstatuscd");
            return (Criteria) this;
        }

        public Criteria andSendstatuscdGreaterThanOrEqualTo(String value) {
            addCriterion("sendstatuscd >=", value, "sendstatuscd");
            return (Criteria) this;
        }

        public Criteria andSendstatuscdLessThan(String value) {
            addCriterion("sendstatuscd <", value, "sendstatuscd");
            return (Criteria) this;
        }

        public Criteria andSendstatuscdLessThanOrEqualTo(String value) {
            addCriterion("sendstatuscd <=", value, "sendstatuscd");
            return (Criteria) this;
        }

        public Criteria andSendstatuscdLike(String value) {
            addCriterion("sendstatuscd like", value, "sendstatuscd");
            return (Criteria) this;
        }

        public Criteria andSendstatuscdNotLike(String value) {
            addCriterion("sendstatuscd not like", value, "sendstatuscd");
            return (Criteria) this;
        }

        public Criteria andSendstatuscdIn(List<String> values) {
            addCriterion("sendstatuscd in", values, "sendstatuscd");
            return (Criteria) this;
        }

        public Criteria andSendstatuscdNotIn(List<String> values) {
            addCriterion("sendstatuscd not in", values, "sendstatuscd");
            return (Criteria) this;
        }

        public Criteria andSendstatuscdBetween(String value1, String value2) {
            addCriterion("sendstatuscd between", value1, value2, "sendstatuscd");
            return (Criteria) this;
        }

        public Criteria andSendstatuscdNotBetween(String value1, String value2) {
            addCriterion("sendstatuscd not between", value1, value2, "sendstatuscd");
            return (Criteria) this;
        }

        public Criteria andSendresultcdIsNull() {
            addCriterion("sendresultcd is null");
            return (Criteria) this;
        }

        public Criteria andSendresultcdIsNotNull() {
            addCriterion("sendresultcd is not null");
            return (Criteria) this;
        }

        public Criteria andSendresultcdEqualTo(String value) {
            addCriterion("sendresultcd =", value, "sendresultcd");
            return (Criteria) this;
        }

        public Criteria andSendresultcdNotEqualTo(String value) {
            addCriterion("sendresultcd <>", value, "sendresultcd");
            return (Criteria) this;
        }

        public Criteria andSendresultcdGreaterThan(String value) {
            addCriterion("sendresultcd >", value, "sendresultcd");
            return (Criteria) this;
        }

        public Criteria andSendresultcdGreaterThanOrEqualTo(String value) {
            addCriterion("sendresultcd >=", value, "sendresultcd");
            return (Criteria) this;
        }

        public Criteria andSendresultcdLessThan(String value) {
            addCriterion("sendresultcd <", value, "sendresultcd");
            return (Criteria) this;
        }

        public Criteria andSendresultcdLessThanOrEqualTo(String value) {
            addCriterion("sendresultcd <=", value, "sendresultcd");
            return (Criteria) this;
        }

        public Criteria andSendresultcdLike(String value) {
            addCriterion("sendresultcd like", value, "sendresultcd");
            return (Criteria) this;
        }

        public Criteria andSendresultcdNotLike(String value) {
            addCriterion("sendresultcd not like", value, "sendresultcd");
            return (Criteria) this;
        }

        public Criteria andSendresultcdIn(List<String> values) {
            addCriterion("sendresultcd in", values, "sendresultcd");
            return (Criteria) this;
        }

        public Criteria andSendresultcdNotIn(List<String> values) {
            addCriterion("sendresultcd not in", values, "sendresultcd");
            return (Criteria) this;
        }

        public Criteria andSendresultcdBetween(String value1, String value2) {
            addCriterion("sendresultcd between", value1, value2, "sendresultcd");
            return (Criteria) this;
        }

        public Criteria andSendresultcdNotBetween(String value1, String value2) {
            addCriterion("sendresultcd not between", value1, value2, "sendresultcd");
            return (Criteria) this;
        }

        public Criteria andSenddateIsNull() {
            addCriterion("senddate is null");
            return (Criteria) this;
        }

        public Criteria andSenddateIsNotNull() {
            addCriterion("senddate is not null");
            return (Criteria) this;
        }

        public Criteria andSenddateEqualTo(Date value) {
            addCriterion("senddate =", value, "senddate");
            return (Criteria) this;
        }

        public Criteria andSenddateNotEqualTo(Date value) {
            addCriterion("senddate <>", value, "senddate");
            return (Criteria) this;
        }

        public Criteria andSenddateGreaterThan(Date value) {
            addCriterion("senddate >", value, "senddate");
            return (Criteria) this;
        }

        public Criteria andSenddateGreaterThanOrEqualTo(Date value) {
            addCriterion("senddate >=", value, "senddate");
            return (Criteria) this;
        }

        public Criteria andSenddateLessThan(Date value) {
            addCriterion("senddate <", value, "senddate");
            return (Criteria) this;
        }

        public Criteria andSenddateLessThanOrEqualTo(Date value) {
            addCriterion("senddate <=", value, "senddate");
            return (Criteria) this;
        }

        public Criteria andSenddateIn(List<Date> values) {
            addCriterion("senddate in", values, "senddate");
            return (Criteria) this;
        }

        public Criteria andSenddateNotIn(List<Date> values) {
            addCriterion("senddate not in", values, "senddate");
            return (Criteria) this;
        }

        public Criteria andSenddateBetween(Date value1, Date value2) {
            addCriterion("senddate between", value1, value2, "senddate");
            return (Criteria) this;
        }

        public Criteria andSenddateNotBetween(Date value1, Date value2) {
            addCriterion("senddate not between", value1, value2, "senddate");
            return (Criteria) this;
        }

        public Criteria andNotimascdIsNull() {
            addCriterion("notimascd is null");
            return (Criteria) this;
        }

        public Criteria andNotimascdIsNotNull() {
            addCriterion("notimascd is not null");
            return (Criteria) this;
        }

        public Criteria andNotimascdEqualTo(String value) {
            addCriterion("notimascd =", value, "notimascd");
            return (Criteria) this;
        }

        public Criteria andNotimascdNotEqualTo(String value) {
            addCriterion("notimascd <>", value, "notimascd");
            return (Criteria) this;
        }

        public Criteria andNotimascdGreaterThan(String value) {
            addCriterion("notimascd >", value, "notimascd");
            return (Criteria) this;
        }

        public Criteria andNotimascdGreaterThanOrEqualTo(String value) {
            addCriterion("notimascd >=", value, "notimascd");
            return (Criteria) this;
        }

        public Criteria andNotimascdLessThan(String value) {
            addCriterion("notimascd <", value, "notimascd");
            return (Criteria) this;
        }

        public Criteria andNotimascdLessThanOrEqualTo(String value) {
            addCriterion("notimascd <=", value, "notimascd");
            return (Criteria) this;
        }

        public Criteria andNotimascdLike(String value) {
            addCriterion("notimascd like", value, "notimascd");
            return (Criteria) this;
        }

        public Criteria andNotimascdNotLike(String value) {
            addCriterion("notimascd not like", value, "notimascd");
            return (Criteria) this;
        }

        public Criteria andNotimascdIn(List<String> values) {
            addCriterion("notimascd in", values, "notimascd");
            return (Criteria) this;
        }

        public Criteria andNotimascdNotIn(List<String> values) {
            addCriterion("notimascd not in", values, "notimascd");
            return (Criteria) this;
        }

        public Criteria andNotimascdBetween(String value1, String value2) {
            addCriterion("notimascd between", value1, value2, "notimascd");
            return (Criteria) this;
        }

        public Criteria andNotimascdNotBetween(String value1, String value2) {
            addCriterion("notimascd not between", value1, value2, "notimascd");
            return (Criteria) this;
        }

        public Criteria andPaymascdIsNull() {
            addCriterion("paymascd is null");
            return (Criteria) this;
        }

        public Criteria andPaymascdIsNotNull() {
            addCriterion("paymascd is not null");
            return (Criteria) this;
        }

        public Criteria andPaymascdEqualTo(String value) {
            addCriterion("paymascd =", value, "paymascd");
            return (Criteria) this;
        }

        public Criteria andPaymascdNotEqualTo(String value) {
            addCriterion("paymascd <>", value, "paymascd");
            return (Criteria) this;
        }

        public Criteria andPaymascdGreaterThan(String value) {
            addCriterion("paymascd >", value, "paymascd");
            return (Criteria) this;
        }

        public Criteria andPaymascdGreaterThanOrEqualTo(String value) {
            addCriterion("paymascd >=", value, "paymascd");
            return (Criteria) this;
        }

        public Criteria andPaymascdLessThan(String value) {
            addCriterion("paymascd <", value, "paymascd");
            return (Criteria) this;
        }

        public Criteria andPaymascdLessThanOrEqualTo(String value) {
            addCriterion("paymascd <=", value, "paymascd");
            return (Criteria) this;
        }

        public Criteria andPaymascdLike(String value) {
            addCriterion("paymascd like", value, "paymascd");
            return (Criteria) this;
        }

        public Criteria andPaymascdNotLike(String value) {
            addCriterion("paymascd not like", value, "paymascd");
            return (Criteria) this;
        }

        public Criteria andPaymascdIn(List<String> values) {
            addCriterion("paymascd in", values, "paymascd");
            return (Criteria) this;
        }

        public Criteria andPaymascdNotIn(List<String> values) {
            addCriterion("paymascd not in", values, "paymascd");
            return (Criteria) this;
        }

        public Criteria andPaymascdBetween(String value1, String value2) {
            addCriterion("paymascd between", value1, value2, "paymascd");
            return (Criteria) this;
        }

        public Criteria andPaymascdNotBetween(String value1, String value2) {
            addCriterion("paymascd not between", value1, value2, "paymascd");
            return (Criteria) this;
        }

        public Criteria andMakedtIsNull() {
            addCriterion("makedt is null");
            return (Criteria) this;
        }

        public Criteria andMakedtIsNotNull() {
            addCriterion("makedt is not null");
            return (Criteria) this;
        }

        public Criteria andMakedtEqualTo(Date value) {
            addCriterion("makedt =", value, "makedt");
            return (Criteria) this;
        }

        public Criteria andMakedtNotEqualTo(Date value) {
            addCriterion("makedt <>", value, "makedt");
            return (Criteria) this;
        }

        public Criteria andMakedtGreaterThan(Date value) {
            addCriterion("makedt >", value, "makedt");
            return (Criteria) this;
        }

        public Criteria andMakedtGreaterThanOrEqualTo(Date value) {
            addCriterion("makedt >=", value, "makedt");
            return (Criteria) this;
        }

        public Criteria andMakedtLessThan(Date value) {
            addCriterion("makedt <", value, "makedt");
            return (Criteria) this;
        }

        public Criteria andMakedtLessThanOrEqualTo(Date value) {
            addCriterion("makedt <=", value, "makedt");
            return (Criteria) this;
        }

        public Criteria andMakedtIn(List<Date> values) {
            addCriterion("makedt in", values, "makedt");
            return (Criteria) this;
        }

        public Criteria andMakedtNotIn(List<Date> values) {
            addCriterion("makedt not in", values, "makedt");
            return (Criteria) this;
        }

        public Criteria andMakedtBetween(Date value1, Date value2) {
            addCriterion("makedt between", value1, value2, "makedt");
            return (Criteria) this;
        }

        public Criteria andMakedtNotBetween(Date value1, Date value2) {
            addCriterion("makedt not between", value1, value2, "makedt");
            return (Criteria) this;
        }

        public Criteria andMakerIsNull() {
            addCriterion("maker is null");
            return (Criteria) this;
        }

        public Criteria andMakerIsNotNull() {
            addCriterion("maker is not null");
            return (Criteria) this;
        }

        public Criteria andMakerEqualTo(String value) {
            addCriterion("maker =", value, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerNotEqualTo(String value) {
            addCriterion("maker <>", value, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerGreaterThan(String value) {
            addCriterion("maker >", value, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerGreaterThanOrEqualTo(String value) {
            addCriterion("maker >=", value, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerLessThan(String value) {
            addCriterion("maker <", value, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerLessThanOrEqualTo(String value) {
            addCriterion("maker <=", value, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerLike(String value) {
            addCriterion("maker like", value, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerNotLike(String value) {
            addCriterion("maker not like", value, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerIn(List<String> values) {
            addCriterion("maker in", values, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerNotIn(List<String> values) {
            addCriterion("maker not in", values, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerBetween(String value1, String value2) {
            addCriterion("maker between", value1, value2, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerNotBetween(String value1, String value2) {
            addCriterion("maker not between", value1, value2, "maker");
            return (Criteria) this;
        }

        public Criteria andReportdateIsNull() {
            addCriterion("reportdate is null");
            return (Criteria) this;
        }

        public Criteria andReportdateIsNotNull() {
            addCriterion("reportdate is not null");
            return (Criteria) this;
        }

        public Criteria andReportdateEqualTo(Date value) {
            addCriterion("reportdate =", value, "reportdate");
            return (Criteria) this;
        }

        public Criteria andReportdateNotEqualTo(Date value) {
            addCriterion("reportdate <>", value, "reportdate");
            return (Criteria) this;
        }

        public Criteria andReportdateGreaterThan(Date value) {
            addCriterion("reportdate >", value, "reportdate");
            return (Criteria) this;
        }

        public Criteria andReportdateGreaterThanOrEqualTo(Date value) {
            addCriterion("reportdate >=", value, "reportdate");
            return (Criteria) this;
        }

        public Criteria andReportdateLessThan(Date value) {
            addCriterion("reportdate <", value, "reportdate");
            return (Criteria) this;
        }

        public Criteria andReportdateLessThanOrEqualTo(Date value) {
            addCriterion("reportdate <=", value, "reportdate");
            return (Criteria) this;
        }

        public Criteria andReportdateIn(List<Date> values) {
            addCriterion("reportdate in", values, "reportdate");
            return (Criteria) this;
        }

        public Criteria andReportdateNotIn(List<Date> values) {
            addCriterion("reportdate not in", values, "reportdate");
            return (Criteria) this;
        }

        public Criteria andReportdateBetween(Date value1, Date value2) {
            addCriterion("reportdate between", value1, value2, "reportdate");
            return (Criteria) this;
        }

        public Criteria andReportdateNotBetween(Date value1, Date value2) {
            addCriterion("reportdate not between", value1, value2, "reportdate");
            return (Criteria) this;
        }

        public Criteria andCmidLikeInsensitive(String value) {
            addCriterion("upper(cmid) like", value.toUpperCase(), "cmid");
            return (Criteria) this;
        }

        public Criteria andTrxkeyLikeInsensitive(String value) {
            addCriterion("upper(trxkey) like", value.toUpperCase(), "trxkey");
            return (Criteria) this;
        }

        public Criteria andChacdLikeInsensitive(String value) {
            addCriterion("upper(chacd) like", value.toUpperCase(), "chacd");
            return (Criteria) this;
        }

        public Criteria andChatelnoLikeInsensitive(String value) {
            addCriterion("upper(chatelno) like", value.toUpperCase(), "chatelno");
            return (Criteria) this;
        }

        public Criteria andCustelnoLikeInsensitive(String value) {
            addCriterion("upper(custelno) like", value.toUpperCase(), "custelno");
            return (Criteria) this;
        }

        public Criteria andSendmsgLikeInsensitive(String value) {
            addCriterion("upper(sendmsg) like", value.toUpperCase(), "sendmsg");
            return (Criteria) this;
        }

        public Criteria andMsgtypeLikeInsensitive(String value) {
            addCriterion("upper(msgtype) like", value.toUpperCase(), "msgtype");
            return (Criteria) this;
        }

        public Criteria andSendstatuscdLikeInsensitive(String value) {
            addCriterion("upper(sendstatuscd) like", value.toUpperCase(), "sendstatuscd");
            return (Criteria) this;
        }

        public Criteria andSendresultcdLikeInsensitive(String value) {
            addCriterion("upper(sendresultcd) like", value.toUpperCase(), "sendresultcd");
            return (Criteria) this;
        }

        public Criteria andNotimascdLikeInsensitive(String value) {
            addCriterion("upper(notimascd) like", value.toUpperCase(), "notimascd");
            return (Criteria) this;
        }

        public Criteria andPaymascdLikeInsensitive(String value) {
            addCriterion("upper(paymascd) like", value.toUpperCase(), "paymascd");
            return (Criteria) this;
        }

        public Criteria andMakerLikeInsensitive(String value) {
            addCriterion("upper(maker) like", value.toUpperCase(), "maker");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table atreq
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table atreq
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}