package com.finger.shinhandamoa.data.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.finger.shinhandamoa.data.model.CashReceiptMaster;
import com.finger.shinhandamoa.data.model.CashReceiptMasterExample;

/**
 * 
 * @author jhjeong@finger.co.kr
 * @modified 2018. 10. 25.
 */
public interface CashReceiptMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FW_CASH_RECEIPT_MASTER
	 * @mbg.generated
	 */
	long countByExample(CashReceiptMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FW_CASH_RECEIPT_MASTER
	 * @mbg.generated
	 */
	int deleteByExample(CashReceiptMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FW_CASH_RECEIPT_MASTER
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FW_CASH_RECEIPT_MASTER
	 * @mbg.generated
	 */
	int insert(CashReceiptMaster record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FW_CASH_RECEIPT_MASTER
	 * @mbg.generated
	 */
	int insertSelective(CashReceiptMaster record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FW_CASH_RECEIPT_MASTER
	 * @mbg.generated
	 */
	List<CashReceiptMaster> selectByExampleWithRowbounds(CashReceiptMasterExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FW_CASH_RECEIPT_MASTER
	 * @mbg.generated
	 */
	List<CashReceiptMaster> selectByExample(CashReceiptMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FW_CASH_RECEIPT_MASTER
	 * @mbg.generated
	 */
	CashReceiptMaster selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FW_CASH_RECEIPT_MASTER
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") CashReceiptMaster record,
                                 @Param("example") CashReceiptMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FW_CASH_RECEIPT_MASTER
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") CashReceiptMaster record, @Param("example") CashReceiptMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FW_CASH_RECEIPT_MASTER
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(CashReceiptMaster record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FW_CASH_RECEIPT_MASTER
	 * @mbg.generated
	 */
	int updateByPrimaryKey(CashReceiptMaster record);
}
