--------------------------------------------------------
--  파일이 생성됨 - 수요일-7월-17-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence AEGISTRANSMSG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FINGER"."AEGISTRANSMSG_SEQ"  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 999979 NOCACHE  NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MSG_SEND_HIST_ID
--------------------------------------------------------

   CREATE SEQUENCE  "FINGER"."SEQ_MSG_SEND_HIST_ID"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1881 CACHE 20 NOORDER  CYCLE   ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PAYER_INFO_ID
--------------------------------------------------------

   CREATE SEQUENCE  "FINGER"."SEQ_PAYER_INFO_ID"  MINVALUE 1 MAXVALUE 999 INCREMENT BY 1 START WITH 421 CACHE 20 NOORDER  CYCLE   ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TRNO
--------------------------------------------------------

   CREATE SEQUENCE  "FINGER"."SEQ_TRNO"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 90421 CACHE 20 NOORDER  CYCLE   ;
--------------------------------------------------------
--  DDL for Table AEGISTRANSMSG
--------------------------------------------------------

  CREATE TABLE "FINGER"."AEGISTRANSMSG" 
   (	"RECORDTYPE" VARCHAR2(1 BYTE), 
	"SERVICEID" VARCHAR2(8 BYTE), 
	"WORKFIELD" VARCHAR2(1 BYTE), 
	"SUCCESSYN" VARCHAR2(1 BYTE), 
	"RESULTCD" VARCHAR2(4 BYTE), 
	"RESULTMSG" VARCHAR2(30 BYTE), 
	"TRNO" VARCHAR2(30 BYTE), 
	"VANO" VARCHAR2(20 BYTE), 
	"PAYMASMONTH" VARCHAR2(6 BYTE), 
	"PAYMASDT" VARCHAR2(8 BYTE), 
	"RCPSTARTDT" VARCHAR2(8 BYTE), 
	"RCPSTARTTM" VARCHAR2(4 BYTE), 
	"RCPENDDT" VARCHAR2(8 BYTE), 
	"RCPENDTM" VARCHAR2(4 BYTE), 
	"RCPPRTENDDT" VARCHAR2(8 BYTE), 
	"RCPPRTENDTM" VARCHAR2(4 BYTE), 
	"CUSNM" VARCHAR2(30 BYTE), 
	"SMSYN" VARCHAR2(1 BYTE), 
	"MOBILENO" VARCHAR2(12 BYTE), 
	"EMAILYN" VARCHAR2(1 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"CONTENT1" VARCHAR2(30 BYTE), 
	"CONTENT2" VARCHAR2(30 BYTE), 
	"CONTENT3" VARCHAR2(30 BYTE), 
	"CONTENT4" VARCHAR2(30 BYTE), 
	"CHATRNO" VARCHAR2(30 BYTE), 
	"ADJFIGRPCD" VARCHAR2(5 BYTE), 
	"PAYITEMNM" VARCHAR2(50 BYTE), 
	"PAYITEMAMT" VARCHAR2(10 BYTE), 
	"PAYITEMYN" VARCHAR2(1 BYTE), 
	"RCPITEMYN" VARCHAR2(1 BYTE), 
	"RCPBUSINESSNO" VARCHAR2(10 BYTE), 
	"RCPPERSONNO" VARCHAR2(20 BYTE), 
	"PRTPAYITEMNM" VARCHAR2(50 BYTE), 
	"PRTCONTENT1" VARCHAR2(50 BYTE), 
	"PRTSEQ" VARCHAR2(2 BYTE), 
	"TRANST" VARCHAR2(2 BYTE), 
	"REGSEQ" NUMBER(9,0), 
	"REGDT" DATE, 
	"PAYDAY" VARCHAR2(14 BYTE), 
	"RCPUSRNAME" VARCHAR2(20 BYTE), 
	"VANOBNKCD" VARCHAR2(3 BYTE), 
	"BNKCD" VARCHAR2(3 BYTE), 
	"BCHCD" VARCHAR2(4 BYTE), 
	"MDGUBN" VARCHAR2(1 BYTE), 
	"TRNDAY" VARCHAR2(14 BYTE), 
	"RCPAMT" VARCHAR2(10 BYTE), 
	"SVECD" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."RECORDTYPE" IS 'Record구분';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."SERVICEID" IS '가맹점코드';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."WORKFIELD" IS '처리내역';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."SUCCESSYN" IS '처리결과';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."RESULTCD" IS '결과코드';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."RESULTMSG" IS '결과메시지';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."TRNO" IS '청구거래번호';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."VANO" IS '등록구분';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."PAYMASMONTH" IS '청구월';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."PAYMASDT" IS '청구일자';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."RCPSTARTDT" IS '납부시작일';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."RCPSTARTTM" IS '납부시작시간';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."RCPENDDT" IS '납부마감일';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."RCPENDTM" IS '납부마감시간';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."RCPPRTENDDT" IS '출력납부마감일';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."RCPPRTENDTM" IS '출력납부마감시간';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."CUSNM" IS '고객명';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."SMSYN" IS 'SMS전송여부';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."MOBILENO" IS '고객휴대폰번호';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."EMAILYN" IS '이메일전송여부';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."EMAIL" IS '고객이메일주소';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."CONTENT1" IS '참조1';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."CONTENT2" IS '참조2';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."CONTENT3" IS '참조3';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."CONTENT4" IS '참조4';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."CHATRNO" IS '항목거래번호';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."ADJFIGRPCD" IS '분할입금KEY';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."PAYITEMNM" IS '항목명';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."PAYITEMAMT" IS '항목금액';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."PAYITEMYN" IS '항목필수여부';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."RCPITEMYN" IS '현금영수증발행여부';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."RCPBUSINESSNO" IS '현금영수증발행사업자정보';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."RCPPERSONNO" IS '현금영수증발행고객정보';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."PRTPAYITEMNM" IS '출력항목명';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."PRTCONTENT1" IS '출력비고내용';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."PRTSEQ" IS '출력순서';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."TRANST" IS '전송상태';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."REGSEQ" IS '전문번호';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."REGDT" IS '전문등록일';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."PAYDAY" IS '수납일시';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."RCPUSRNAME" IS '수납자명';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."VANOBNKCD" IS '가상계좌은행';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."BNKCD" IS '수납은행코드';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."BCHCD" IS '수납지점코드';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."MDGUBN" IS '매체구분';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."TRNDAY" IS '처리일시';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."RCPAMT" IS '총수납금액';
   COMMENT ON COLUMN "FINGER"."AEGISTRANSMSG"."SVECD" IS '수납구분';
   COMMENT ON TABLE "FINGER"."AEGISTRANSMSG"  IS '다모아인터페이스';
--------------------------------------------------------
--  DDL for Table TB_AUTH_GRP
--------------------------------------------------------

  CREATE TABLE "FINGER"."TB_AUTH_GRP" 
   (	"AUTH_GRP_CD" VARCHAR2(1 BYTE), 
	"AUTH_GRP_NM" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "FINGER"."TB_AUTH_GRP"."AUTH_GRP_CD" IS '권한그룹코드';
   COMMENT ON COLUMN "FINGER"."TB_AUTH_GRP"."AUTH_GRP_NM" IS '권한그룹명';
   COMMENT ON TABLE "FINGER"."TB_AUTH_GRP"  IS '권한그룹';
--------------------------------------------------------
--  DDL for Table TB_AUTH_MENU
--------------------------------------------------------

  CREATE TABLE "FINGER"."TB_AUTH_MENU" 
   (	"AUTH_GRP_CD" VARCHAR2(1 BYTE), 
	"MENU_ID" VARCHAR2(9 BYTE), 
	"DEFAULT_YN" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "FINGER"."TB_AUTH_MENU"."AUTH_GRP_CD" IS '권한그룹코드';
   COMMENT ON COLUMN "FINGER"."TB_AUTH_MENU"."MENU_ID" IS '메뉴ID';
   COMMENT ON TABLE "FINGER"."TB_AUTH_MENU"  IS '권한별메뉴';
--------------------------------------------------------
--  DDL for Table TB_BANK_CD
--------------------------------------------------------

  CREATE TABLE "FINGER"."TB_BANK_CD" 
   (	"BANK_CD" VARCHAR2(3 BYTE), 
	"BANK_NM" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "FINGER"."TB_BANK_CD"."BANK_CD" IS '은행코드';
   COMMENT ON COLUMN "FINGER"."TB_BANK_CD"."BANK_NM" IS '은행명';
   COMMENT ON TABLE "FINGER"."TB_BANK_CD"  IS '은행코드';
--------------------------------------------------------
--  DDL for Table TB_BELONG_INFO
--------------------------------------------------------

  CREATE TABLE "FINGER"."TB_BELONG_INFO" 
   (	"BELONG_ID" VARCHAR2(2 BYTE), 
	"BELONG_NM" VARCHAR2(100 BYTE), 
	"BELONG_PHONE_NUM1" VARCHAR2(4 BYTE), 
	"BELONG_PHONE_NUM2" VARCHAR2(4 BYTE), 
	"BELONG_PHONE_NUM3" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "FINGER"."TB_BELONG_INFO"."BELONG_ID" IS '소속ID';
   COMMENT ON COLUMN "FINGER"."TB_BELONG_INFO"."BELONG_NM" IS '소속명';
   COMMENT ON COLUMN "FINGER"."TB_BELONG_INFO"."BELONG_PHONE_NUM1" IS '소속전화번호1';
   COMMENT ON COLUMN "FINGER"."TB_BELONG_INFO"."BELONG_PHONE_NUM2" IS '소속전화번호2';
   COMMENT ON COLUMN "FINGER"."TB_BELONG_INFO"."BELONG_PHONE_NUM3" IS '소속전화번호3';
   COMMENT ON TABLE "FINGER"."TB_BELONG_INFO"  IS '소속정보';
--------------------------------------------------------
--  DDL for Table TB_MENU
--------------------------------------------------------

  CREATE TABLE "FINGER"."TB_MENU" 
   (	"MENU_ID" VARCHAR2(9 BYTE), 
	"MENU_NM" VARCHAR2(50 BYTE), 
	"UPPER_MENU_ID" VARCHAR2(9 BYTE), 
	"MENU_LVL" VARCHAR2(1 BYTE), 
	"DISP_SEQ" NUMBER(2,0), 
	"IND" VARCHAR2(1 BYTE), 
	"MENU_URL" VARCHAR2(300 BYTE), 
	"USE_YN" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "FINGER"."TB_MENU"."MENU_ID" IS '메뉴ID';
   COMMENT ON COLUMN "FINGER"."TB_MENU"."MENU_NM" IS '메뉴명';
   COMMENT ON COLUMN "FINGER"."TB_MENU"."UPPER_MENU_ID" IS '상위메뉴ID';
   COMMENT ON COLUMN "FINGER"."TB_MENU"."MENU_LVL" IS '메뉴레벨';
   COMMENT ON COLUMN "FINGER"."TB_MENU"."DISP_SEQ" IS '표시순서';
   COMMENT ON COLUMN "FINGER"."TB_MENU"."IND" IS '구분';
   COMMENT ON COLUMN "FINGER"."TB_MENU"."MENU_URL" IS '메뉴경로';
   COMMENT ON COLUMN "FINGER"."TB_MENU"."USE_YN" IS '사용여부';
   COMMENT ON TABLE "FINGER"."TB_MENU"  IS '메뉴';
--------------------------------------------------------
--  DDL for Table TB_MSG_SEND_HIST
--------------------------------------------------------

  CREATE TABLE "FINGER"."TB_MSG_SEND_HIST" 
   (	"MSG_SEND_HIST_ID" VARCHAR2(13 BYTE), 
	"MSG_SEND_MONTH" VARCHAR2(6 BYTE), 
	"MSG_SEND_DTTM" VARCHAR2(14 BYTE), 
	"SMS_LMS_IND" VARCHAR2(1 BYTE), 
	"USE_AMT" NUMBER(8,0), 
	"MSG_CONTENT" VARCHAR2(2000 BYTE), 
	"RECV_NUM" VARCHAR2(14 BYTE), 
	"SEND_NUM" VARCHAR2(14 BYTE), 
	"SUCCESS_YN" VARCHAR2(1 BYTE), 
	"REG_USER_ID" VARCHAR2(12 BYTE), 
	"MSG_ID" NUMBER(14,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "FINGER"."TB_MSG_SEND_HIST"."MSG_SEND_HIST_ID" IS '문자전송이력ID';
   COMMENT ON COLUMN "FINGER"."TB_MSG_SEND_HIST"."MSG_SEND_MONTH" IS '발송월';
   COMMENT ON COLUMN "FINGER"."TB_MSG_SEND_HIST"."MSG_SEND_DTTM" IS '발송일시';
   COMMENT ON COLUMN "FINGER"."TB_MSG_SEND_HIST"."SMS_LMS_IND" IS '장단문구분';
   COMMENT ON COLUMN "FINGER"."TB_MSG_SEND_HIST"."USE_AMT" IS '사용요금';
   COMMENT ON COLUMN "FINGER"."TB_MSG_SEND_HIST"."MSG_CONTENT" IS '문자내용';
   COMMENT ON COLUMN "FINGER"."TB_MSG_SEND_HIST"."RECV_NUM" IS '수신번호';
   COMMENT ON COLUMN "FINGER"."TB_MSG_SEND_HIST"."SEND_NUM" IS '발신번호';
   COMMENT ON COLUMN "FINGER"."TB_MSG_SEND_HIST"."SUCCESS_YN" IS '성공여부';
   COMMENT ON COLUMN "FINGER"."TB_MSG_SEND_HIST"."REG_USER_ID" IS '등록자ID';
   COMMENT ON TABLE "FINGER"."TB_MSG_SEND_HIST"  IS '문자전송이력';
--------------------------------------------------------
--  DDL for Table TB_PAYER_INFO
--------------------------------------------------------

  CREATE TABLE "FINGER"."TB_PAYER_INFO" 
   (	"CAR_NUM" VARCHAR2(30 BYTE), 
	"CAR_OWNER_NM" VARCHAR2(50 BYTE), 
	"PAY_DUE_DT" VARCHAR2(10 BYTE), 
	"CAR_OWNER_ADDR" VARCHAR2(300 BYTE), 
	"GIRO_NUM" VARCHAR2(9 BYTE), 
	"CUST_INQ_NUM" VARCHAR2(22 BYTE), 
	"TOT_AMT" NUMBER(8,0), 
	"NOTI_AMT_CD" VARCHAR2(9 BYTE), 
	"GIRO_CD" VARCHAR2(4 BYTE), 
	"OCCUR_DTTM1" VARCHAR2(19 BYTE), 
	"OCCUR_REASON1" VARCHAR2(100 BYTE), 
	"PASS_PLACE1" VARCHAR2(100 BYTE), 
	"PASS_AMT1" NUMBER(8,0), 
	"OCCUR_DTTM2" VARCHAR2(19 BYTE), 
	"OCCUR_REASON2" VARCHAR2(100 BYTE), 
	"PASS_PLACE2" VARCHAR2(100 BYTE), 
	"PASS_AMT2" NUMBER(8,0), 
	"OCCUR_DTTM3" VARCHAR2(19 BYTE), 
	"OCCUR_REASON3" VARCHAR2(100 BYTE), 
	"PASS_PLACE3" VARCHAR2(100 BYTE), 
	"PASS_AMT3" NUMBER(8,0), 
	"OCCUR_DTTM4" VARCHAR2(19 BYTE), 
	"OCCUR_REASON4" VARCHAR2(100 BYTE), 
	"PASS_PLACE4" VARCHAR2(100 BYTE), 
	"PASS_AMT4" NUMBER(8,0), 
	"OCCUR_DTTM5" VARCHAR2(19 BYTE), 
	"OCCUR_REASON5" VARCHAR2(100 BYTE), 
	"PASS_PLACE5" VARCHAR2(100 BYTE), 
	"PASS_AMT5" NUMBER(8,0), 
	"OCCUR_DTTM6" VARCHAR2(19 BYTE), 
	"OCCUR_REASON6" VARCHAR2(100 BYTE), 
	"PASS_PLACE6" VARCHAR2(100 BYTE), 
	"PASS_AMT6" NUMBER(8,0), 
	"OCCUR_DTTM7" VARCHAR2(19 BYTE), 
	"OCCUR_REASON7" VARCHAR2(100 BYTE), 
	"PASS_PLACE7" VARCHAR2(100 BYTE), 
	"PASS_AMT7" NUMBER(8,0), 
	"OCCUR_DTTM8" VARCHAR2(19 BYTE), 
	"OCCUR_REASON8" VARCHAR2(100 BYTE), 
	"PASS_PLACE8" VARCHAR2(100 BYTE), 
	"PASS_AMT8" NUMBER(8,0), 
	"OCCUR_DTTM9" VARCHAR2(19 BYTE), 
	"OCCUR_REASON9" VARCHAR2(100 BYTE), 
	"PASS_PLACE9" VARCHAR2(100 BYTE), 
	"PASS_AMT9" NUMBER(8,0), 
	"OCCUR_DTTM10" VARCHAR2(19 BYTE), 
	"OCCUR_REASON10" VARCHAR2(100 BYTE), 
	"PASS_PLACE10" VARCHAR2(100 BYTE), 
	"PASS_AMT10" NUMBER(8,0), 
	"RUN_DT" VARCHAR2(30 BYTE), 
	"PAY_YN" VARCHAR2(1 BYTE), 
	"PAYER_INFO_ID" VARCHAR2(11 BYTE), 
	"VIRTUAL_ACNT_NUM" VARCHAR2(14 BYTE), 
	"TRNO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."CAR_NUM" IS '차량번호';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."CAR_OWNER_NM" IS '차량주';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."PAY_DUE_DT" IS '납부기한';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."CAR_OWNER_ADDR" IS '차량주주소';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."GIRO_NUM" IS '지로번호';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."CUST_INQ_NUM" IS '고객조회번호';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."TOT_AMT" IS '총금액';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."NOTI_AMT_CD" IS '고지금코드';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."GIRO_CD" IS '지로코드';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."OCCUR_DTTM1" IS '발생일시1';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."OCCUR_REASON1" IS '발생원인1';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."PASS_PLACE1" IS '통행장소1';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."PASS_AMT1" IS '통행요금1';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."OCCUR_DTTM2" IS '발생일시2';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."OCCUR_REASON2" IS '발생원인2';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."PASS_PLACE2" IS '통행장소2';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."PASS_AMT2" IS '통행요금2';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."OCCUR_DTTM3" IS '발생일시3';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."OCCUR_REASON3" IS '발생원인3';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."PASS_PLACE3" IS '통행장소3';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."PASS_AMT3" IS '통행요금3';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."OCCUR_DTTM4" IS '발생일시4';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."OCCUR_REASON4" IS '발생원인4';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."PASS_PLACE4" IS '통행장소4';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."PASS_AMT4" IS '통행요금4';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."OCCUR_DTTM5" IS '발생일시5';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."OCCUR_REASON5" IS '발생원인5';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."PASS_PLACE5" IS '통행장소5';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."PASS_AMT5" IS '통행요금5';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."OCCUR_DTTM6" IS '발생일시6';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."OCCUR_REASON6" IS '발생원인6';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."PASS_PLACE6" IS '통행장소6';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."PASS_AMT6" IS '통행요금6';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."OCCUR_DTTM7" IS '발생일시7';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."OCCUR_REASON7" IS '발생원인7';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."PASS_PLACE7" IS '통행장소7';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."PASS_AMT7" IS '통행요금7';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."OCCUR_DTTM8" IS '발생일시8';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."OCCUR_REASON8" IS '발생원인8';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."PASS_PLACE8" IS '통행장소8';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."PASS_AMT8" IS '통행요금8';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."OCCUR_DTTM9" IS '발생일시9';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."OCCUR_REASON9" IS '발생원인9';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."PASS_PLACE9" IS '통행장소9';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."PASS_AMT9" IS '통행요금9';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."OCCUR_DTTM10" IS '발생일시10';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."OCCUR_REASON10" IS '발생원인10';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."PASS_PLACE10" IS '통행장소10';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."PASS_AMT10" IS '통행요금10';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."RUN_DT" IS '운행기간';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."PAY_YN" IS '납부여부';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."PAYER_INFO_ID" IS '납부자정보ID';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."VIRTUAL_ACNT_NUM" IS '가상계좌번호';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO"."TRNO" IS '거래번호';
   COMMENT ON TABLE "FINGER"."TB_PAYER_INFO"  IS '납부자정보';
--------------------------------------------------------
--  DDL for Table TB_PAYER_INFO_BAK
--------------------------------------------------------

  CREATE TABLE "FINGER"."TB_PAYER_INFO_BAK" 
   (	"CAR_NUM" VARCHAR2(30 BYTE), 
	"CAR_OWNER_NM" VARCHAR2(50 BYTE), 
	"PAY_DUE_DT" VARCHAR2(10 BYTE), 
	"CAR_OWNER_ADDR" VARCHAR2(300 BYTE), 
	"GIRO_NUM" VARCHAR2(9 BYTE), 
	"CUST_INQ_NUM" VARCHAR2(22 BYTE), 
	"TOT_AMT" NUMBER(8,0), 
	"NOTI_AMT_CD" VARCHAR2(8 BYTE), 
	"GIRO_CD" VARCHAR2(4 BYTE), 
	"OCCUR_DTTM1" VARCHAR2(19 BYTE), 
	"OCCUR_REASON1" VARCHAR2(100 BYTE), 
	"PASS_PLACE1" VARCHAR2(100 BYTE), 
	"PASS_AMT1" NUMBER(8,0), 
	"OCCUR_DTTM2" VARCHAR2(19 BYTE), 
	"OCCUR_REASON2" VARCHAR2(100 BYTE), 
	"PASS_PLACE2" VARCHAR2(100 BYTE), 
	"PASS_AMT2" NUMBER(8,0), 
	"OCCUR_DTTM3" VARCHAR2(19 BYTE), 
	"OCCUR_REASON3" VARCHAR2(100 BYTE), 
	"PASS_PLACE3" VARCHAR2(100 BYTE), 
	"PASS_AMT3" NUMBER(8,0), 
	"OCCUR_DTTM4" VARCHAR2(19 BYTE), 
	"OCCUR_REASON4" VARCHAR2(100 BYTE), 
	"PASS_PLACE4" VARCHAR2(100 BYTE), 
	"PASS_AMT4" NUMBER(8,0), 
	"OCCUR_DTTM5" VARCHAR2(19 BYTE), 
	"OCCUR_REASON5" VARCHAR2(100 BYTE), 
	"PASS_PLACE5" VARCHAR2(100 BYTE), 
	"PASS_AMT5" NUMBER(8,0), 
	"OCCUR_DTTM6" VARCHAR2(19 BYTE), 
	"OCCUR_REASON6" VARCHAR2(100 BYTE), 
	"PASS_PLACE6" VARCHAR2(100 BYTE), 
	"PASS_AMT6" NUMBER(8,0), 
	"OCCUR_DTTM7" VARCHAR2(19 BYTE), 
	"OCCUR_REASON7" VARCHAR2(100 BYTE), 
	"PASS_PLACE7" VARCHAR2(100 BYTE), 
	"PASS_AMT7" NUMBER(8,0), 
	"OCCUR_DTTM8" VARCHAR2(19 BYTE), 
	"OCCUR_REASON8" VARCHAR2(100 BYTE), 
	"PASS_PLACE8" VARCHAR2(100 BYTE), 
	"PASS_AMT8" NUMBER(8,0), 
	"OCCUR_DTTM9" VARCHAR2(19 BYTE), 
	"OCCUR_REASON9" VARCHAR2(100 BYTE), 
	"PASS_PLACE9" VARCHAR2(100 BYTE), 
	"PASS_AMT9" NUMBER(8,0), 
	"OCCUR_DTTM10" VARCHAR2(19 BYTE), 
	"OCCUR_REASON10" VARCHAR2(100 BYTE), 
	"PASS_PLACE10" VARCHAR2(100 BYTE), 
	"PASS_AMT10" NUMBER(8,0), 
	"RUN_DT" VARCHAR2(30 BYTE), 
	"PAY_YN" VARCHAR2(1 BYTE), 
	"PAYER_INFO_ID" VARCHAR2(11 BYTE), 
	"VIRTUAL_ACNT_NUM" VARCHAR2(14 BYTE), 
	"TRNO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TB_PAYER_INFO_MASTER
--------------------------------------------------------

  CREATE TABLE "FINGER"."TB_PAYER_INFO_MASTER" 
   (	"PAYER_INFO_ID" VARCHAR2(11 BYTE), 
	"REG_DTTM" VARCHAR2(14 BYTE), 
	"REG_MONTH" VARCHAR2(6 BYTE), 
	"CLAIM_CNT" NUMBER(5,0), 
	"CLAIM_AMT_SUM" NUMBER(8,0), 
	"STATUS" VARCHAR2(1 BYTE), 
	"REG_USER_ID" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO_MASTER"."PAYER_INFO_ID" IS '납부자정보ID';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO_MASTER"."REG_DTTM" IS '등록일시';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO_MASTER"."REG_MONTH" IS '등록월';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO_MASTER"."CLAIM_CNT" IS '청구건수';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO_MASTER"."CLAIM_AMT_SUM" IS '청구금액합계';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO_MASTER"."STATUS" IS '상태';
   COMMENT ON COLUMN "FINGER"."TB_PAYER_INFO_MASTER"."REG_USER_ID" IS '등록자ID';
   COMMENT ON TABLE "FINGER"."TB_PAYER_INFO_MASTER"  IS '납부자정보마스터';
--------------------------------------------------------
--  DDL for Table TB_PAYER_INFO_MASTER_BAK
--------------------------------------------------------

  CREATE TABLE "FINGER"."TB_PAYER_INFO_MASTER_BAK" 
   (	"PAYER_INFO_ID" VARCHAR2(11 BYTE), 
	"REG_DTTM" VARCHAR2(14 BYTE), 
	"REG_MONTH" VARCHAR2(6 BYTE), 
	"CLAIM_CNT" NUMBER(5,0), 
	"CLAIM_AMT_SUM" NUMBER(8,0), 
	"STATUS" VARCHAR2(1 BYTE), 
	"REG_USER_ID" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TB_RECEIPT_LAST_DOWN_DT
--------------------------------------------------------

  CREATE TABLE "FINGER"."TB_RECEIPT_LAST_DOWN_DT" 
   (	"PROC_DTTM" VARCHAR2(14 BYTE), 
	"INQ_START_DT" VARCHAR2(8 BYTE), 
	"INQ_END_DT" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "FINGER"."TB_RECEIPT_LAST_DOWN_DT"."PROC_DTTM" IS '처리일시';
   COMMENT ON COLUMN "FINGER"."TB_RECEIPT_LAST_DOWN_DT"."INQ_START_DT" IS '조회시작일자';
   COMMENT ON COLUMN "FINGER"."TB_RECEIPT_LAST_DOWN_DT"."INQ_END_DT" IS '조회종료일자';
   COMMENT ON TABLE "FINGER"."TB_RECEIPT_LAST_DOWN_DT"  IS '수납목록최종다운로드일자';
--------------------------------------------------------
--  DDL for Table TB_USER
--------------------------------------------------------

  CREATE TABLE "FINGER"."TB_USER" 
   (	"USER_ID" VARCHAR2(12 BYTE), 
	"USER_NM" VARCHAR2(50 BYTE), 
	"USER_PSWD" VARCHAR2(12 BYTE), 
	"INIT_PSWD" VARCHAR2(12 BYTE), 
	"POSITION" VARCHAR2(100 BYTE), 
	"BELONG_ID" VARCHAR2(2 BYTE), 
	"DEPT" VARCHAR2(100 BYTE), 
	"PHONE_NUM1" VARCHAR2(3 BYTE), 
	"PHONE_NUM2" VARCHAR2(4 BYTE), 
	"PHONE_NUM3" VARCHAR2(4 BYTE), 
	"MOBILE_NUM1" VARCHAR2(3 BYTE), 
	"MOBILE_NUM2" VARCHAR2(4 BYTE), 
	"MOBILE_NUM3" VARCHAR2(4 BYTE), 
	"EMAIL_ADDR" VARCHAR2(40 BYTE), 
	"MEMO" VARCHAR2(1000 BYTE), 
	"REG_DT" VARCHAR2(8 BYTE), 
	"AUTH_GRP_CD" VARCHAR2(1 BYTE), 
	"USE_YN" VARCHAR2(1 BYTE), 
	"LAST_CONN_DTTM" VARCHAR2(14 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "FINGER"."TB_USER"."USER_ID" IS '사용자ID';
   COMMENT ON COLUMN "FINGER"."TB_USER"."USER_NM" IS '성명';
   COMMENT ON COLUMN "FINGER"."TB_USER"."USER_PSWD" IS '비밀번호';
   COMMENT ON COLUMN "FINGER"."TB_USER"."INIT_PSWD" IS '초기화비밀번호';
   COMMENT ON COLUMN "FINGER"."TB_USER"."POSITION" IS '직급';
   COMMENT ON COLUMN "FINGER"."TB_USER"."BELONG_ID" IS '소속ID';
   COMMENT ON COLUMN "FINGER"."TB_USER"."DEPT" IS '부서';
   COMMENT ON COLUMN "FINGER"."TB_USER"."PHONE_NUM1" IS '전화번호1';
   COMMENT ON COLUMN "FINGER"."TB_USER"."PHONE_NUM2" IS '전화번호2';
   COMMENT ON COLUMN "FINGER"."TB_USER"."PHONE_NUM3" IS '전화번호3';
   COMMENT ON COLUMN "FINGER"."TB_USER"."MOBILE_NUM1" IS '휴대폰1';
   COMMENT ON COLUMN "FINGER"."TB_USER"."MOBILE_NUM2" IS '휴대폰2';
   COMMENT ON COLUMN "FINGER"."TB_USER"."MOBILE_NUM3" IS '휴대폰3';
   COMMENT ON COLUMN "FINGER"."TB_USER"."EMAIL_ADDR" IS '이메일주소';
   COMMENT ON COLUMN "FINGER"."TB_USER"."MEMO" IS '메모';
   COMMENT ON COLUMN "FINGER"."TB_USER"."REG_DT" IS '등록일';
   COMMENT ON COLUMN "FINGER"."TB_USER"."AUTH_GRP_CD" IS '권한그룹코드';
   COMMENT ON COLUMN "FINGER"."TB_USER"."USE_YN" IS '사용여부';
   COMMENT ON COLUMN "FINGER"."TB_USER"."LAST_CONN_DTTM" IS '마지막접속일시';
   COMMENT ON TABLE "FINGER"."TB_USER"  IS '사용자';
--------------------------------------------------------
--  DDL for Table TB_VIRTUAL_ACNT
--------------------------------------------------------

  CREATE TABLE "FINGER"."TB_VIRTUAL_ACNT" 
   (	"VIRTUAL_ACNT_NUM" VARCHAR2(14 BYTE), 
	"PAY_DUE_DT" VARCHAR2(8 BYTE), 
	"USE_YN" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "FINGER"."TB_VIRTUAL_ACNT"."VIRTUAL_ACNT_NUM" IS '가상계좌번호';
   COMMENT ON COLUMN "FINGER"."TB_VIRTUAL_ACNT"."PAY_DUE_DT" IS '납부기한';
   COMMENT ON COLUMN "FINGER"."TB_VIRTUAL_ACNT"."USE_YN" IS '사용여부';
   COMMENT ON TABLE "FINGER"."TB_VIRTUAL_ACNT"  IS '가상계좌';
--------------------------------------------------------
--  DDL for Index PK_TB_MSG_SEND_HIST
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINGER"."PK_TB_MSG_SEND_HIST" ON "FINGER"."TB_MSG_SEND_HIST" ("MSG_SEND_HIST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TB_BELONG_INFO
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINGER"."PK_TB_BELONG_INFO" ON "FINGER"."TB_BELONG_INFO" ("BELONG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DRC$TB_PAYER_INFO_INDEX3$R
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINGER"."DRC$TB_PAYER_INFO_INDEX3$R" ON "FINGER"."DR$TB_PAYER_INFO_INDEX3$R" ("ROW_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AEGISTRANSMSG_INDEX1
--------------------------------------------------------

  CREATE INDEX "FINGER"."AEGISTRANSMSG_INDEX1" ON "FINGER"."AEGISTRANSMSG" ("TRANST", "TRNO", "PAYDAY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TB_PAYER_INFO1
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINGER"."PK_TB_PAYER_INFO1" ON "FINGER"."TB_PAYER_INFO" ("CUST_INQ_NUM", "OCCUR_DTTM1", "PAY_DUE_DT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TB_MENU
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINGER"."PK_TB_MENU" ON "FINGER"."TB_MENU" ("MENU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_PAYER_INFO_INDEX3
--------------------------------------------------------

  CREATE INDEX "FINGER"."TB_PAYER_INFO_INDEX3" ON "FINGER"."TB_PAYER_INFO" ("CAR_NUM") 
   INDEXTYPE IS "CTXSYS"."CONTEXT" ;
--------------------------------------------------------
--  DDL for Index PK_TB_AUTH_GRP
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINGER"."PK_TB_AUTH_GRP" ON "FINGER"."TB_AUTH_GRP" ("AUTH_GRP_CD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DR$TB_PAYER_INFO_INDEX3$X
--------------------------------------------------------

  CREATE INDEX "FINGER"."DR$TB_PAYER_INFO_INDEX3$X" ON "FINGER"."DR$TB_PAYER_INFO_INDEX3$I" ("TOKEN_TEXT", "TOKEN_TYPE", "TOKEN_FIRST", "TOKEN_LAST", "TOKEN_COUNT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS COMPRESS 2 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_AEGISTRANSMSG
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINGER"."PK_AEGISTRANSMSG" ON "FINGER"."AEGISTRANSMSG" ("REGSEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_PAYER_INFO_INDEX4
--------------------------------------------------------

  CREATE INDEX "FINGER"."TB_PAYER_INFO_INDEX4" ON "FINGER"."TB_PAYER_INFO" ("PAYER_INFO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_PAYER_INFO_INDEX5
--------------------------------------------------------

  CREATE INDEX "FINGER"."TB_PAYER_INFO_INDEX5" ON "FINGER"."TB_PAYER_INFO" ("PAYER_INFO_ID", "TRNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TB_PAYER_INFO_MASTER
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINGER"."PK_TB_PAYER_INFO_MASTER" ON "FINGER"."TB_PAYER_INFO_MASTER" ("PAYER_INFO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TB_VIRTUAL_ACNT
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINGER"."PK_TB_VIRTUAL_ACNT" ON "FINGER"."TB_VIRTUAL_ACNT" ("VIRTUAL_ACNT_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TB_USER
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINGER"."PK_TB_USER" ON "FINGER"."TB_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TB_AUTH_MENU
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINGER"."PK_TB_AUTH_MENU" ON "FINGER"."TB_AUTH_MENU" ("AUTH_GRP_CD", "MENU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_PAYER_INFO_MASTER_INDEX1
--------------------------------------------------------

  CREATE INDEX "FINGER"."TB_PAYER_INFO_MASTER_INDEX1" ON "FINGER"."TB_PAYER_INFO_MASTER" ("REG_MONTH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_PAYER_INFO_INDEX2
--------------------------------------------------------

  CREATE INDEX "FINGER"."TB_PAYER_INFO_INDEX2" ON "FINGER"."TB_PAYER_INFO" ("TRNO", "PAYER_INFO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AEGISTRANSMSG_INDEX3
--------------------------------------------------------

  CREATE INDEX "FINGER"."AEGISTRANSMSG_INDEX3" ON "FINGER"."AEGISTRANSMSG" ("TRNO", "PAYDAY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_PAYER_INFO_INDEX1
--------------------------------------------------------

  CREATE INDEX "FINGER"."TB_PAYER_INFO_INDEX1" ON "FINGER"."TB_PAYER_INFO" ("PAY_DUE_DT" DESC, "CUST_INQ_NUM", "OCCUR_DTTM1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TB_BANK_CD
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINGER"."PK_TB_BANK_CD" ON "FINGER"."TB_BANK_CD" ("BANK_CD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AEGISTRANSMSG_INDEX2
--------------------------------------------------------

  CREATE INDEX "FINGER"."AEGISTRANSMSG_INDEX2" ON "FINGER"."AEGISTRANSMSG" ("TRANST", "TRNDAY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TB_MSG_SEND_HIST
--------------------------------------------------------

  ALTER TABLE "FINGER"."TB_MSG_SEND_HIST" MODIFY ("MSG_SEND_HIST_ID" NOT NULL ENABLE);
  ALTER TABLE "FINGER"."TB_MSG_SEND_HIST" ADD CONSTRAINT "PK_TB_MSG_SEND_HIST" PRIMARY KEY ("MSG_SEND_HIST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_USER
--------------------------------------------------------

  ALTER TABLE "FINGER"."TB_USER" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "FINGER"."TB_USER" MODIFY ("USER_NM" NOT NULL ENABLE);
  ALTER TABLE "FINGER"."TB_USER" MODIFY ("AUTH_GRP_CD" NOT NULL ENABLE);
  ALTER TABLE "FINGER"."TB_USER" ADD CONSTRAINT "PK_TB_USER" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_RECEIPT_LAST_DOWN_DT
--------------------------------------------------------

  ALTER TABLE "FINGER"."TB_RECEIPT_LAST_DOWN_DT" MODIFY ("PROC_DTTM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DR$TB_PAYER_INFO_INDEX3$N
--------------------------------------------------------

  ALTER TABLE "FINGER"."DR$TB_PAYER_INFO_INDEX3$N" ADD PRIMARY KEY ("NLT_DOCID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FINGER"."DR$TB_PAYER_INFO_INDEX3$N" MODIFY ("NLT_MARK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_PAYER_INFO_MASTER_BAK
--------------------------------------------------------

  ALTER TABLE "FINGER"."TB_PAYER_INFO_MASTER_BAK" MODIFY ("PAYER_INFO_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DR$TB_PAYER_INFO_INDEX3$I
--------------------------------------------------------

  ALTER TABLE "FINGER"."DR$TB_PAYER_INFO_INDEX3$I" MODIFY ("TOKEN_COUNT" NOT NULL ENABLE);
  ALTER TABLE "FINGER"."DR$TB_PAYER_INFO_INDEX3$I" MODIFY ("TOKEN_LAST" NOT NULL ENABLE);
  ALTER TABLE "FINGER"."DR$TB_PAYER_INFO_INDEX3$I" MODIFY ("TOKEN_FIRST" NOT NULL ENABLE);
  ALTER TABLE "FINGER"."DR$TB_PAYER_INFO_INDEX3$I" MODIFY ("TOKEN_TYPE" NOT NULL ENABLE);
  ALTER TABLE "FINGER"."DR$TB_PAYER_INFO_INDEX3$I" MODIFY ("TOKEN_TEXT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_BELONG_INFO
--------------------------------------------------------

  ALTER TABLE "FINGER"."TB_BELONG_INFO" MODIFY ("BELONG_ID" NOT NULL ENABLE);
  ALTER TABLE "FINGER"."TB_BELONG_INFO" ADD CONSTRAINT "PK_TB_BELONG_INFO" PRIMARY KEY ("BELONG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AEGISTRANSMSG
--------------------------------------------------------

  ALTER TABLE "FINGER"."AEGISTRANSMSG" MODIFY ("REGSEQ" NOT NULL ENABLE);
  ALTER TABLE "FINGER"."AEGISTRANSMSG" ADD CONSTRAINT "PK_AEGISTRANSMSG" PRIMARY KEY ("REGSEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_BANK_CD
--------------------------------------------------------

  ALTER TABLE "FINGER"."TB_BANK_CD" MODIFY ("BANK_CD" NOT NULL ENABLE);
  ALTER TABLE "FINGER"."TB_BANK_CD" ADD CONSTRAINT "PK_TB_BANK_CD" PRIMARY KEY ("BANK_CD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_VIRTUAL_ACNT
--------------------------------------------------------

  ALTER TABLE "FINGER"."TB_VIRTUAL_ACNT" MODIFY ("VIRTUAL_ACNT_NUM" NOT NULL ENABLE);
  ALTER TABLE "FINGER"."TB_VIRTUAL_ACNT" ADD CONSTRAINT "PK_TB_VIRTUAL_ACNT" PRIMARY KEY ("VIRTUAL_ACNT_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DR$TB_PAYER_INFO_INDEX3$R
--------------------------------------------------------

  ALTER TABLE "FINGER"."DR$TB_PAYER_INFO_INDEX3$R" ADD CONSTRAINT "DRC$TB_PAYER_INFO_INDEX3$R" PRIMARY KEY ("ROW_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_PAYER_INFO_MASTER
--------------------------------------------------------

  ALTER TABLE "FINGER"."TB_PAYER_INFO_MASTER" MODIFY ("PAYER_INFO_ID" NOT NULL ENABLE);
  ALTER TABLE "FINGER"."TB_PAYER_INFO_MASTER" ADD CONSTRAINT "PK_TB_PAYER_INFO_MASTER" PRIMARY KEY ("PAYER_INFO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_AUTH_MENU
--------------------------------------------------------

  ALTER TABLE "FINGER"."TB_AUTH_MENU" MODIFY ("AUTH_GRP_CD" NOT NULL ENABLE);
  ALTER TABLE "FINGER"."TB_AUTH_MENU" MODIFY ("MENU_ID" NOT NULL ENABLE);
  ALTER TABLE "FINGER"."TB_AUTH_MENU" ADD CONSTRAINT "PK_TB_AUTH_MENU" PRIMARY KEY ("AUTH_GRP_CD", "MENU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_PAYER_INFO_BAK
--------------------------------------------------------

  ALTER TABLE "FINGER"."TB_PAYER_INFO_BAK" MODIFY ("PAYER_INFO_ID" NOT NULL ENABLE);
  ALTER TABLE "FINGER"."TB_PAYER_INFO_BAK" MODIFY ("OCCUR_DTTM1" NOT NULL ENABLE);
  ALTER TABLE "FINGER"."TB_PAYER_INFO_BAK" MODIFY ("CUST_INQ_NUM" NOT NULL ENABLE);
  ALTER TABLE "FINGER"."TB_PAYER_INFO_BAK" MODIFY ("PAY_DUE_DT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_PAYER_INFO
--------------------------------------------------------

  ALTER TABLE "FINGER"."TB_PAYER_INFO" ADD CONSTRAINT "PK_TB_PAYER_INFO" PRIMARY KEY ("CUST_INQ_NUM", "OCCUR_DTTM1", "PAY_DUE_DT")
  USING INDEX (CREATE UNIQUE INDEX "FINGER"."PK_TB_PAYER_INFO1" ON "FINGER"."TB_PAYER_INFO" ("CUST_INQ_NUM", "OCCUR_DTTM1", "PAY_DUE_DT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "FINGER"."TB_PAYER_INFO" MODIFY ("CUST_INQ_NUM" NOT NULL ENABLE);
  ALTER TABLE "FINGER"."TB_PAYER_INFO" MODIFY ("OCCUR_DTTM1" NOT NULL ENABLE);
  ALTER TABLE "FINGER"."TB_PAYER_INFO" MODIFY ("PAYER_INFO_ID" NOT NULL ENABLE);
  ALTER TABLE "FINGER"."TB_PAYER_INFO" MODIFY ("PAY_DUE_DT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_AUTH_GRP
--------------------------------------------------------

  ALTER TABLE "FINGER"."TB_AUTH_GRP" MODIFY ("AUTH_GRP_CD" NOT NULL ENABLE);
  ALTER TABLE "FINGER"."TB_AUTH_GRP" ADD CONSTRAINT "PK_TB_AUTH_GRP" PRIMARY KEY ("AUTH_GRP_CD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DR$TB_PAYER_INFO_INDEX3$K
--------------------------------------------------------

  ALTER TABLE "FINGER"."DR$TB_PAYER_INFO_INDEX3$K" ADD PRIMARY KEY ("TEXTKEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_MENU
--------------------------------------------------------

  ALTER TABLE "FINGER"."TB_MENU" MODIFY ("MENU_ID" NOT NULL ENABLE);
  ALTER TABLE "FINGER"."TB_MENU" ADD CONSTRAINT "PK_TB_MENU" PRIMARY KEY ("MENU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
