package com.finger.shinhandamoa.data.table.model;

import java.io.Serializable;

public class ChaWithBLOBs extends Cha implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCHALIST.CHRHP
     *
     * @mbg.generated
     */
    private String chrhp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCHALIST.FEEACCNO
     *
     * @mbg.generated
     */
    private String feeaccno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCHALIST.FEEOFFNO
     *
     * @mbg.generated
     */
    private String feeoffno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCHALIST.CONHP
     *
     * @mbg.generated
     */
    private String conhp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCHALIST.SMS_SEND_TEL
     *
     * @mbg.generated
     */
    private String smsSendTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCHALIST.USRPWD
     *
     * @mbg.generated
     */
    private String usrpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table XCHALIST
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCHALIST.CHRHP
     *
     * @return the value of XCHALIST.CHRHP
     *
     * @mbg.generated
     */
    public String getChrhp() {
        return chrhp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCHALIST.CHRHP
     *
     * @param chrhp the value for XCHALIST.CHRHP
     *
     * @mbg.generated
     */
    public void setChrhp(String chrhp) {
        this.chrhp = chrhp == null ? null : chrhp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCHALIST.FEEACCNO
     *
     * @return the value of XCHALIST.FEEACCNO
     *
     * @mbg.generated
     */
    public String getFeeaccno() {
        return feeaccno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCHALIST.FEEACCNO
     *
     * @param feeaccno the value for XCHALIST.FEEACCNO
     *
     * @mbg.generated
     */
    public void setFeeaccno(String feeaccno) {
        this.feeaccno = feeaccno == null ? null : feeaccno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCHALIST.FEEOFFNO
     *
     * @return the value of XCHALIST.FEEOFFNO
     *
     * @mbg.generated
     */
    public String getFeeoffno() {
        return feeoffno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCHALIST.FEEOFFNO
     *
     * @param feeoffno the value for XCHALIST.FEEOFFNO
     *
     * @mbg.generated
     */
    public void setFeeoffno(String feeoffno) {
        this.feeoffno = feeoffno == null ? null : feeoffno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCHALIST.CONHP
     *
     * @return the value of XCHALIST.CONHP
     *
     * @mbg.generated
     */
    public String getConhp() {
        return conhp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCHALIST.CONHP
     *
     * @param conhp the value for XCHALIST.CONHP
     *
     * @mbg.generated
     */
    public void setConhp(String conhp) {
        this.conhp = conhp == null ? null : conhp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCHALIST.SMS_SEND_TEL
     *
     * @return the value of XCHALIST.SMS_SEND_TEL
     *
     * @mbg.generated
     */
    public String getSmsSendTel() {
        return smsSendTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCHALIST.SMS_SEND_TEL
     *
     * @param smsSendTel the value for XCHALIST.SMS_SEND_TEL
     *
     * @mbg.generated
     */
    public void setSmsSendTel(String smsSendTel) {
        this.smsSendTel = smsSendTel == null ? null : smsSendTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCHALIST.USRPWD
     *
     * @return the value of XCHALIST.USRPWD
     *
     * @mbg.generated
     */
    public String getUsrpwd() {
        return usrpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCHALIST.USRPWD
     *
     * @param usrpwd the value for XCHALIST.USRPWD
     *
     * @mbg.generated
     */
    public void setUsrpwd(String usrpwd) {
        this.usrpwd = usrpwd == null ? null : usrpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XCHALIST
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ChaWithBLOBs other = (ChaWithBLOBs) that;
        return (this.getChacd() == null ? other.getChacd() == null : this.getChacd().equals(other.getChacd()))
            && (this.getAgtcd() == null ? other.getAgtcd() == null : this.getAgtcd().equals(other.getAgtcd()))
            && (this.getChaname() == null ? other.getChaname() == null : this.getChaname().equals(other.getChaname()))
            && (this.getOwner() == null ? other.getOwner() == null : this.getOwner().equals(other.getOwner()))
            && (this.getOwnertel() == null ? other.getOwnertel() == null : this.getOwnertel().equals(other.getOwnertel()))
            && (this.getChaoffno() == null ? other.getChaoffno() == null : this.getChaoffno().equals(other.getChaoffno()))
            && (this.getChastatus() == null ? other.getChastatus() == null : this.getChastatus().equals(other.getChastatus()))
            && (this.getChatype() == null ? other.getChatype() == null : this.getChatype().equals(other.getChatype()))
            && (this.getChaaddress1() == null ? other.getChaaddress1() == null : this.getChaaddress1().equals(other.getChaaddress1()))
            && (this.getChaaddress2() == null ? other.getChaaddress2() == null : this.getChaaddress2().equals(other.getChaaddress2()))
            && (this.getChazipcode() == null ? other.getChazipcode() == null : this.getChazipcode().equals(other.getChazipcode()))
            && (this.getChrname() == null ? other.getChrname() == null : this.getChrname().equals(other.getChrname()))
            && (this.getChrtelno() == null ? other.getChrtelno() == null : this.getChrtelno().equals(other.getChrtelno()))
            && (this.getChrmail() == null ? other.getChrmail() == null : this.getChrmail().equals(other.getChrmail()))
            && (this.getFeeaccname() == null ? other.getFeeaccname() == null : this.getFeeaccname().equals(other.getFeeaccname()))
            && (this.getAccnocnt() == null ? other.getAccnocnt() == null : this.getAccnocnt().equals(other.getAccnocnt()))
            && (this.getConname() == null ? other.getConname() == null : this.getConname().equals(other.getConname()))
            && (this.getContelno() == null ? other.getContelno() == null : this.getContelno().equals(other.getContelno()))
            && (this.getAdjaccyn() == null ? other.getAdjaccyn() == null : this.getAdjaccyn().equals(other.getAdjaccyn()))
            && (this.getRcpreqyn() == null ? other.getRcpreqyn() == null : this.getRcpreqyn().equals(other.getRcpreqyn()))
            && (this.getRcpreqty() == null ? other.getRcpreqty() == null : this.getRcpreqty().equals(other.getRcpreqty()))
            && (this.getRcpdtdupyn() == null ? other.getRcpdtdupyn() == null : this.getRcpdtdupyn().equals(other.getRcpdtdupyn()))
            && (this.getUsesmsyn() == null ? other.getUsesmsyn() == null : this.getUsesmsyn().equals(other.getUsesmsyn()))
            && (this.getNotsmsyn() == null ? other.getNotsmsyn() == null : this.getNotsmsyn().equals(other.getNotsmsyn()))
            && (this.getRcpsmsyn() == null ? other.getRcpsmsyn() == null : this.getRcpsmsyn().equals(other.getRcpsmsyn()))
            && (this.getRcpsmsty() == null ? other.getRcpsmsty() == null : this.getRcpsmsty().equals(other.getRcpsmsty()))
            && (this.getUsemailyn() == null ? other.getUsemailyn() == null : this.getUsemailyn().equals(other.getUsemailyn()))
            && (this.getAmtchkty() == null ? other.getAmtchkty() == null : this.getAmtchkty().equals(other.getAmtchkty()))
            && (this.getCusnamety() == null ? other.getCusnamety() == null : this.getCusnamety().equals(other.getCusnamety()))
            && (this.getNotaxyn() == null ? other.getNotaxyn() == null : this.getNotaxyn().equals(other.getNotaxyn()))
            && (this.getChatrty() == null ? other.getChatrty() == null : this.getChatrty().equals(other.getChatrty()))
            && (this.getChaip() == null ? other.getChaip() == null : this.getChaip().equals(other.getChaip()))
            && (this.getChaport() == null ? other.getChaport() == null : this.getChaport().equals(other.getChaport()))
            && (this.getCusgubn1() == null ? other.getCusgubn1() == null : this.getCusgubn1().equals(other.getCusgubn1()))
            && (this.getCusgubn2() == null ? other.getCusgubn2() == null : this.getCusgubn2().equals(other.getCusgubn2()))
            && (this.getCusgubn3() == null ? other.getCusgubn3() == null : this.getCusgubn3().equals(other.getCusgubn3()))
            && (this.getCusgubn4() == null ? other.getCusgubn4() == null : this.getCusgubn4().equals(other.getCusgubn4()))
            && (this.getCusgubnyn1() == null ? other.getCusgubnyn1() == null : this.getCusgubnyn1().equals(other.getCusgubnyn1()))
            && (this.getCusgubnyn2() == null ? other.getCusgubnyn2() == null : this.getCusgubnyn2().equals(other.getCusgubnyn2()))
            && (this.getCusgubnyn3() == null ? other.getCusgubnyn3() == null : this.getCusgubnyn3().equals(other.getCusgubnyn3()))
            && (this.getCusgubnyn4() == null ? other.getCusgubnyn4() == null : this.getCusgubnyn4().equals(other.getCusgubnyn4()))
            && (this.getNotsms() == null ? other.getNotsms() == null : this.getNotsms().equals(other.getNotsms()))
            && (this.getRcpsms() == null ? other.getRcpsms() == null : this.getRcpsms().equals(other.getRcpsms()))
            && (this.getChasvcyn() == null ? other.getChasvcyn() == null : this.getChasvcyn().equals(other.getChasvcyn()))
            && (this.getChasvcdt() == null ? other.getChasvcdt() == null : this.getChasvcdt().equals(other.getChasvcdt()))
            && (this.getBillname() == null ? other.getBillname() == null : this.getBillname().equals(other.getBillname()))
            && (this.getCusals() == null ? other.getCusals() == null : this.getCusals().equals(other.getCusals()))
            && (this.getNotichaname() == null ? other.getNotichaname() == null : this.getNotichaname().equals(other.getNotichaname()))
            && (this.getTelno() == null ? other.getTelno() == null : this.getTelno().equals(other.getTelno()))
            && (this.getBillcont1() == null ? other.getBillcont1() == null : this.getBillcont1().equals(other.getBillcont1()))
            && (this.getBillcont2() == null ? other.getBillcont2() == null : this.getBillcont2().equals(other.getBillcont2()))
            && (this.getBillcont3() == null ? other.getBillcont3() == null : this.getBillcont3().equals(other.getBillcont3()))
            && (this.getBillcont4() == null ? other.getBillcont4() == null : this.getBillcont4().equals(other.getBillcont4()))
            && (this.getBillcont5() == null ? other.getBillcont5() == null : this.getBillcont5().equals(other.getBillcont5()))
            && (this.getBillcont6() == null ? other.getBillcont6() == null : this.getBillcont6().equals(other.getBillcont6()))
            && (this.getBillcont7() == null ? other.getBillcont7() == null : this.getBillcont7().equals(other.getBillcont7()))
            && (this.getBillcont8() == null ? other.getBillcont8() == null : this.getBillcont8().equals(other.getBillcont8()))
            && (this.getBillcont9() == null ? other.getBillcont9() == null : this.getBillcont9().equals(other.getBillcont9()))
            && (this.getBillcont10() == null ? other.getBillcont10() == null : this.getBillcont10().equals(other.getBillcont10()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getChast() == null ? other.getChast() == null : this.getChast().equals(other.getChast()))
            && (this.getMakedt() == null ? other.getMakedt() == null : this.getMakedt().equals(other.getMakedt()))
            && (this.getMaker() == null ? other.getMaker() == null : this.getMaker().equals(other.getMaker()))
            && (this.getRegdt() == null ? other.getRegdt() == null : this.getRegdt().equals(other.getRegdt()))
            && (this.getBillimgty() == null ? other.getBillimgty() == null : this.getBillimgty().equals(other.getBillimgty()))
            && (this.getUsepgyn() == null ? other.getUsepgyn() == null : this.getUsepgyn().equals(other.getUsepgyn()))
            && (this.getChkcash() == null ? other.getChkcash() == null : this.getChkcash().equals(other.getChkcash()))
            && (this.getChkoff() == null ? other.getChkoff() == null : this.getChkoff().equals(other.getChkoff()))
            && (this.getChkcms() == null ? other.getChkcms() == null : this.getChkcms().equals(other.getChkcms()))
            && (this.getUsecmsyn() == null ? other.getUsecmsyn() == null : this.getUsecmsyn().equals(other.getUsecmsyn()))
            && (this.getNotminlimit() == null ? other.getNotminlimit() == null : this.getNotminlimit().equals(other.getNotminlimit()))
            && (this.getNotminfee() == null ? other.getNotminfee() == null : this.getNotminfee().equals(other.getNotminfee()))
            && (this.getNotcntfee() == null ? other.getNotcntfee() == null : this.getNotcntfee().equals(other.getNotcntfee()))
            && (this.getRcpcntfee() == null ? other.getRcpcntfee() == null : this.getRcpcntfee().equals(other.getRcpcntfee()))
            && (this.getRcpbnkfee() == null ? other.getRcpbnkfee() == null : this.getRcpbnkfee().equals(other.getRcpbnkfee()))
            && (this.getChagroupid() == null ? other.getChagroupid() == null : this.getChagroupid().equals(other.getChagroupid()))
            && (this.getBillcont11() == null ? other.getBillcont11() == null : this.getBillcont11().equals(other.getBillcont11()))
            && (this.getCussms() == null ? other.getCussms() == null : this.getCussms().equals(other.getCussms()))
            && (this.getRcpreqsvety() == null ? other.getRcpreqsvety() == null : this.getRcpreqsvety().equals(other.getRcpreqsvety()))
            && (this.getNotsms2() == null ? other.getNotsms2() == null : this.getNotsms2().equals(other.getNotsms2()))
            && (this.getMakeip() == null ? other.getMakeip() == null : this.getMakeip().equals(other.getMakeip()))
            && (this.getPgserviceid() == null ? other.getPgserviceid() == null : this.getPgserviceid().equals(other.getPgserviceid()))
            && (this.getChagubn() == null ? other.getChagubn() == null : this.getChagubn().equals(other.getChagubn()))
            && (this.getPrechast() == null ? other.getPrechast() == null : this.getPrechast().equals(other.getPrechast()))
            && (this.getHolddt() == null ? other.getHolddt() == null : this.getHolddt().equals(other.getHolddt()))
            && (this.getHoldreason() == null ? other.getHoldreason() == null : this.getHoldreason().equals(other.getHoldreason()))
            && (this.getRsltpgyn() == null ? other.getRsltpgyn() == null : this.getRsltpgyn().equals(other.getRsltpgyn()))
            && (this.getRcpDueChk() == null ? other.getRcpDueChk() == null : this.getRcpDueChk().equals(other.getRcpDueChk()))
            && (this.getSmsMsgDef1() == null ? other.getSmsMsgDef1() == null : this.getSmsMsgDef1().equals(other.getSmsMsgDef1()))
            && (this.getSmsMsgDef2() == null ? other.getSmsMsgDef2() == null : this.getSmsMsgDef2().equals(other.getSmsMsgDef2()))
            && (this.getRcpreIssuYn() == null ? other.getRcpreIssuYn() == null : this.getRcpreIssuYn().equals(other.getRcpreIssuYn()))
            && (this.getChaCloseChk() == null ? other.getChaCloseChk() == null : this.getChaCloseChk().equals(other.getChaCloseChk()))
            && (this.getDaMngMemo() == null ? other.getDaMngMemo() == null : this.getDaMngMemo().equals(other.getDaMngMemo()))
            && (this.getCmsFileName() == null ? other.getCmsFileName() == null : this.getCmsFileName().equals(other.getCmsFileName()))
            && (this.getCmsReqSt() == null ? other.getCmsReqSt() == null : this.getCmsReqSt().equals(other.getCmsReqSt()))
            && (this.getCmsReqFailCont() == null ? other.getCmsReqFailCont() == null : this.getCmsReqFailCont().equals(other.getCmsReqFailCont()))
            && (this.getSmsAplDt() == null ? other.getSmsAplDt() == null : this.getSmsAplDt().equals(other.getSmsAplDt()))
            && (this.getSmsAplMemo() == null ? other.getSmsAplMemo() == null : this.getSmsAplMemo().equals(other.getSmsAplMemo()))
            && (this.getPgAprDt() == null ? other.getPgAprDt() == null : this.getPgAprDt().equals(other.getPgAprDt()))
            && (this.getPgAprMemo() == null ? other.getPgAprMemo() == null : this.getPgAprMemo().equals(other.getPgAprMemo()))
            && (this.getPgComName() == null ? other.getPgComName() == null : this.getPgComName().equals(other.getPgComName()))
            && (this.getPgLicenKey() == null ? other.getPgLicenKey() == null : this.getPgLicenKey().equals(other.getPgLicenKey()))
            && (this.getPgRevCommiRate() == null ? other.getPgRevCommiRate() == null : this.getPgRevCommiRate().equals(other.getPgRevCommiRate()))
            && (this.getFingerRevCommiRate() == null ? other.getFingerRevCommiRate() == null : this.getFingerRevCommiRate().equals(other.getFingerRevCommiRate()))
            && (this.getChaNewRegDt() == null ? other.getChaNewRegDt() == null : this.getChaNewRegDt().equals(other.getChaNewRegDt()))
            && (this.getChaCloseDt() == null ? other.getChaCloseDt() == null : this.getChaCloseDt().equals(other.getChaCloseDt()))
            && (this.getChaCloseSt() == null ? other.getChaCloseSt() == null : this.getChaCloseSt().equals(other.getChaCloseSt()))
            && (this.getChaCloseVarDt() == null ? other.getChaCloseVarDt() == null : this.getChaCloseVarDt().equals(other.getChaCloseVarDt()))
            && (this.getChaCloseVarReson() == null ? other.getChaCloseVarReson() == null : this.getChaCloseVarReson().equals(other.getChaCloseVarReson()))
            && (this.getCmsReqDt() == null ? other.getCmsReqDt() == null : this.getCmsReqDt().equals(other.getCmsReqDt()))
            && (this.getCmsReqFinDt() == null ? other.getCmsReqFinDt() == null : this.getCmsReqFinDt().equals(other.getCmsReqFinDt()))
            && (this.getCmsAppGubn() == null ? other.getCmsAppGubn() == null : this.getCmsAppGubn().equals(other.getCmsAppGubn()))
            && (this.getPartialPayment() == null ? other.getPartialPayment() == null : this.getPartialPayment().equals(other.getPartialPayment()))
            && (this.getFingerFeeBankCode() == null ? other.getFingerFeeBankCode() == null : this.getFingerFeeBankCode().equals(other.getFingerFeeBankCode()))
            && (this.getFingerFeeAccountNo() == null ? other.getFingerFeeAccountNo() == null : this.getFingerFeeAccountNo().equals(other.getFingerFeeAccountNo()))
            && (this.getFingerFeeAgreeStatus() == null ? other.getFingerFeeAgreeStatus() == null : this.getFingerFeeAgreeStatus().equals(other.getFingerFeeAgreeStatus()))
            && (this.getWithdrawAgreementId() == null ? other.getWithdrawAgreementId() == null : this.getWithdrawAgreementId().equals(other.getWithdrawAgreementId()))
            && (this.getFingerFeeAccountOwner() == null ? other.getFingerFeeAccountOwner() == null : this.getFingerFeeAccountOwner().equals(other.getFingerFeeAccountOwner()))
            && (this.getFingerFeeAccountIdentity() == null ? other.getFingerFeeAccountIdentity() == null : this.getFingerFeeAccountIdentity().equals(other.getFingerFeeAccountIdentity()))
            && (this.getFingerFeeOwnerNo() == null ? other.getFingerFeeOwnerNo() == null : this.getFingerFeeOwnerNo().equals(other.getFingerFeeOwnerNo()))
            && (this.getFingerFeePayty() == null ? other.getFingerFeePayty() == null : this.getFingerFeePayty().equals(other.getFingerFeePayty()))
            && (this.getMnlrcpreqty() == null ? other.getMnlrcpreqty() == null : this.getMnlrcpreqty().equals(other.getMnlrcpreqty()))
            && (this.getBankRegiDt() == null ? other.getBankRegiDt() == null : this.getBankRegiDt().equals(other.getBankRegiDt()))
            && (this.getBankAcptDt() == null ? other.getBankAcptDt() == null : this.getBankAcptDt().equals(other.getBankAcptDt()))
            && (this.getMandRcpYn() == null ? other.getMandRcpYn() == null : this.getMandRcpYn().equals(other.getMandRcpYn()))
            && (this.getPrnFreeYn() == null ? other.getPrnFreeYn() == null : this.getPrnFreeYn().equals(other.getPrnFreeYn()))
            && (this.getAtyn() == null ? other.getAtyn() == null : this.getAtyn().equals(other.getAtyn()))
            && (this.getNotatyn() == null ? other.getNotatyn() == null : this.getNotatyn().equals(other.getNotatyn()))
            && (this.getRcpatyn() == null ? other.getRcpatyn() == null : this.getRcpatyn().equals(other.getRcpatyn()))
            && (this.getAtchaname() == null ? other.getAtchaname() == null : this.getAtchaname().equals(other.getAtchaname()))
            && (this.getAtregdt() == null ? other.getAtregdt() == null : this.getAtregdt().equals(other.getAtregdt()))
            && (this.getAtacptdt() == null ? other.getAtacptdt() == null : this.getAtacptdt().equals(other.getAtacptdt()))
            && (this.getAtcncldt() == null ? other.getAtcncldt() == null : this.getAtcncldt().equals(other.getAtcncldt()))
            && (this.getChrhp() == null ? other.getChrhp() == null : this.getChrhp().equals(other.getChrhp()))
            && (this.getFeeaccno() == null ? other.getFeeaccno() == null : this.getFeeaccno().equals(other.getFeeaccno()))
            && (this.getFeeoffno() == null ? other.getFeeoffno() == null : this.getFeeoffno().equals(other.getFeeoffno()))
            && (this.getConhp() == null ? other.getConhp() == null : this.getConhp().equals(other.getConhp()))
            && (this.getSmsSendTel() == null ? other.getSmsSendTel() == null : this.getSmsSendTel().equals(other.getSmsSendTel()))
            && (this.getUsrpwd() == null ? other.getUsrpwd() == null : this.getUsrpwd().equals(other.getUsrpwd()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XCHALIST
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getChacd() == null) ? 0 : getChacd().hashCode());
        result = prime * result + ((getAgtcd() == null) ? 0 : getAgtcd().hashCode());
        result = prime * result + ((getChaname() == null) ? 0 : getChaname().hashCode());
        result = prime * result + ((getOwner() == null) ? 0 : getOwner().hashCode());
        result = prime * result + ((getOwnertel() == null) ? 0 : getOwnertel().hashCode());
        result = prime * result + ((getChaoffno() == null) ? 0 : getChaoffno().hashCode());
        result = prime * result + ((getChastatus() == null) ? 0 : getChastatus().hashCode());
        result = prime * result + ((getChatype() == null) ? 0 : getChatype().hashCode());
        result = prime * result + ((getChaaddress1() == null) ? 0 : getChaaddress1().hashCode());
        result = prime * result + ((getChaaddress2() == null) ? 0 : getChaaddress2().hashCode());
        result = prime * result + ((getChazipcode() == null) ? 0 : getChazipcode().hashCode());
        result = prime * result + ((getChrname() == null) ? 0 : getChrname().hashCode());
        result = prime * result + ((getChrtelno() == null) ? 0 : getChrtelno().hashCode());
        result = prime * result + ((getChrmail() == null) ? 0 : getChrmail().hashCode());
        result = prime * result + ((getFeeaccname() == null) ? 0 : getFeeaccname().hashCode());
        result = prime * result + ((getAccnocnt() == null) ? 0 : getAccnocnt().hashCode());
        result = prime * result + ((getConname() == null) ? 0 : getConname().hashCode());
        result = prime * result + ((getContelno() == null) ? 0 : getContelno().hashCode());
        result = prime * result + ((getAdjaccyn() == null) ? 0 : getAdjaccyn().hashCode());
        result = prime * result + ((getRcpreqyn() == null) ? 0 : getRcpreqyn().hashCode());
        result = prime * result + ((getRcpreqty() == null) ? 0 : getRcpreqty().hashCode());
        result = prime * result + ((getRcpdtdupyn() == null) ? 0 : getRcpdtdupyn().hashCode());
        result = prime * result + ((getUsesmsyn() == null) ? 0 : getUsesmsyn().hashCode());
        result = prime * result + ((getNotsmsyn() == null) ? 0 : getNotsmsyn().hashCode());
        result = prime * result + ((getRcpsmsyn() == null) ? 0 : getRcpsmsyn().hashCode());
        result = prime * result + ((getRcpsmsty() == null) ? 0 : getRcpsmsty().hashCode());
        result = prime * result + ((getUsemailyn() == null) ? 0 : getUsemailyn().hashCode());
        result = prime * result + ((getAmtchkty() == null) ? 0 : getAmtchkty().hashCode());
        result = prime * result + ((getCusnamety() == null) ? 0 : getCusnamety().hashCode());
        result = prime * result + ((getNotaxyn() == null) ? 0 : getNotaxyn().hashCode());
        result = prime * result + ((getChatrty() == null) ? 0 : getChatrty().hashCode());
        result = prime * result + ((getChaip() == null) ? 0 : getChaip().hashCode());
        result = prime * result + ((getChaport() == null) ? 0 : getChaport().hashCode());
        result = prime * result + ((getCusgubn1() == null) ? 0 : getCusgubn1().hashCode());
        result = prime * result + ((getCusgubn2() == null) ? 0 : getCusgubn2().hashCode());
        result = prime * result + ((getCusgubn3() == null) ? 0 : getCusgubn3().hashCode());
        result = prime * result + ((getCusgubn4() == null) ? 0 : getCusgubn4().hashCode());
        result = prime * result + ((getCusgubnyn1() == null) ? 0 : getCusgubnyn1().hashCode());
        result = prime * result + ((getCusgubnyn2() == null) ? 0 : getCusgubnyn2().hashCode());
        result = prime * result + ((getCusgubnyn3() == null) ? 0 : getCusgubnyn3().hashCode());
        result = prime * result + ((getCusgubnyn4() == null) ? 0 : getCusgubnyn4().hashCode());
        result = prime * result + ((getNotsms() == null) ? 0 : getNotsms().hashCode());
        result = prime * result + ((getRcpsms() == null) ? 0 : getRcpsms().hashCode());
        result = prime * result + ((getChasvcyn() == null) ? 0 : getChasvcyn().hashCode());
        result = prime * result + ((getChasvcdt() == null) ? 0 : getChasvcdt().hashCode());
        result = prime * result + ((getBillname() == null) ? 0 : getBillname().hashCode());
        result = prime * result + ((getCusals() == null) ? 0 : getCusals().hashCode());
        result = prime * result + ((getNotichaname() == null) ? 0 : getNotichaname().hashCode());
        result = prime * result + ((getTelno() == null) ? 0 : getTelno().hashCode());
        result = prime * result + ((getBillcont1() == null) ? 0 : getBillcont1().hashCode());
        result = prime * result + ((getBillcont2() == null) ? 0 : getBillcont2().hashCode());
        result = prime * result + ((getBillcont3() == null) ? 0 : getBillcont3().hashCode());
        result = prime * result + ((getBillcont4() == null) ? 0 : getBillcont4().hashCode());
        result = prime * result + ((getBillcont5() == null) ? 0 : getBillcont5().hashCode());
        result = prime * result + ((getBillcont6() == null) ? 0 : getBillcont6().hashCode());
        result = prime * result + ((getBillcont7() == null) ? 0 : getBillcont7().hashCode());
        result = prime * result + ((getBillcont8() == null) ? 0 : getBillcont8().hashCode());
        result = prime * result + ((getBillcont9() == null) ? 0 : getBillcont9().hashCode());
        result = prime * result + ((getBillcont10() == null) ? 0 : getBillcont10().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getChast() == null) ? 0 : getChast().hashCode());
        result = prime * result + ((getMakedt() == null) ? 0 : getMakedt().hashCode());
        result = prime * result + ((getMaker() == null) ? 0 : getMaker().hashCode());
        result = prime * result + ((getRegdt() == null) ? 0 : getRegdt().hashCode());
        result = prime * result + ((getBillimgty() == null) ? 0 : getBillimgty().hashCode());
        result = prime * result + ((getUsepgyn() == null) ? 0 : getUsepgyn().hashCode());
        result = prime * result + ((getChkcash() == null) ? 0 : getChkcash().hashCode());
        result = prime * result + ((getChkoff() == null) ? 0 : getChkoff().hashCode());
        result = prime * result + ((getChkcms() == null) ? 0 : getChkcms().hashCode());
        result = prime * result + ((getUsecmsyn() == null) ? 0 : getUsecmsyn().hashCode());
        result = prime * result + ((getNotminlimit() == null) ? 0 : getNotminlimit().hashCode());
        result = prime * result + ((getNotminfee() == null) ? 0 : getNotminfee().hashCode());
        result = prime * result + ((getNotcntfee() == null) ? 0 : getNotcntfee().hashCode());
        result = prime * result + ((getRcpcntfee() == null) ? 0 : getRcpcntfee().hashCode());
        result = prime * result + ((getRcpbnkfee() == null) ? 0 : getRcpbnkfee().hashCode());
        result = prime * result + ((getChagroupid() == null) ? 0 : getChagroupid().hashCode());
        result = prime * result + ((getBillcont11() == null) ? 0 : getBillcont11().hashCode());
        result = prime * result + ((getCussms() == null) ? 0 : getCussms().hashCode());
        result = prime * result + ((getRcpreqsvety() == null) ? 0 : getRcpreqsvety().hashCode());
        result = prime * result + ((getNotsms2() == null) ? 0 : getNotsms2().hashCode());
        result = prime * result + ((getMakeip() == null) ? 0 : getMakeip().hashCode());
        result = prime * result + ((getPgserviceid() == null) ? 0 : getPgserviceid().hashCode());
        result = prime * result + ((getChagubn() == null) ? 0 : getChagubn().hashCode());
        result = prime * result + ((getPrechast() == null) ? 0 : getPrechast().hashCode());
        result = prime * result + ((getHolddt() == null) ? 0 : getHolddt().hashCode());
        result = prime * result + ((getHoldreason() == null) ? 0 : getHoldreason().hashCode());
        result = prime * result + ((getRsltpgyn() == null) ? 0 : getRsltpgyn().hashCode());
        result = prime * result + ((getRcpDueChk() == null) ? 0 : getRcpDueChk().hashCode());
        result = prime * result + ((getSmsMsgDef1() == null) ? 0 : getSmsMsgDef1().hashCode());
        result = prime * result + ((getSmsMsgDef2() == null) ? 0 : getSmsMsgDef2().hashCode());
        result = prime * result + ((getRcpreIssuYn() == null) ? 0 : getRcpreIssuYn().hashCode());
        result = prime * result + ((getChaCloseChk() == null) ? 0 : getChaCloseChk().hashCode());
        result = prime * result + ((getDaMngMemo() == null) ? 0 : getDaMngMemo().hashCode());
        result = prime * result + ((getCmsFileName() == null) ? 0 : getCmsFileName().hashCode());
        result = prime * result + ((getCmsReqSt() == null) ? 0 : getCmsReqSt().hashCode());
        result = prime * result + ((getCmsReqFailCont() == null) ? 0 : getCmsReqFailCont().hashCode());
        result = prime * result + ((getSmsAplDt() == null) ? 0 : getSmsAplDt().hashCode());
        result = prime * result + ((getSmsAplMemo() == null) ? 0 : getSmsAplMemo().hashCode());
        result = prime * result + ((getPgAprDt() == null) ? 0 : getPgAprDt().hashCode());
        result = prime * result + ((getPgAprMemo() == null) ? 0 : getPgAprMemo().hashCode());
        result = prime * result + ((getPgComName() == null) ? 0 : getPgComName().hashCode());
        result = prime * result + ((getPgLicenKey() == null) ? 0 : getPgLicenKey().hashCode());
        result = prime * result + ((getPgRevCommiRate() == null) ? 0 : getPgRevCommiRate().hashCode());
        result = prime * result + ((getFingerRevCommiRate() == null) ? 0 : getFingerRevCommiRate().hashCode());
        result = prime * result + ((getChaNewRegDt() == null) ? 0 : getChaNewRegDt().hashCode());
        result = prime * result + ((getChaCloseDt() == null) ? 0 : getChaCloseDt().hashCode());
        result = prime * result + ((getChaCloseSt() == null) ? 0 : getChaCloseSt().hashCode());
        result = prime * result + ((getChaCloseVarDt() == null) ? 0 : getChaCloseVarDt().hashCode());
        result = prime * result + ((getChaCloseVarReson() == null) ? 0 : getChaCloseVarReson().hashCode());
        result = prime * result + ((getCmsReqDt() == null) ? 0 : getCmsReqDt().hashCode());
        result = prime * result + ((getCmsReqFinDt() == null) ? 0 : getCmsReqFinDt().hashCode());
        result = prime * result + ((getCmsAppGubn() == null) ? 0 : getCmsAppGubn().hashCode());
        result = prime * result + ((getPartialPayment() == null) ? 0 : getPartialPayment().hashCode());
        result = prime * result + ((getFingerFeeBankCode() == null) ? 0 : getFingerFeeBankCode().hashCode());
        result = prime * result + ((getFingerFeeAccountNo() == null) ? 0 : getFingerFeeAccountNo().hashCode());
        result = prime * result + ((getFingerFeeAgreeStatus() == null) ? 0 : getFingerFeeAgreeStatus().hashCode());
        result = prime * result + ((getWithdrawAgreementId() == null) ? 0 : getWithdrawAgreementId().hashCode());
        result = prime * result + ((getFingerFeeAccountOwner() == null) ? 0 : getFingerFeeAccountOwner().hashCode());
        result = prime * result + ((getFingerFeeAccountIdentity() == null) ? 0 : getFingerFeeAccountIdentity().hashCode());
        result = prime * result + ((getFingerFeeOwnerNo() == null) ? 0 : getFingerFeeOwnerNo().hashCode());
        result = prime * result + ((getFingerFeePayty() == null) ? 0 : getFingerFeePayty().hashCode());
        result = prime * result + ((getMnlrcpreqty() == null) ? 0 : getMnlrcpreqty().hashCode());
        result = prime * result + ((getBankRegiDt() == null) ? 0 : getBankRegiDt().hashCode());
        result = prime * result + ((getBankAcptDt() == null) ? 0 : getBankAcptDt().hashCode());
        result = prime * result + ((getMandRcpYn() == null) ? 0 : getMandRcpYn().hashCode());
        result = prime * result + ((getPrnFreeYn() == null) ? 0 : getPrnFreeYn().hashCode());
        result = prime * result + ((getAtyn() == null) ? 0 : getAtyn().hashCode());
        result = prime * result + ((getNotatyn() == null) ? 0 : getNotatyn().hashCode());
        result = prime * result + ((getRcpatyn() == null) ? 0 : getRcpatyn().hashCode());
        result = prime * result + ((getAtchaname() == null) ? 0 : getAtchaname().hashCode());
        result = prime * result + ((getAtregdt() == null) ? 0 : getAtregdt().hashCode());
        result = prime * result + ((getAtacptdt() == null) ? 0 : getAtacptdt().hashCode());
        result = prime * result + ((getAtcncldt() == null) ? 0 : getAtcncldt().hashCode());
        result = prime * result + ((getChrhp() == null) ? 0 : getChrhp().hashCode());
        result = prime * result + ((getFeeaccno() == null) ? 0 : getFeeaccno().hashCode());
        result = prime * result + ((getFeeoffno() == null) ? 0 : getFeeoffno().hashCode());
        result = prime * result + ((getConhp() == null) ? 0 : getConhp().hashCode());
        result = prime * result + ((getSmsSendTel() == null) ? 0 : getSmsSendTel().hashCode());
        result = prime * result + ((getUsrpwd() == null) ? 0 : getUsrpwd().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XCHALIST
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", chrhp=").append(chrhp);
        sb.append(", feeaccno=").append(feeaccno);
        sb.append(", feeoffno=").append(feeoffno);
        sb.append(", conhp=").append(conhp);
        sb.append(", smsSendTel=").append(smsSendTel);
        sb.append(", usrpwd=").append(usrpwd);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}