package com.finger.shinhandamoa.data.table.model;

import java.util.ArrayList;
import java.util.List;

public class CooconARSExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coocon_ars
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coocon_ars
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coocon_ars
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coocon_ars
     *
     * @mbg.generated
     */
    public CooconARSExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coocon_ars
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coocon_ars
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coocon_ars
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coocon_ars
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coocon_ars
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coocon_ars
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coocon_ars
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coocon_ars
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coocon_ars
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coocon_ars
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table coocon_ars
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andReqTrCdIsNull() {
            addCriterion("req_tr_cd is null");
            return (Criteria) this;
        }

        public Criteria andReqTrCdIsNotNull() {
            addCriterion("req_tr_cd is not null");
            return (Criteria) this;
        }

        public Criteria andReqTrCdEqualTo(String value) {
            addCriterion("req_tr_cd =", value, "reqTrCd");
            return (Criteria) this;
        }

        public Criteria andReqTrCdNotEqualTo(String value) {
            addCriterion("req_tr_cd <>", value, "reqTrCd");
            return (Criteria) this;
        }

        public Criteria andReqTrCdGreaterThan(String value) {
            addCriterion("req_tr_cd >", value, "reqTrCd");
            return (Criteria) this;
        }

        public Criteria andReqTrCdGreaterThanOrEqualTo(String value) {
            addCriterion("req_tr_cd >=", value, "reqTrCd");
            return (Criteria) this;
        }

        public Criteria andReqTrCdLessThan(String value) {
            addCriterion("req_tr_cd <", value, "reqTrCd");
            return (Criteria) this;
        }

        public Criteria andReqTrCdLessThanOrEqualTo(String value) {
            addCriterion("req_tr_cd <=", value, "reqTrCd");
            return (Criteria) this;
        }

        public Criteria andReqTrCdLike(String value) {
            addCriterion("req_tr_cd like", value, "reqTrCd");
            return (Criteria) this;
        }

        public Criteria andReqTrCdNotLike(String value) {
            addCriterion("req_tr_cd not like", value, "reqTrCd");
            return (Criteria) this;
        }

        public Criteria andReqTrCdIn(List<String> values) {
            addCriterion("req_tr_cd in", values, "reqTrCd");
            return (Criteria) this;
        }

        public Criteria andReqTrCdNotIn(List<String> values) {
            addCriterion("req_tr_cd not in", values, "reqTrCd");
            return (Criteria) this;
        }

        public Criteria andReqTrCdBetween(String value1, String value2) {
            addCriterion("req_tr_cd between", value1, value2, "reqTrCd");
            return (Criteria) this;
        }

        public Criteria andReqTrCdNotBetween(String value1, String value2) {
            addCriterion("req_tr_cd not between", value1, value2, "reqTrCd");
            return (Criteria) this;
        }

        public Criteria andReqOrgCdIsNull() {
            addCriterion("req_org_cd is null");
            return (Criteria) this;
        }

        public Criteria andReqOrgCdIsNotNull() {
            addCriterion("req_org_cd is not null");
            return (Criteria) this;
        }

        public Criteria andReqOrgCdEqualTo(String value) {
            addCriterion("req_org_cd =", value, "reqOrgCd");
            return (Criteria) this;
        }

        public Criteria andReqOrgCdNotEqualTo(String value) {
            addCriterion("req_org_cd <>", value, "reqOrgCd");
            return (Criteria) this;
        }

        public Criteria andReqOrgCdGreaterThan(String value) {
            addCriterion("req_org_cd >", value, "reqOrgCd");
            return (Criteria) this;
        }

        public Criteria andReqOrgCdGreaterThanOrEqualTo(String value) {
            addCriterion("req_org_cd >=", value, "reqOrgCd");
            return (Criteria) this;
        }

        public Criteria andReqOrgCdLessThan(String value) {
            addCriterion("req_org_cd <", value, "reqOrgCd");
            return (Criteria) this;
        }

        public Criteria andReqOrgCdLessThanOrEqualTo(String value) {
            addCriterion("req_org_cd <=", value, "reqOrgCd");
            return (Criteria) this;
        }

        public Criteria andReqOrgCdLike(String value) {
            addCriterion("req_org_cd like", value, "reqOrgCd");
            return (Criteria) this;
        }

        public Criteria andReqOrgCdNotLike(String value) {
            addCriterion("req_org_cd not like", value, "reqOrgCd");
            return (Criteria) this;
        }

        public Criteria andReqOrgCdIn(List<String> values) {
            addCriterion("req_org_cd in", values, "reqOrgCd");
            return (Criteria) this;
        }

        public Criteria andReqOrgCdNotIn(List<String> values) {
            addCriterion("req_org_cd not in", values, "reqOrgCd");
            return (Criteria) this;
        }

        public Criteria andReqOrgCdBetween(String value1, String value2) {
            addCriterion("req_org_cd between", value1, value2, "reqOrgCd");
            return (Criteria) this;
        }

        public Criteria andReqOrgCdNotBetween(String value1, String value2) {
            addCriterion("req_org_cd not between", value1, value2, "reqOrgCd");
            return (Criteria) this;
        }

        public Criteria andReqTxDateIsNull() {
            addCriterion("req_tx_date is null");
            return (Criteria) this;
        }

        public Criteria andReqTxDateIsNotNull() {
            addCriterion("req_tx_date is not null");
            return (Criteria) this;
        }

        public Criteria andReqTxDateEqualTo(String value) {
            addCriterion("req_tx_date =", value, "reqTxDate");
            return (Criteria) this;
        }

        public Criteria andReqTxDateNotEqualTo(String value) {
            addCriterion("req_tx_date <>", value, "reqTxDate");
            return (Criteria) this;
        }

        public Criteria andReqTxDateGreaterThan(String value) {
            addCriterion("req_tx_date >", value, "reqTxDate");
            return (Criteria) this;
        }

        public Criteria andReqTxDateGreaterThanOrEqualTo(String value) {
            addCriterion("req_tx_date >=", value, "reqTxDate");
            return (Criteria) this;
        }

        public Criteria andReqTxDateLessThan(String value) {
            addCriterion("req_tx_date <", value, "reqTxDate");
            return (Criteria) this;
        }

        public Criteria andReqTxDateLessThanOrEqualTo(String value) {
            addCriterion("req_tx_date <=", value, "reqTxDate");
            return (Criteria) this;
        }

        public Criteria andReqTxDateLike(String value) {
            addCriterion("req_tx_date like", value, "reqTxDate");
            return (Criteria) this;
        }

        public Criteria andReqTxDateNotLike(String value) {
            addCriterion("req_tx_date not like", value, "reqTxDate");
            return (Criteria) this;
        }

        public Criteria andReqTxDateIn(List<String> values) {
            addCriterion("req_tx_date in", values, "reqTxDate");
            return (Criteria) this;
        }

        public Criteria andReqTxDateNotIn(List<String> values) {
            addCriterion("req_tx_date not in", values, "reqTxDate");
            return (Criteria) this;
        }

        public Criteria andReqTxDateBetween(String value1, String value2) {
            addCriterion("req_tx_date between", value1, value2, "reqTxDate");
            return (Criteria) this;
        }

        public Criteria andReqTxDateNotBetween(String value1, String value2) {
            addCriterion("req_tx_date not between", value1, value2, "reqTxDate");
            return (Criteria) this;
        }

        public Criteria andReqPhoneIsNull() {
            addCriterion("req_phone is null");
            return (Criteria) this;
        }

        public Criteria andReqPhoneIsNotNull() {
            addCriterion("req_phone is not null");
            return (Criteria) this;
        }

        public Criteria andReqPhoneEqualTo(String value) {
            addCriterion("req_phone =", value, "reqPhone");
            return (Criteria) this;
        }

        public Criteria andReqPhoneNotEqualTo(String value) {
            addCriterion("req_phone <>", value, "reqPhone");
            return (Criteria) this;
        }

        public Criteria andReqPhoneGreaterThan(String value) {
            addCriterion("req_phone >", value, "reqPhone");
            return (Criteria) this;
        }

        public Criteria andReqPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("req_phone >=", value, "reqPhone");
            return (Criteria) this;
        }

        public Criteria andReqPhoneLessThan(String value) {
            addCriterion("req_phone <", value, "reqPhone");
            return (Criteria) this;
        }

        public Criteria andReqPhoneLessThanOrEqualTo(String value) {
            addCriterion("req_phone <=", value, "reqPhone");
            return (Criteria) this;
        }

        public Criteria andReqPhoneLike(String value) {
            addCriterion("req_phone like", value, "reqPhone");
            return (Criteria) this;
        }

        public Criteria andReqPhoneNotLike(String value) {
            addCriterion("req_phone not like", value, "reqPhone");
            return (Criteria) this;
        }

        public Criteria andReqPhoneIn(List<String> values) {
            addCriterion("req_phone in", values, "reqPhone");
            return (Criteria) this;
        }

        public Criteria andReqPhoneNotIn(List<String> values) {
            addCriterion("req_phone not in", values, "reqPhone");
            return (Criteria) this;
        }

        public Criteria andReqPhoneBetween(String value1, String value2) {
            addCriterion("req_phone between", value1, value2, "reqPhone");
            return (Criteria) this;
        }

        public Criteria andReqPhoneNotBetween(String value1, String value2) {
            addCriterion("req_phone not between", value1, value2, "reqPhone");
            return (Criteria) this;
        }

        public Criteria andReqAuthNoIsNull() {
            addCriterion("req_auth_no is null");
            return (Criteria) this;
        }

        public Criteria andReqAuthNoIsNotNull() {
            addCriterion("req_auth_no is not null");
            return (Criteria) this;
        }

        public Criteria andReqAuthNoEqualTo(String value) {
            addCriterion("req_auth_no =", value, "reqAuthNo");
            return (Criteria) this;
        }

        public Criteria andReqAuthNoNotEqualTo(String value) {
            addCriterion("req_auth_no <>", value, "reqAuthNo");
            return (Criteria) this;
        }

        public Criteria andReqAuthNoGreaterThan(String value) {
            addCriterion("req_auth_no >", value, "reqAuthNo");
            return (Criteria) this;
        }

        public Criteria andReqAuthNoGreaterThanOrEqualTo(String value) {
            addCriterion("req_auth_no >=", value, "reqAuthNo");
            return (Criteria) this;
        }

        public Criteria andReqAuthNoLessThan(String value) {
            addCriterion("req_auth_no <", value, "reqAuthNo");
            return (Criteria) this;
        }

        public Criteria andReqAuthNoLessThanOrEqualTo(String value) {
            addCriterion("req_auth_no <=", value, "reqAuthNo");
            return (Criteria) this;
        }

        public Criteria andReqAuthNoLike(String value) {
            addCriterion("req_auth_no like", value, "reqAuthNo");
            return (Criteria) this;
        }

        public Criteria andReqAuthNoNotLike(String value) {
            addCriterion("req_auth_no not like", value, "reqAuthNo");
            return (Criteria) this;
        }

        public Criteria andReqAuthNoIn(List<String> values) {
            addCriterion("req_auth_no in", values, "reqAuthNo");
            return (Criteria) this;
        }

        public Criteria andReqAuthNoNotIn(List<String> values) {
            addCriterion("req_auth_no not in", values, "reqAuthNo");
            return (Criteria) this;
        }

        public Criteria andReqAuthNoBetween(String value1, String value2) {
            addCriterion("req_auth_no between", value1, value2, "reqAuthNo");
            return (Criteria) this;
        }

        public Criteria andReqAuthNoNotBetween(String value1, String value2) {
            addCriterion("req_auth_no not between", value1, value2, "reqAuthNo");
            return (Criteria) this;
        }

        public Criteria andReqFileSaveYnIsNull() {
            addCriterion("req_file_save_yn is null");
            return (Criteria) this;
        }

        public Criteria andReqFileSaveYnIsNotNull() {
            addCriterion("req_file_save_yn is not null");
            return (Criteria) this;
        }

        public Criteria andReqFileSaveYnEqualTo(String value) {
            addCriterion("req_file_save_yn =", value, "reqFileSaveYn");
            return (Criteria) this;
        }

        public Criteria andReqFileSaveYnNotEqualTo(String value) {
            addCriterion("req_file_save_yn <>", value, "reqFileSaveYn");
            return (Criteria) this;
        }

        public Criteria andReqFileSaveYnGreaterThan(String value) {
            addCriterion("req_file_save_yn >", value, "reqFileSaveYn");
            return (Criteria) this;
        }

        public Criteria andReqFileSaveYnGreaterThanOrEqualTo(String value) {
            addCriterion("req_file_save_yn >=", value, "reqFileSaveYn");
            return (Criteria) this;
        }

        public Criteria andReqFileSaveYnLessThan(String value) {
            addCriterion("req_file_save_yn <", value, "reqFileSaveYn");
            return (Criteria) this;
        }

        public Criteria andReqFileSaveYnLessThanOrEqualTo(String value) {
            addCriterion("req_file_save_yn <=", value, "reqFileSaveYn");
            return (Criteria) this;
        }

        public Criteria andReqFileSaveYnLike(String value) {
            addCriterion("req_file_save_yn like", value, "reqFileSaveYn");
            return (Criteria) this;
        }

        public Criteria andReqFileSaveYnNotLike(String value) {
            addCriterion("req_file_save_yn not like", value, "reqFileSaveYn");
            return (Criteria) this;
        }

        public Criteria andReqFileSaveYnIn(List<String> values) {
            addCriterion("req_file_save_yn in", values, "reqFileSaveYn");
            return (Criteria) this;
        }

        public Criteria andReqFileSaveYnNotIn(List<String> values) {
            addCriterion("req_file_save_yn not in", values, "reqFileSaveYn");
            return (Criteria) this;
        }

        public Criteria andReqFileSaveYnBetween(String value1, String value2) {
            addCriterion("req_file_save_yn between", value1, value2, "reqFileSaveYn");
            return (Criteria) this;
        }

        public Criteria andReqFileSaveYnNotBetween(String value1, String value2) {
            addCriterion("req_file_save_yn not between", value1, value2, "reqFileSaveYn");
            return (Criteria) this;
        }

        public Criteria andReqFileNmIsNull() {
            addCriterion("req_file_nm is null");
            return (Criteria) this;
        }

        public Criteria andReqFileNmIsNotNull() {
            addCriterion("req_file_nm is not null");
            return (Criteria) this;
        }

        public Criteria andReqFileNmEqualTo(String value) {
            addCriterion("req_file_nm =", value, "reqFileNm");
            return (Criteria) this;
        }

        public Criteria andReqFileNmNotEqualTo(String value) {
            addCriterion("req_file_nm <>", value, "reqFileNm");
            return (Criteria) this;
        }

        public Criteria andReqFileNmGreaterThan(String value) {
            addCriterion("req_file_nm >", value, "reqFileNm");
            return (Criteria) this;
        }

        public Criteria andReqFileNmGreaterThanOrEqualTo(String value) {
            addCriterion("req_file_nm >=", value, "reqFileNm");
            return (Criteria) this;
        }

        public Criteria andReqFileNmLessThan(String value) {
            addCriterion("req_file_nm <", value, "reqFileNm");
            return (Criteria) this;
        }

        public Criteria andReqFileNmLessThanOrEqualTo(String value) {
            addCriterion("req_file_nm <=", value, "reqFileNm");
            return (Criteria) this;
        }

        public Criteria andReqFileNmLike(String value) {
            addCriterion("req_file_nm like", value, "reqFileNm");
            return (Criteria) this;
        }

        public Criteria andReqFileNmNotLike(String value) {
            addCriterion("req_file_nm not like", value, "reqFileNm");
            return (Criteria) this;
        }

        public Criteria andReqFileNmIn(List<String> values) {
            addCriterion("req_file_nm in", values, "reqFileNm");
            return (Criteria) this;
        }

        public Criteria andReqFileNmNotIn(List<String> values) {
            addCriterion("req_file_nm not in", values, "reqFileNm");
            return (Criteria) this;
        }

        public Criteria andReqFileNmBetween(String value1, String value2) {
            addCriterion("req_file_nm between", value1, value2, "reqFileNm");
            return (Criteria) this;
        }

        public Criteria andReqFileNmNotBetween(String value1, String value2) {
            addCriterion("req_file_nm not between", value1, value2, "reqFileNm");
            return (Criteria) this;
        }

        public Criteria andReqAuthInqueryIsNull() {
            addCriterion("req_auth_inquery is null");
            return (Criteria) this;
        }

        public Criteria andReqAuthInqueryIsNotNull() {
            addCriterion("req_auth_inquery is not null");
            return (Criteria) this;
        }

        public Criteria andReqAuthInqueryEqualTo(String value) {
            addCriterion("req_auth_inquery =", value, "reqAuthInquery");
            return (Criteria) this;
        }

        public Criteria andReqAuthInqueryNotEqualTo(String value) {
            addCriterion("req_auth_inquery <>", value, "reqAuthInquery");
            return (Criteria) this;
        }

        public Criteria andReqAuthInqueryGreaterThan(String value) {
            addCriterion("req_auth_inquery >", value, "reqAuthInquery");
            return (Criteria) this;
        }

        public Criteria andReqAuthInqueryGreaterThanOrEqualTo(String value) {
            addCriterion("req_auth_inquery >=", value, "reqAuthInquery");
            return (Criteria) this;
        }

        public Criteria andReqAuthInqueryLessThan(String value) {
            addCriterion("req_auth_inquery <", value, "reqAuthInquery");
            return (Criteria) this;
        }

        public Criteria andReqAuthInqueryLessThanOrEqualTo(String value) {
            addCriterion("req_auth_inquery <=", value, "reqAuthInquery");
            return (Criteria) this;
        }

        public Criteria andReqAuthInqueryLike(String value) {
            addCriterion("req_auth_inquery like", value, "reqAuthInquery");
            return (Criteria) this;
        }

        public Criteria andReqAuthInqueryNotLike(String value) {
            addCriterion("req_auth_inquery not like", value, "reqAuthInquery");
            return (Criteria) this;
        }

        public Criteria andReqAuthInqueryIn(List<String> values) {
            addCriterion("req_auth_inquery in", values, "reqAuthInquery");
            return (Criteria) this;
        }

        public Criteria andReqAuthInqueryNotIn(List<String> values) {
            addCriterion("req_auth_inquery not in", values, "reqAuthInquery");
            return (Criteria) this;
        }

        public Criteria andReqAuthInqueryBetween(String value1, String value2) {
            addCriterion("req_auth_inquery between", value1, value2, "reqAuthInquery");
            return (Criteria) this;
        }

        public Criteria andReqAuthInqueryNotBetween(String value1, String value2) {
            addCriterion("req_auth_inquery not between", value1, value2, "reqAuthInquery");
            return (Criteria) this;
        }

        public Criteria andReqRecInqueryIsNull() {
            addCriterion("req_rec_inquery is null");
            return (Criteria) this;
        }

        public Criteria andReqRecInqueryIsNotNull() {
            addCriterion("req_rec_inquery is not null");
            return (Criteria) this;
        }

        public Criteria andReqRecInqueryEqualTo(String value) {
            addCriterion("req_rec_inquery =", value, "reqRecInquery");
            return (Criteria) this;
        }

        public Criteria andReqRecInqueryNotEqualTo(String value) {
            addCriterion("req_rec_inquery <>", value, "reqRecInquery");
            return (Criteria) this;
        }

        public Criteria andReqRecInqueryGreaterThan(String value) {
            addCriterion("req_rec_inquery >", value, "reqRecInquery");
            return (Criteria) this;
        }

        public Criteria andReqRecInqueryGreaterThanOrEqualTo(String value) {
            addCriterion("req_rec_inquery >=", value, "reqRecInquery");
            return (Criteria) this;
        }

        public Criteria andReqRecInqueryLessThan(String value) {
            addCriterion("req_rec_inquery <", value, "reqRecInquery");
            return (Criteria) this;
        }

        public Criteria andReqRecInqueryLessThanOrEqualTo(String value) {
            addCriterion("req_rec_inquery <=", value, "reqRecInquery");
            return (Criteria) this;
        }

        public Criteria andReqRecInqueryLike(String value) {
            addCriterion("req_rec_inquery like", value, "reqRecInquery");
            return (Criteria) this;
        }

        public Criteria andReqRecInqueryNotLike(String value) {
            addCriterion("req_rec_inquery not like", value, "reqRecInquery");
            return (Criteria) this;
        }

        public Criteria andReqRecInqueryIn(List<String> values) {
            addCriterion("req_rec_inquery in", values, "reqRecInquery");
            return (Criteria) this;
        }

        public Criteria andReqRecInqueryNotIn(List<String> values) {
            addCriterion("req_rec_inquery not in", values, "reqRecInquery");
            return (Criteria) this;
        }

        public Criteria andReqRecInqueryBetween(String value1, String value2) {
            addCriterion("req_rec_inquery between", value1, value2, "reqRecInquery");
            return (Criteria) this;
        }

        public Criteria andReqRecInqueryNotBetween(String value1, String value2) {
            addCriterion("req_rec_inquery not between", value1, value2, "reqRecInquery");
            return (Criteria) this;
        }

        public Criteria andRespRsltCdIsNull() {
            addCriterion("resp_rslt_cd is null");
            return (Criteria) this;
        }

        public Criteria andRespRsltCdIsNotNull() {
            addCriterion("resp_rslt_cd is not null");
            return (Criteria) this;
        }

        public Criteria andRespRsltCdEqualTo(String value) {
            addCriterion("resp_rslt_cd =", value, "respRsltCd");
            return (Criteria) this;
        }

        public Criteria andRespRsltCdNotEqualTo(String value) {
            addCriterion("resp_rslt_cd <>", value, "respRsltCd");
            return (Criteria) this;
        }

        public Criteria andRespRsltCdGreaterThan(String value) {
            addCriterion("resp_rslt_cd >", value, "respRsltCd");
            return (Criteria) this;
        }

        public Criteria andRespRsltCdGreaterThanOrEqualTo(String value) {
            addCriterion("resp_rslt_cd >=", value, "respRsltCd");
            return (Criteria) this;
        }

        public Criteria andRespRsltCdLessThan(String value) {
            addCriterion("resp_rslt_cd <", value, "respRsltCd");
            return (Criteria) this;
        }

        public Criteria andRespRsltCdLessThanOrEqualTo(String value) {
            addCriterion("resp_rslt_cd <=", value, "respRsltCd");
            return (Criteria) this;
        }

        public Criteria andRespRsltCdLike(String value) {
            addCriterion("resp_rslt_cd like", value, "respRsltCd");
            return (Criteria) this;
        }

        public Criteria andRespRsltCdNotLike(String value) {
            addCriterion("resp_rslt_cd not like", value, "respRsltCd");
            return (Criteria) this;
        }

        public Criteria andRespRsltCdIn(List<String> values) {
            addCriterion("resp_rslt_cd in", values, "respRsltCd");
            return (Criteria) this;
        }

        public Criteria andRespRsltCdNotIn(List<String> values) {
            addCriterion("resp_rslt_cd not in", values, "respRsltCd");
            return (Criteria) this;
        }

        public Criteria andRespRsltCdBetween(String value1, String value2) {
            addCriterion("resp_rslt_cd between", value1, value2, "respRsltCd");
            return (Criteria) this;
        }

        public Criteria andRespRsltCdNotBetween(String value1, String value2) {
            addCriterion("resp_rslt_cd not between", value1, value2, "respRsltCd");
            return (Criteria) this;
        }

        public Criteria andRespRsltMsgIsNull() {
            addCriterion("resp_rslt_msg is null");
            return (Criteria) this;
        }

        public Criteria andRespRsltMsgIsNotNull() {
            addCriterion("resp_rslt_msg is not null");
            return (Criteria) this;
        }

        public Criteria andRespRsltMsgEqualTo(String value) {
            addCriterion("resp_rslt_msg =", value, "respRsltMsg");
            return (Criteria) this;
        }

        public Criteria andRespRsltMsgNotEqualTo(String value) {
            addCriterion("resp_rslt_msg <>", value, "respRsltMsg");
            return (Criteria) this;
        }

        public Criteria andRespRsltMsgGreaterThan(String value) {
            addCriterion("resp_rslt_msg >", value, "respRsltMsg");
            return (Criteria) this;
        }

        public Criteria andRespRsltMsgGreaterThanOrEqualTo(String value) {
            addCriterion("resp_rslt_msg >=", value, "respRsltMsg");
            return (Criteria) this;
        }

        public Criteria andRespRsltMsgLessThan(String value) {
            addCriterion("resp_rslt_msg <", value, "respRsltMsg");
            return (Criteria) this;
        }

        public Criteria andRespRsltMsgLessThanOrEqualTo(String value) {
            addCriterion("resp_rslt_msg <=", value, "respRsltMsg");
            return (Criteria) this;
        }

        public Criteria andRespRsltMsgLike(String value) {
            addCriterion("resp_rslt_msg like", value, "respRsltMsg");
            return (Criteria) this;
        }

        public Criteria andRespRsltMsgNotLike(String value) {
            addCriterion("resp_rslt_msg not like", value, "respRsltMsg");
            return (Criteria) this;
        }

        public Criteria andRespRsltMsgIn(List<String> values) {
            addCriterion("resp_rslt_msg in", values, "respRsltMsg");
            return (Criteria) this;
        }

        public Criteria andRespRsltMsgNotIn(List<String> values) {
            addCriterion("resp_rslt_msg not in", values, "respRsltMsg");
            return (Criteria) this;
        }

        public Criteria andRespRsltMsgBetween(String value1, String value2) {
            addCriterion("resp_rslt_msg between", value1, value2, "respRsltMsg");
            return (Criteria) this;
        }

        public Criteria andRespRsltMsgNotBetween(String value1, String value2) {
            addCriterion("resp_rslt_msg not between", value1, value2, "respRsltMsg");
            return (Criteria) this;
        }

        public Criteria andRespTrCdIsNull() {
            addCriterion("resp_tr_cd is null");
            return (Criteria) this;
        }

        public Criteria andRespTrCdIsNotNull() {
            addCriterion("resp_tr_cd is not null");
            return (Criteria) this;
        }

        public Criteria andRespTrCdEqualTo(String value) {
            addCriterion("resp_tr_cd =", value, "respTrCd");
            return (Criteria) this;
        }

        public Criteria andRespTrCdNotEqualTo(String value) {
            addCriterion("resp_tr_cd <>", value, "respTrCd");
            return (Criteria) this;
        }

        public Criteria andRespTrCdGreaterThan(String value) {
            addCriterion("resp_tr_cd >", value, "respTrCd");
            return (Criteria) this;
        }

        public Criteria andRespTrCdGreaterThanOrEqualTo(String value) {
            addCriterion("resp_tr_cd >=", value, "respTrCd");
            return (Criteria) this;
        }

        public Criteria andRespTrCdLessThan(String value) {
            addCriterion("resp_tr_cd <", value, "respTrCd");
            return (Criteria) this;
        }

        public Criteria andRespTrCdLessThanOrEqualTo(String value) {
            addCriterion("resp_tr_cd <=", value, "respTrCd");
            return (Criteria) this;
        }

        public Criteria andRespTrCdLike(String value) {
            addCriterion("resp_tr_cd like", value, "respTrCd");
            return (Criteria) this;
        }

        public Criteria andRespTrCdNotLike(String value) {
            addCriterion("resp_tr_cd not like", value, "respTrCd");
            return (Criteria) this;
        }

        public Criteria andRespTrCdIn(List<String> values) {
            addCriterion("resp_tr_cd in", values, "respTrCd");
            return (Criteria) this;
        }

        public Criteria andRespTrCdNotIn(List<String> values) {
            addCriterion("resp_tr_cd not in", values, "respTrCd");
            return (Criteria) this;
        }

        public Criteria andRespTrCdBetween(String value1, String value2) {
            addCriterion("resp_tr_cd between", value1, value2, "respTrCd");
            return (Criteria) this;
        }

        public Criteria andRespTrCdNotBetween(String value1, String value2) {
            addCriterion("resp_tr_cd not between", value1, value2, "respTrCd");
            return (Criteria) this;
        }

        public Criteria andRespTxtNoIsNull() {
            addCriterion("resp_txt_no is null");
            return (Criteria) this;
        }

        public Criteria andRespTxtNoIsNotNull() {
            addCriterion("resp_txt_no is not null");
            return (Criteria) this;
        }

        public Criteria andRespTxtNoEqualTo(String value) {
            addCriterion("resp_txt_no =", value, "respTxtNo");
            return (Criteria) this;
        }

        public Criteria andRespTxtNoNotEqualTo(String value) {
            addCriterion("resp_txt_no <>", value, "respTxtNo");
            return (Criteria) this;
        }

        public Criteria andRespTxtNoGreaterThan(String value) {
            addCriterion("resp_txt_no >", value, "respTxtNo");
            return (Criteria) this;
        }

        public Criteria andRespTxtNoGreaterThanOrEqualTo(String value) {
            addCriterion("resp_txt_no >=", value, "respTxtNo");
            return (Criteria) this;
        }

        public Criteria andRespTxtNoLessThan(String value) {
            addCriterion("resp_txt_no <", value, "respTxtNo");
            return (Criteria) this;
        }

        public Criteria andRespTxtNoLessThanOrEqualTo(String value) {
            addCriterion("resp_txt_no <=", value, "respTxtNo");
            return (Criteria) this;
        }

        public Criteria andRespTxtNoLike(String value) {
            addCriterion("resp_txt_no like", value, "respTxtNo");
            return (Criteria) this;
        }

        public Criteria andRespTxtNoNotLike(String value) {
            addCriterion("resp_txt_no not like", value, "respTxtNo");
            return (Criteria) this;
        }

        public Criteria andRespTxtNoIn(List<String> values) {
            addCriterion("resp_txt_no in", values, "respTxtNo");
            return (Criteria) this;
        }

        public Criteria andRespTxtNoNotIn(List<String> values) {
            addCriterion("resp_txt_no not in", values, "respTxtNo");
            return (Criteria) this;
        }

        public Criteria andRespTxtNoBetween(String value1, String value2) {
            addCriterion("resp_txt_no between", value1, value2, "respTxtNo");
            return (Criteria) this;
        }

        public Criteria andRespTxtNoNotBetween(String value1, String value2) {
            addCriterion("resp_txt_no not between", value1, value2, "respTxtNo");
            return (Criteria) this;
        }

        public Criteria andIdLikeInsensitive(String value) {
            addCriterion("upper(id) like", value.toUpperCase(), "id");
            return (Criteria) this;
        }

        public Criteria andReqTrCdLikeInsensitive(String value) {
            addCriterion("upper(req_tr_cd) like", value.toUpperCase(), "reqTrCd");
            return (Criteria) this;
        }

        public Criteria andReqOrgCdLikeInsensitive(String value) {
            addCriterion("upper(req_org_cd) like", value.toUpperCase(), "reqOrgCd");
            return (Criteria) this;
        }

        public Criteria andReqTxDateLikeInsensitive(String value) {
            addCriterion("upper(req_tx_date) like", value.toUpperCase(), "reqTxDate");
            return (Criteria) this;
        }

        public Criteria andReqPhoneLikeInsensitive(String value) {
            addCriterion("upper(req_phone) like", value.toUpperCase(), "reqPhone");
            return (Criteria) this;
        }

        public Criteria andReqAuthNoLikeInsensitive(String value) {
            addCriterion("upper(req_auth_no) like", value.toUpperCase(), "reqAuthNo");
            return (Criteria) this;
        }

        public Criteria andReqFileSaveYnLikeInsensitive(String value) {
            addCriterion("upper(req_file_save_yn) like", value.toUpperCase(), "reqFileSaveYn");
            return (Criteria) this;
        }

        public Criteria andReqFileNmLikeInsensitive(String value) {
            addCriterion("upper(req_file_nm) like", value.toUpperCase(), "reqFileNm");
            return (Criteria) this;
        }

        public Criteria andReqAuthInqueryLikeInsensitive(String value) {
            addCriterion("upper(req_auth_inquery) like", value.toUpperCase(), "reqAuthInquery");
            return (Criteria) this;
        }

        public Criteria andReqRecInqueryLikeInsensitive(String value) {
            addCriterion("upper(req_rec_inquery) like", value.toUpperCase(), "reqRecInquery");
            return (Criteria) this;
        }

        public Criteria andRespRsltCdLikeInsensitive(String value) {
            addCriterion("upper(resp_rslt_cd) like", value.toUpperCase(), "respRsltCd");
            return (Criteria) this;
        }

        public Criteria andRespRsltMsgLikeInsensitive(String value) {
            addCriterion("upper(resp_rslt_msg) like", value.toUpperCase(), "respRsltMsg");
            return (Criteria) this;
        }

        public Criteria andRespTrCdLikeInsensitive(String value) {
            addCriterion("upper(resp_tr_cd) like", value.toUpperCase(), "respTrCd");
            return (Criteria) this;
        }

        public Criteria andRespTxtNoLikeInsensitive(String value) {
            addCriterion("upper(resp_txt_no) like", value.toUpperCase(), "respTxtNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table coocon_ars
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table coocon_ars
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}