package com.finger.shinhandamoa.data.table.model;

import java.io.Serializable;
import java.util.Date;

public class KftcWithdraw implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kftc_withdraw.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kftc_withdraw.eb21_id
     *
     * @mbg.generated
     */
    private String eb21Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kftc_withdraw.eb22_id
     *
     * @mbg.generated
     */
    private String eb22Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kftc_withdraw.data_no
     *
     * @mbg.generated
     */
    private String dataNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kftc_withdraw.payer_kftc_code
     *
     * @mbg.generated
     */
    private String payerKftcCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kftc_withdraw.payer_account_no
     *
     * @mbg.generated
     */
    private String payerAccountNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kftc_withdraw.amount
     *
     * @mbg.generated
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kftc_withdraw.payer_identity_no
     *
     * @mbg.generated
     */
    private String payerIdentityNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kftc_withdraw.success_yn
     *
     * @mbg.generated
     */
    private String successYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kftc_withdraw.result_cd
     *
     * @mbg.generated
     */
    private String resultCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kftc_withdraw.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kftc_withdraw.fund_type_cd
     *
     * @mbg.generated
     */
    private String fundTypeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kftc_withdraw.payer_no
     *
     * @mbg.generated
     */
    private String payerNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kftc_withdraw.user_area
     *
     * @mbg.generated
     */
    private String userArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kftc_withdraw.withdraw_type_cd
     *
     * @mbg.generated
     */
    private String withdrawTypeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kftc_withdraw.contact_no
     *
     * @mbg.generated
     */
    private String contactNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kftc_withdraw.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kftc_withdraw.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kftc_withdraw.status_cd
     *
     * @mbg.generated
     */
    private String statusCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kftc_withdraw
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kftc_withdraw.id
     *
     * @return the value of kftc_withdraw.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kftc_withdraw.id
     *
     * @param id the value for kftc_withdraw.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kftc_withdraw.eb21_id
     *
     * @return the value of kftc_withdraw.eb21_id
     *
     * @mbg.generated
     */
    public String getEb21Id() {
        return eb21Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kftc_withdraw.eb21_id
     *
     * @param eb21Id the value for kftc_withdraw.eb21_id
     *
     * @mbg.generated
     */
    public void setEb21Id(String eb21Id) {
        this.eb21Id = eb21Id == null ? null : eb21Id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kftc_withdraw.eb22_id
     *
     * @return the value of kftc_withdraw.eb22_id
     *
     * @mbg.generated
     */
    public String getEb22Id() {
        return eb22Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kftc_withdraw.eb22_id
     *
     * @param eb22Id the value for kftc_withdraw.eb22_id
     *
     * @mbg.generated
     */
    public void setEb22Id(String eb22Id) {
        this.eb22Id = eb22Id == null ? null : eb22Id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kftc_withdraw.data_no
     *
     * @return the value of kftc_withdraw.data_no
     *
     * @mbg.generated
     */
    public String getDataNo() {
        return dataNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kftc_withdraw.data_no
     *
     * @param dataNo the value for kftc_withdraw.data_no
     *
     * @mbg.generated
     */
    public void setDataNo(String dataNo) {
        this.dataNo = dataNo == null ? null : dataNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kftc_withdraw.payer_kftc_code
     *
     * @return the value of kftc_withdraw.payer_kftc_code
     *
     * @mbg.generated
     */
    public String getPayerKftcCode() {
        return payerKftcCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kftc_withdraw.payer_kftc_code
     *
     * @param payerKftcCode the value for kftc_withdraw.payer_kftc_code
     *
     * @mbg.generated
     */
    public void setPayerKftcCode(String payerKftcCode) {
        this.payerKftcCode = payerKftcCode == null ? null : payerKftcCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kftc_withdraw.payer_account_no
     *
     * @return the value of kftc_withdraw.payer_account_no
     *
     * @mbg.generated
     */
    public String getPayerAccountNo() {
        return payerAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kftc_withdraw.payer_account_no
     *
     * @param payerAccountNo the value for kftc_withdraw.payer_account_no
     *
     * @mbg.generated
     */
    public void setPayerAccountNo(String payerAccountNo) {
        this.payerAccountNo = payerAccountNo == null ? null : payerAccountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kftc_withdraw.amount
     *
     * @return the value of kftc_withdraw.amount
     *
     * @mbg.generated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kftc_withdraw.amount
     *
     * @param amount the value for kftc_withdraw.amount
     *
     * @mbg.generated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kftc_withdraw.payer_identity_no
     *
     * @return the value of kftc_withdraw.payer_identity_no
     *
     * @mbg.generated
     */
    public String getPayerIdentityNo() {
        return payerIdentityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kftc_withdraw.payer_identity_no
     *
     * @param payerIdentityNo the value for kftc_withdraw.payer_identity_no
     *
     * @mbg.generated
     */
    public void setPayerIdentityNo(String payerIdentityNo) {
        this.payerIdentityNo = payerIdentityNo == null ? null : payerIdentityNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kftc_withdraw.success_yn
     *
     * @return the value of kftc_withdraw.success_yn
     *
     * @mbg.generated
     */
    public String getSuccessYn() {
        return successYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kftc_withdraw.success_yn
     *
     * @param successYn the value for kftc_withdraw.success_yn
     *
     * @mbg.generated
     */
    public void setSuccessYn(String successYn) {
        this.successYn = successYn == null ? null : successYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kftc_withdraw.result_cd
     *
     * @return the value of kftc_withdraw.result_cd
     *
     * @mbg.generated
     */
    public String getResultCd() {
        return resultCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kftc_withdraw.result_cd
     *
     * @param resultCd the value for kftc_withdraw.result_cd
     *
     * @mbg.generated
     */
    public void setResultCd(String resultCd) {
        this.resultCd = resultCd == null ? null : resultCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kftc_withdraw.remark
     *
     * @return the value of kftc_withdraw.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kftc_withdraw.remark
     *
     * @param remark the value for kftc_withdraw.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kftc_withdraw.fund_type_cd
     *
     * @return the value of kftc_withdraw.fund_type_cd
     *
     * @mbg.generated
     */
    public String getFundTypeCd() {
        return fundTypeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kftc_withdraw.fund_type_cd
     *
     * @param fundTypeCd the value for kftc_withdraw.fund_type_cd
     *
     * @mbg.generated
     */
    public void setFundTypeCd(String fundTypeCd) {
        this.fundTypeCd = fundTypeCd == null ? null : fundTypeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kftc_withdraw.payer_no
     *
     * @return the value of kftc_withdraw.payer_no
     *
     * @mbg.generated
     */
    public String getPayerNo() {
        return payerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kftc_withdraw.payer_no
     *
     * @param payerNo the value for kftc_withdraw.payer_no
     *
     * @mbg.generated
     */
    public void setPayerNo(String payerNo) {
        this.payerNo = payerNo == null ? null : payerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kftc_withdraw.user_area
     *
     * @return the value of kftc_withdraw.user_area
     *
     * @mbg.generated
     */
    public String getUserArea() {
        return userArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kftc_withdraw.user_area
     *
     * @param userArea the value for kftc_withdraw.user_area
     *
     * @mbg.generated
     */
    public void setUserArea(String userArea) {
        this.userArea = userArea == null ? null : userArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kftc_withdraw.withdraw_type_cd
     *
     * @return the value of kftc_withdraw.withdraw_type_cd
     *
     * @mbg.generated
     */
    public String getWithdrawTypeCd() {
        return withdrawTypeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kftc_withdraw.withdraw_type_cd
     *
     * @param withdrawTypeCd the value for kftc_withdraw.withdraw_type_cd
     *
     * @mbg.generated
     */
    public void setWithdrawTypeCd(String withdrawTypeCd) {
        this.withdrawTypeCd = withdrawTypeCd == null ? null : withdrawTypeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kftc_withdraw.contact_no
     *
     * @return the value of kftc_withdraw.contact_no
     *
     * @mbg.generated
     */
    public String getContactNo() {
        return contactNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kftc_withdraw.contact_no
     *
     * @param contactNo the value for kftc_withdraw.contact_no
     *
     * @mbg.generated
     */
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo == null ? null : contactNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kftc_withdraw.create_date
     *
     * @return the value of kftc_withdraw.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kftc_withdraw.create_date
     *
     * @param createDate the value for kftc_withdraw.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kftc_withdraw.create_user
     *
     * @return the value of kftc_withdraw.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kftc_withdraw.create_user
     *
     * @param createUser the value for kftc_withdraw.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kftc_withdraw.status_cd
     *
     * @return the value of kftc_withdraw.status_cd
     *
     * @mbg.generated
     */
    public String getStatusCd() {
        return statusCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kftc_withdraw.status_cd
     *
     * @param statusCd the value for kftc_withdraw.status_cd
     *
     * @mbg.generated
     */
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd == null ? null : statusCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_withdraw
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        KftcWithdraw other = (KftcWithdraw) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getEb21Id() == null ? other.getEb21Id() == null : this.getEb21Id().equals(other.getEb21Id()))
            && (this.getEb22Id() == null ? other.getEb22Id() == null : this.getEb22Id().equals(other.getEb22Id()))
            && (this.getDataNo() == null ? other.getDataNo() == null : this.getDataNo().equals(other.getDataNo()))
            && (this.getPayerKftcCode() == null ? other.getPayerKftcCode() == null : this.getPayerKftcCode().equals(other.getPayerKftcCode()))
            && (this.getPayerAccountNo() == null ? other.getPayerAccountNo() == null : this.getPayerAccountNo().equals(other.getPayerAccountNo()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getPayerIdentityNo() == null ? other.getPayerIdentityNo() == null : this.getPayerIdentityNo().equals(other.getPayerIdentityNo()))
            && (this.getSuccessYn() == null ? other.getSuccessYn() == null : this.getSuccessYn().equals(other.getSuccessYn()))
            && (this.getResultCd() == null ? other.getResultCd() == null : this.getResultCd().equals(other.getResultCd()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getFundTypeCd() == null ? other.getFundTypeCd() == null : this.getFundTypeCd().equals(other.getFundTypeCd()))
            && (this.getPayerNo() == null ? other.getPayerNo() == null : this.getPayerNo().equals(other.getPayerNo()))
            && (this.getUserArea() == null ? other.getUserArea() == null : this.getUserArea().equals(other.getUserArea()))
            && (this.getWithdrawTypeCd() == null ? other.getWithdrawTypeCd() == null : this.getWithdrawTypeCd().equals(other.getWithdrawTypeCd()))
            && (this.getContactNo() == null ? other.getContactNo() == null : this.getContactNo().equals(other.getContactNo()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getStatusCd() == null ? other.getStatusCd() == null : this.getStatusCd().equals(other.getStatusCd()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_withdraw
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getEb21Id() == null) ? 0 : getEb21Id().hashCode());
        result = prime * result + ((getEb22Id() == null) ? 0 : getEb22Id().hashCode());
        result = prime * result + ((getDataNo() == null) ? 0 : getDataNo().hashCode());
        result = prime * result + ((getPayerKftcCode() == null) ? 0 : getPayerKftcCode().hashCode());
        result = prime * result + ((getPayerAccountNo() == null) ? 0 : getPayerAccountNo().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getPayerIdentityNo() == null) ? 0 : getPayerIdentityNo().hashCode());
        result = prime * result + ((getSuccessYn() == null) ? 0 : getSuccessYn().hashCode());
        result = prime * result + ((getResultCd() == null) ? 0 : getResultCd().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getFundTypeCd() == null) ? 0 : getFundTypeCd().hashCode());
        result = prime * result + ((getPayerNo() == null) ? 0 : getPayerNo().hashCode());
        result = prime * result + ((getUserArea() == null) ? 0 : getUserArea().hashCode());
        result = prime * result + ((getWithdrawTypeCd() == null) ? 0 : getWithdrawTypeCd().hashCode());
        result = prime * result + ((getContactNo() == null) ? 0 : getContactNo().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getStatusCd() == null) ? 0 : getStatusCd().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_withdraw
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", eb21Id=").append(eb21Id);
        sb.append(", eb22Id=").append(eb22Id);
        sb.append(", dataNo=").append(dataNo);
        sb.append(", payerKftcCode=").append(payerKftcCode);
        sb.append(", payerAccountNo=").append(payerAccountNo);
        sb.append(", amount=").append(amount);
        sb.append(", payerIdentityNo=").append(payerIdentityNo);
        sb.append(", successYn=").append(successYn);
        sb.append(", resultCd=").append(resultCd);
        sb.append(", remark=").append(remark);
        sb.append(", fundTypeCd=").append(fundTypeCd);
        sb.append(", payerNo=").append(payerNo);
        sb.append(", userArea=").append(userArea);
        sb.append(", withdrawTypeCd=").append(withdrawTypeCd);
        sb.append(", contactNo=").append(contactNo);
        sb.append(", createDate=").append(createDate);
        sb.append(", createUser=").append(createUser);
        sb.append(", statusCd=").append(statusCd);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}