package com.finger.shinhandamoa.data.table.model;

import java.io.Serializable;

public class Xdaysumrcp extends XdaysumrcpKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XDAYSUMRCP.RCPCNT
     *
     * @mbg.generated
     */
    private Integer rcpcnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XDAYSUMRCP.RCPAMT
     *
     * @mbg.generated
     */
    private Long rcpamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XDAYSUMRCP.RCPCNT
     *
     * @return the value of XDAYSUMRCP.RCPCNT
     *
     * @mbg.generated
     */
    public Integer getRcpcnt() {
        return rcpcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XDAYSUMRCP.RCPCNT
     *
     * @param rcpcnt the value for XDAYSUMRCP.RCPCNT
     *
     * @mbg.generated
     */
    public void setRcpcnt(Integer rcpcnt) {
        this.rcpcnt = rcpcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XDAYSUMRCP.RCPAMT
     *
     * @return the value of XDAYSUMRCP.RCPAMT
     *
     * @mbg.generated
     */
    public Long getRcpamt() {
        return rcpamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XDAYSUMRCP.RCPAMT
     *
     * @param rcpamt the value for XDAYSUMRCP.RCPAMT
     *
     * @mbg.generated
     */
    public void setRcpamt(Long rcpamt) {
        this.rcpamt = rcpamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Xdaysumrcp other = (Xdaysumrcp) that;
        return (this.getChacd() == null ? other.getChacd() == null : this.getChacd().equals(other.getChacd()))
            && (this.getRcpday() == null ? other.getRcpday() == null : this.getRcpday().equals(other.getRcpday()))
            && (this.getRcpcnt() == null ? other.getRcpcnt() == null : this.getRcpcnt().equals(other.getRcpcnt()))
            && (this.getRcpamt() == null ? other.getRcpamt() == null : this.getRcpamt().equals(other.getRcpamt()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getChacd() == null) ? 0 : getChacd().hashCode());
        result = prime * result + ((getRcpday() == null) ? 0 : getRcpday().hashCode());
        result = prime * result + ((getRcpcnt() == null) ? 0 : getRcpcnt().hashCode());
        result = prime * result + ((getRcpamt() == null) ? 0 : getRcpamt().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rcpcnt=").append(rcpcnt);
        sb.append(", rcpamt=").append(rcpamt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}