package com.finger.shinhandamoa.data.table.model;

import java.io.Serializable;

public class XdaysumnotiKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XDAYSUMNOTI.CHACD
     *
     * @mbg.generated
     */
    private String chacd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XDAYSUMNOTI.NOTIDAY
     *
     * @mbg.generated
     */
    private String notiday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table XDAYSUMNOTI
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XDAYSUMNOTI.CHACD
     *
     * @return the value of XDAYSUMNOTI.CHACD
     *
     * @mbg.generated
     */
    public String getChacd() {
        return chacd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XDAYSUMNOTI.CHACD
     *
     * @param chacd the value for XDAYSUMNOTI.CHACD
     *
     * @mbg.generated
     */
    public void setChacd(String chacd) {
        this.chacd = chacd == null ? null : chacd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XDAYSUMNOTI.NOTIDAY
     *
     * @return the value of XDAYSUMNOTI.NOTIDAY
     *
     * @mbg.generated
     */
    public String getNotiday() {
        return notiday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XDAYSUMNOTI.NOTIDAY
     *
     * @param notiday the value for XDAYSUMNOTI.NOTIDAY
     *
     * @mbg.generated
     */
    public void setNotiday(String notiday) {
        this.notiday = notiday == null ? null : notiday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMNOTI
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        XdaysumnotiKey other = (XdaysumnotiKey) that;
        return (this.getChacd() == null ? other.getChacd() == null : this.getChacd().equals(other.getChacd()))
            && (this.getNotiday() == null ? other.getNotiday() == null : this.getNotiday().equals(other.getNotiday()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMNOTI
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getChacd() == null) ? 0 : getChacd().hashCode());
        result = prime * result + ((getNotiday() == null) ? 0 : getNotiday().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMNOTI
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", chacd=").append(chacd);
        sb.append(", notiday=").append(notiday);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}