package com.finger.shinhandamoa.data.table.model;

import java.util.ArrayList;
import java.util.List;

public class XdaysumrcpExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    public XdaysumrcpExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andChacdIsNull() {
            addCriterion("CHACD is null");
            return (Criteria) this;
        }

        public Criteria andChacdIsNotNull() {
            addCriterion("CHACD is not null");
            return (Criteria) this;
        }

        public Criteria andChacdEqualTo(String value) {
            addCriterion("CHACD =", value, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdNotEqualTo(String value) {
            addCriterion("CHACD <>", value, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdGreaterThan(String value) {
            addCriterion("CHACD >", value, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdGreaterThanOrEqualTo(String value) {
            addCriterion("CHACD >=", value, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdLessThan(String value) {
            addCriterion("CHACD <", value, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdLessThanOrEqualTo(String value) {
            addCriterion("CHACD <=", value, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdLike(String value) {
            addCriterion("CHACD like", value, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdNotLike(String value) {
            addCriterion("CHACD not like", value, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdIn(List<String> values) {
            addCriterion("CHACD in", values, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdNotIn(List<String> values) {
            addCriterion("CHACD not in", values, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdBetween(String value1, String value2) {
            addCriterion("CHACD between", value1, value2, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdNotBetween(String value1, String value2) {
            addCriterion("CHACD not between", value1, value2, "chacd");
            return (Criteria) this;
        }

        public Criteria andRcpdayIsNull() {
            addCriterion("RCPDAY is null");
            return (Criteria) this;
        }

        public Criteria andRcpdayIsNotNull() {
            addCriterion("RCPDAY is not null");
            return (Criteria) this;
        }

        public Criteria andRcpdayEqualTo(String value) {
            addCriterion("RCPDAY =", value, "rcpday");
            return (Criteria) this;
        }

        public Criteria andRcpdayNotEqualTo(String value) {
            addCriterion("RCPDAY <>", value, "rcpday");
            return (Criteria) this;
        }

        public Criteria andRcpdayGreaterThan(String value) {
            addCriterion("RCPDAY >", value, "rcpday");
            return (Criteria) this;
        }

        public Criteria andRcpdayGreaterThanOrEqualTo(String value) {
            addCriterion("RCPDAY >=", value, "rcpday");
            return (Criteria) this;
        }

        public Criteria andRcpdayLessThan(String value) {
            addCriterion("RCPDAY <", value, "rcpday");
            return (Criteria) this;
        }

        public Criteria andRcpdayLessThanOrEqualTo(String value) {
            addCriterion("RCPDAY <=", value, "rcpday");
            return (Criteria) this;
        }

        public Criteria andRcpdayLike(String value) {
            addCriterion("RCPDAY like", value, "rcpday");
            return (Criteria) this;
        }

        public Criteria andRcpdayNotLike(String value) {
            addCriterion("RCPDAY not like", value, "rcpday");
            return (Criteria) this;
        }

        public Criteria andRcpdayIn(List<String> values) {
            addCriterion("RCPDAY in", values, "rcpday");
            return (Criteria) this;
        }

        public Criteria andRcpdayNotIn(List<String> values) {
            addCriterion("RCPDAY not in", values, "rcpday");
            return (Criteria) this;
        }

        public Criteria andRcpdayBetween(String value1, String value2) {
            addCriterion("RCPDAY between", value1, value2, "rcpday");
            return (Criteria) this;
        }

        public Criteria andRcpdayNotBetween(String value1, String value2) {
            addCriterion("RCPDAY not between", value1, value2, "rcpday");
            return (Criteria) this;
        }

        public Criteria andRcpcntIsNull() {
            addCriterion("RCPCNT is null");
            return (Criteria) this;
        }

        public Criteria andRcpcntIsNotNull() {
            addCriterion("RCPCNT is not null");
            return (Criteria) this;
        }

        public Criteria andRcpcntEqualTo(Integer value) {
            addCriterion("RCPCNT =", value, "rcpcnt");
            return (Criteria) this;
        }

        public Criteria andRcpcntNotEqualTo(Integer value) {
            addCriterion("RCPCNT <>", value, "rcpcnt");
            return (Criteria) this;
        }

        public Criteria andRcpcntGreaterThan(Integer value) {
            addCriterion("RCPCNT >", value, "rcpcnt");
            return (Criteria) this;
        }

        public Criteria andRcpcntGreaterThanOrEqualTo(Integer value) {
            addCriterion("RCPCNT >=", value, "rcpcnt");
            return (Criteria) this;
        }

        public Criteria andRcpcntLessThan(Integer value) {
            addCriterion("RCPCNT <", value, "rcpcnt");
            return (Criteria) this;
        }

        public Criteria andRcpcntLessThanOrEqualTo(Integer value) {
            addCriterion("RCPCNT <=", value, "rcpcnt");
            return (Criteria) this;
        }

        public Criteria andRcpcntIn(List<Integer> values) {
            addCriterion("RCPCNT in", values, "rcpcnt");
            return (Criteria) this;
        }

        public Criteria andRcpcntNotIn(List<Integer> values) {
            addCriterion("RCPCNT not in", values, "rcpcnt");
            return (Criteria) this;
        }

        public Criteria andRcpcntBetween(Integer value1, Integer value2) {
            addCriterion("RCPCNT between", value1, value2, "rcpcnt");
            return (Criteria) this;
        }

        public Criteria andRcpcntNotBetween(Integer value1, Integer value2) {
            addCriterion("RCPCNT not between", value1, value2, "rcpcnt");
            return (Criteria) this;
        }

        public Criteria andRcpamtIsNull() {
            addCriterion("RCPAMT is null");
            return (Criteria) this;
        }

        public Criteria andRcpamtIsNotNull() {
            addCriterion("RCPAMT is not null");
            return (Criteria) this;
        }

        public Criteria andRcpamtEqualTo(Long value) {
            addCriterion("RCPAMT =", value, "rcpamt");
            return (Criteria) this;
        }

        public Criteria andRcpamtNotEqualTo(Long value) {
            addCriterion("RCPAMT <>", value, "rcpamt");
            return (Criteria) this;
        }

        public Criteria andRcpamtGreaterThan(Long value) {
            addCriterion("RCPAMT >", value, "rcpamt");
            return (Criteria) this;
        }

        public Criteria andRcpamtGreaterThanOrEqualTo(Long value) {
            addCriterion("RCPAMT >=", value, "rcpamt");
            return (Criteria) this;
        }

        public Criteria andRcpamtLessThan(Long value) {
            addCriterion("RCPAMT <", value, "rcpamt");
            return (Criteria) this;
        }

        public Criteria andRcpamtLessThanOrEqualTo(Long value) {
            addCriterion("RCPAMT <=", value, "rcpamt");
            return (Criteria) this;
        }

        public Criteria andRcpamtIn(List<Long> values) {
            addCriterion("RCPAMT in", values, "rcpamt");
            return (Criteria) this;
        }

        public Criteria andRcpamtNotIn(List<Long> values) {
            addCriterion("RCPAMT not in", values, "rcpamt");
            return (Criteria) this;
        }

        public Criteria andRcpamtBetween(Long value1, Long value2) {
            addCriterion("RCPAMT between", value1, value2, "rcpamt");
            return (Criteria) this;
        }

        public Criteria andRcpamtNotBetween(Long value1, Long value2) {
            addCriterion("RCPAMT not between", value1, value2, "rcpamt");
            return (Criteria) this;
        }

        public Criteria andChacdLikeInsensitive(String value) {
            addCriterion("upper(CHACD) like", value.toUpperCase(), "chacd");
            return (Criteria) this;
        }

        public Criteria andRcpdayLikeInsensitive(String value) {
            addCriterion("upper(RCPDAY) like", value.toUpperCase(), "rcpday");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}