package com.finger.shinhandamoa.data.table.model;

import java.io.Serializable;

public class XdaysumKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xdaysum.chacd
     *
     * @mbg.generated
     */
    private String chacd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xdaysum.settle_dt
     *
     * @mbg.generated
     */
    private String settleDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xdaysum
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xdaysum.chacd
     *
     * @return the value of xdaysum.chacd
     *
     * @mbg.generated
     */
    public String getChacd() {
        return chacd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xdaysum.chacd
     *
     * @param chacd the value for xdaysum.chacd
     *
     * @mbg.generated
     */
    public void setChacd(String chacd) {
        this.chacd = chacd == null ? null : chacd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xdaysum.settle_dt
     *
     * @return the value of xdaysum.settle_dt
     *
     * @mbg.generated
     */
    public String getSettleDt() {
        return settleDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xdaysum.settle_dt
     *
     * @param settleDt the value for xdaysum.settle_dt
     *
     * @mbg.generated
     */
    public void setSettleDt(String settleDt) {
        this.settleDt = settleDt == null ? null : settleDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysum
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        XdaysumKey other = (XdaysumKey) that;
        return (this.getChacd() == null ? other.getChacd() == null : this.getChacd().equals(other.getChacd()))
            && (this.getSettleDt() == null ? other.getSettleDt() == null : this.getSettleDt().equals(other.getSettleDt()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysum
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getChacd() == null) ? 0 : getChacd().hashCode());
        result = prime * result + ((getSettleDt() == null) ? 0 : getSettleDt().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysum
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", chacd=").append(chacd);
        sb.append(", settleDt=").append(settleDt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}