package com.finger.shinhandamoa.data.table.model;

import java.io.Serializable;

public class XdaysumsmsKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XDAYSUMSMS.CHACD
     *
     * @mbg.generated
     */
    private String chacd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XDAYSUMSMS.SMSDAY
     *
     * @mbg.generated
     */
    private String smsday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table XDAYSUMSMS
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XDAYSUMSMS.CHACD
     *
     * @return the value of XDAYSUMSMS.CHACD
     *
     * @mbg.generated
     */
    public String getChacd() {
        return chacd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XDAYSUMSMS.CHACD
     *
     * @param chacd the value for XDAYSUMSMS.CHACD
     *
     * @mbg.generated
     */
    public void setChacd(String chacd) {
        this.chacd = chacd == null ? null : chacd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XDAYSUMSMS.SMSDAY
     *
     * @return the value of XDAYSUMSMS.SMSDAY
     *
     * @mbg.generated
     */
    public String getSmsday() {
        return smsday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XDAYSUMSMS.SMSDAY
     *
     * @param smsday the value for XDAYSUMSMS.SMSDAY
     *
     * @mbg.generated
     */
    public void setSmsday(String smsday) {
        this.smsday = smsday == null ? null : smsday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMSMS
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        XdaysumsmsKey other = (XdaysumsmsKey) that;
        return (this.getChacd() == null ? other.getChacd() == null : this.getChacd().equals(other.getChacd()))
            && (this.getSmsday() == null ? other.getSmsday() == null : this.getSmsday().equals(other.getSmsday()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMSMS
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getChacd() == null) ? 0 : getChacd().hashCode());
        result = prime * result + ((getSmsday() == null) ? 0 : getSmsday().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMSMS
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", chacd=").append(chacd);
        sb.append(", smsday=").append(smsday);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}