package com.finger.shinhandamoa.data.table.model;

import java.io.Serializable;

public class Xdaysumrcpetc extends XdaysumrcpetcKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XDAYSUMRCPETC.CMSCNT
     *
     * @mbg.generated
     */
    private Integer cmscnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XDAYSUMRCPETC.CMSAMT
     *
     * @mbg.generated
     */
    private Long cmsamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XDAYSUMRCPETC.DCDCNT
     *
     * @mbg.generated
     */
    private Integer dcdcnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XDAYSUMRCPETC.DCDAMT
     *
     * @mbg.generated
     */
    private Long dcdamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XDAYSUMRCPETC.DCSCNT
     *
     * @mbg.generated
     */
    private Integer dcscnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XDAYSUMRCPETC.DCSAMT
     *
     * @mbg.generated
     */
    private Long dcsamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XDAYSUMRCPETC.DVACNT
     *
     * @mbg.generated
     */
    private Integer dvacnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XDAYSUMRCPETC.DVAAMT
     *
     * @mbg.generated
     */
    private Long dvaamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XDAYSUMRCPETC.OCDCNT
     *
     * @mbg.generated
     */
    private Integer ocdcnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XDAYSUMRCPETC.OCDAMT
     *
     * @mbg.generated
     */
    private Long ocdamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table XDAYSUMRCPETC
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XDAYSUMRCPETC.CMSCNT
     *
     * @return the value of XDAYSUMRCPETC.CMSCNT
     *
     * @mbg.generated
     */
    public Integer getCmscnt() {
        return cmscnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XDAYSUMRCPETC.CMSCNT
     *
     * @param cmscnt the value for XDAYSUMRCPETC.CMSCNT
     *
     * @mbg.generated
     */
    public void setCmscnt(Integer cmscnt) {
        this.cmscnt = cmscnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XDAYSUMRCPETC.CMSAMT
     *
     * @return the value of XDAYSUMRCPETC.CMSAMT
     *
     * @mbg.generated
     */
    public Long getCmsamt() {
        return cmsamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XDAYSUMRCPETC.CMSAMT
     *
     * @param cmsamt the value for XDAYSUMRCPETC.CMSAMT
     *
     * @mbg.generated
     */
    public void setCmsamt(Long cmsamt) {
        this.cmsamt = cmsamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XDAYSUMRCPETC.DCDCNT
     *
     * @return the value of XDAYSUMRCPETC.DCDCNT
     *
     * @mbg.generated
     */
    public Integer getDcdcnt() {
        return dcdcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XDAYSUMRCPETC.DCDCNT
     *
     * @param dcdcnt the value for XDAYSUMRCPETC.DCDCNT
     *
     * @mbg.generated
     */
    public void setDcdcnt(Integer dcdcnt) {
        this.dcdcnt = dcdcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XDAYSUMRCPETC.DCDAMT
     *
     * @return the value of XDAYSUMRCPETC.DCDAMT
     *
     * @mbg.generated
     */
    public Long getDcdamt() {
        return dcdamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XDAYSUMRCPETC.DCDAMT
     *
     * @param dcdamt the value for XDAYSUMRCPETC.DCDAMT
     *
     * @mbg.generated
     */
    public void setDcdamt(Long dcdamt) {
        this.dcdamt = dcdamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XDAYSUMRCPETC.DCSCNT
     *
     * @return the value of XDAYSUMRCPETC.DCSCNT
     *
     * @mbg.generated
     */
    public Integer getDcscnt() {
        return dcscnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XDAYSUMRCPETC.DCSCNT
     *
     * @param dcscnt the value for XDAYSUMRCPETC.DCSCNT
     *
     * @mbg.generated
     */
    public void setDcscnt(Integer dcscnt) {
        this.dcscnt = dcscnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XDAYSUMRCPETC.DCSAMT
     *
     * @return the value of XDAYSUMRCPETC.DCSAMT
     *
     * @mbg.generated
     */
    public Long getDcsamt() {
        return dcsamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XDAYSUMRCPETC.DCSAMT
     *
     * @param dcsamt the value for XDAYSUMRCPETC.DCSAMT
     *
     * @mbg.generated
     */
    public void setDcsamt(Long dcsamt) {
        this.dcsamt = dcsamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XDAYSUMRCPETC.DVACNT
     *
     * @return the value of XDAYSUMRCPETC.DVACNT
     *
     * @mbg.generated
     */
    public Integer getDvacnt() {
        return dvacnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XDAYSUMRCPETC.DVACNT
     *
     * @param dvacnt the value for XDAYSUMRCPETC.DVACNT
     *
     * @mbg.generated
     */
    public void setDvacnt(Integer dvacnt) {
        this.dvacnt = dvacnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XDAYSUMRCPETC.DVAAMT
     *
     * @return the value of XDAYSUMRCPETC.DVAAMT
     *
     * @mbg.generated
     */
    public Long getDvaamt() {
        return dvaamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XDAYSUMRCPETC.DVAAMT
     *
     * @param dvaamt the value for XDAYSUMRCPETC.DVAAMT
     *
     * @mbg.generated
     */
    public void setDvaamt(Long dvaamt) {
        this.dvaamt = dvaamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XDAYSUMRCPETC.OCDCNT
     *
     * @return the value of XDAYSUMRCPETC.OCDCNT
     *
     * @mbg.generated
     */
    public Integer getOcdcnt() {
        return ocdcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XDAYSUMRCPETC.OCDCNT
     *
     * @param ocdcnt the value for XDAYSUMRCPETC.OCDCNT
     *
     * @mbg.generated
     */
    public void setOcdcnt(Integer ocdcnt) {
        this.ocdcnt = ocdcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XDAYSUMRCPETC.OCDAMT
     *
     * @return the value of XDAYSUMRCPETC.OCDAMT
     *
     * @mbg.generated
     */
    public Long getOcdamt() {
        return ocdamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XDAYSUMRCPETC.OCDAMT
     *
     * @param ocdamt the value for XDAYSUMRCPETC.OCDAMT
     *
     * @mbg.generated
     */
    public void setOcdamt(Long ocdamt) {
        this.ocdamt = ocdamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCPETC
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Xdaysumrcpetc other = (Xdaysumrcpetc) that;
        return (this.getChacd() == null ? other.getChacd() == null : this.getChacd().equals(other.getChacd()))
            && (this.getRcpday() == null ? other.getRcpday() == null : this.getRcpday().equals(other.getRcpday()))
            && (this.getCmscnt() == null ? other.getCmscnt() == null : this.getCmscnt().equals(other.getCmscnt()))
            && (this.getCmsamt() == null ? other.getCmsamt() == null : this.getCmsamt().equals(other.getCmsamt()))
            && (this.getDcdcnt() == null ? other.getDcdcnt() == null : this.getDcdcnt().equals(other.getDcdcnt()))
            && (this.getDcdamt() == null ? other.getDcdamt() == null : this.getDcdamt().equals(other.getDcdamt()))
            && (this.getDcscnt() == null ? other.getDcscnt() == null : this.getDcscnt().equals(other.getDcscnt()))
            && (this.getDcsamt() == null ? other.getDcsamt() == null : this.getDcsamt().equals(other.getDcsamt()))
            && (this.getDvacnt() == null ? other.getDvacnt() == null : this.getDvacnt().equals(other.getDvacnt()))
            && (this.getDvaamt() == null ? other.getDvaamt() == null : this.getDvaamt().equals(other.getDvaamt()))
            && (this.getOcdcnt() == null ? other.getOcdcnt() == null : this.getOcdcnt().equals(other.getOcdcnt()))
            && (this.getOcdamt() == null ? other.getOcdamt() == null : this.getOcdamt().equals(other.getOcdamt()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCPETC
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getChacd() == null) ? 0 : getChacd().hashCode());
        result = prime * result + ((getRcpday() == null) ? 0 : getRcpday().hashCode());
        result = prime * result + ((getCmscnt() == null) ? 0 : getCmscnt().hashCode());
        result = prime * result + ((getCmsamt() == null) ? 0 : getCmsamt().hashCode());
        result = prime * result + ((getDcdcnt() == null) ? 0 : getDcdcnt().hashCode());
        result = prime * result + ((getDcdamt() == null) ? 0 : getDcdamt().hashCode());
        result = prime * result + ((getDcscnt() == null) ? 0 : getDcscnt().hashCode());
        result = prime * result + ((getDcsamt() == null) ? 0 : getDcsamt().hashCode());
        result = prime * result + ((getDvacnt() == null) ? 0 : getDvacnt().hashCode());
        result = prime * result + ((getDvaamt() == null) ? 0 : getDvaamt().hashCode());
        result = prime * result + ((getOcdcnt() == null) ? 0 : getOcdcnt().hashCode());
        result = prime * result + ((getOcdamt() == null) ? 0 : getOcdamt().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCPETC
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cmscnt=").append(cmscnt);
        sb.append(", cmsamt=").append(cmsamt);
        sb.append(", dcdcnt=").append(dcdcnt);
        sb.append(", dcdamt=").append(dcdamt);
        sb.append(", dcscnt=").append(dcscnt);
        sb.append(", dcsamt=").append(dcsamt);
        sb.append(", dvacnt=").append(dvacnt);
        sb.append(", dvaamt=").append(dvaamt);
        sb.append(", ocdcnt=").append(ocdcnt);
        sb.append(", ocdamt=").append(ocdamt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}