package kr.co.finger.shinhandamoa.data.table.model;

import java.io.Serializable;
import java.util.Date;

public class DamoaClientInfoPullHist extends DamoaClientInfoPullHistKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.client_name
     *
     * @mbg.generated
     */
    private String clientName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.client_delete_yn
     *
     * @mbg.generated
     */
    private String clientDeleteYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.relay_client_id
     *
     * @mbg.generated
     */
    private String relayClientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.rgst_dt
     *
     * @mbg.generated
     */
    private String rgstDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.client_id_no
     *
     * @mbg.generated
     */
    private String clientIdNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.client_status
     *
     * @mbg.generated
     */
    private String clientStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency1_code
     *
     * @mbg.generated
     */
    private String agency1Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency1_name
     *
     * @mbg.generated
     */
    private String agency1Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency1_status
     *
     * @mbg.generated
     */
    private String agency1Status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency2_code
     *
     * @mbg.generated
     */
    private String agency2Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency2_name
     *
     * @mbg.generated
     */
    private String agency2Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency2_status
     *
     * @mbg.generated
     */
    private String agency2Status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency3_code
     *
     * @mbg.generated
     */
    private String agency3Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency3_name
     *
     * @mbg.generated
     */
    private String agency3Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency3_status
     *
     * @mbg.generated
     */
    private String agency3Status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency4_code
     *
     * @mbg.generated
     */
    private String agency4Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency4_name
     *
     * @mbg.generated
     */
    private String agency4Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency4_status
     *
     * @mbg.generated
     */
    private String agency4Status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency5_code
     *
     * @mbg.generated
     */
    private String agency5Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency5_name
     *
     * @mbg.generated
     */
    private String agency5Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency5_status
     *
     * @mbg.generated
     */
    private String agency5Status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency6_code
     *
     * @mbg.generated
     */
    private String agency6Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency6_name
     *
     * @mbg.generated
     */
    private String agency6Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency6_status
     *
     * @mbg.generated
     */
    private String agency6Status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency7_code
     *
     * @mbg.generated
     */
    private String agency7Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency7_name
     *
     * @mbg.generated
     */
    private String agency7Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency7_status
     *
     * @mbg.generated
     */
    private String agency7Status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency8_code
     *
     * @mbg.generated
     */
    private String agency8Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency8_name
     *
     * @mbg.generated
     */
    private String agency8Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency8_status
     *
     * @mbg.generated
     */
    private String agency8Status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency9_code
     *
     * @mbg.generated
     */
    private String agency9Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency9_name
     *
     * @mbg.generated
     */
    private String agency9Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency9_status
     *
     * @mbg.generated
     */
    private String agency9Status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency10_code
     *
     * @mbg.generated
     */
    private String agency10Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency10_name
     *
     * @mbg.generated
     */
    private String agency10Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.agency10_status
     *
     * @mbg.generated
     */
    private String agency10Status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.payment_fee_amt
     *
     * @mbg.generated
     */
    private Integer paymentFeeAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.finger_fee_rate
     *
     * @mbg.generated
     */
    private Integer fingerFeeRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.brch_code
     *
     * @mbg.generated
     */
    private String brchCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.status_cd
     *
     * @mbg.generated
     */
    private String statusCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.modify_date
     *
     * @mbg.generated
     */
    private Date modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.modify_user
     *
     * @mbg.generated
     */
    private String modifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.type_cd
     *
     * @mbg.generated
     */
    private String typeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.asis_client_name
     *
     * @mbg.generated
     */
    private String asisClientName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.asis_client_id_no
     *
     * @mbg.generated
     */
    private String asisClientIdNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.asis_client_status
     *
     * @mbg.generated
     */
    private String asisClientStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.asis_agency1_code
     *
     * @mbg.generated
     */
    private String asisAgency1Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.asis_agency1_name
     *
     * @mbg.generated
     */
    private String asisAgency1Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.asis_agency2_code
     *
     * @mbg.generated
     */
    private String asisAgency2Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.asis_agency2_name
     *
     * @mbg.generated
     */
    private String asisAgency2Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.asis_agency3_code
     *
     * @mbg.generated
     */
    private String asisAgency3Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.asis_agency3_name
     *
     * @mbg.generated
     */
    private String asisAgency3Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.asis_agency4_code
     *
     * @mbg.generated
     */
    private String asisAgency4Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.asis_agency4_name
     *
     * @mbg.generated
     */
    private String asisAgency4Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.asis_agency5_code
     *
     * @mbg.generated
     */
    private String asisAgency5Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.asis_agency5_name
     *
     * @mbg.generated
     */
    private String asisAgency5Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.asis_agency6_code
     *
     * @mbg.generated
     */
    private String asisAgency6Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.asis_agency6_name
     *
     * @mbg.generated
     */
    private String asisAgency6Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.asis_agency7_code
     *
     * @mbg.generated
     */
    private String asisAgency7Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.asis_agency7_name
     *
     * @mbg.generated
     */
    private String asisAgency7Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.asis_agency8_code
     *
     * @mbg.generated
     */
    private String asisAgency8Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.asis_agency8_name
     *
     * @mbg.generated
     */
    private String asisAgency8Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.asis_agency9_code
     *
     * @mbg.generated
     */
    private String asisAgency9Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.asis_agency9_name
     *
     * @mbg.generated
     */
    private String asisAgency9Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.asis_agency10_code
     *
     * @mbg.generated
     */
    private String asisAgency10Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.asis_agency10_name
     *
     * @mbg.generated
     */
    private String asisAgency10Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.asis_payment_fee_amt
     *
     * @mbg.generated
     */
    private Integer asisPaymentFeeAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.asis_finger_fee_rate
     *
     * @mbg.generated
     */
    private Integer asisFingerFeeRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.asis_brch_code
     *
     * @mbg.generated
     */
    private String asisBrchCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table damoa_client_info_pull_hist
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.client_name
     *
     * @return the value of damoa_client_info_pull_hist.client_name
     *
     * @mbg.generated
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.client_name
     *
     * @param clientName the value for damoa_client_info_pull_hist.client_name
     *
     * @mbg.generated
     */
    public void setClientName(String clientName) {
        this.clientName = clientName == null ? null : clientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.client_delete_yn
     *
     * @return the value of damoa_client_info_pull_hist.client_delete_yn
     *
     * @mbg.generated
     */
    public String getClientDeleteYn() {
        return clientDeleteYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.client_delete_yn
     *
     * @param clientDeleteYn the value for damoa_client_info_pull_hist.client_delete_yn
     *
     * @mbg.generated
     */
    public void setClientDeleteYn(String clientDeleteYn) {
        this.clientDeleteYn = clientDeleteYn == null ? null : clientDeleteYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.relay_client_id
     *
     * @return the value of damoa_client_info_pull_hist.relay_client_id
     *
     * @mbg.generated
     */
    public String getRelayClientId() {
        return relayClientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.relay_client_id
     *
     * @param relayClientId the value for damoa_client_info_pull_hist.relay_client_id
     *
     * @mbg.generated
     */
    public void setRelayClientId(String relayClientId) {
        this.relayClientId = relayClientId == null ? null : relayClientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.rgst_dt
     *
     * @return the value of damoa_client_info_pull_hist.rgst_dt
     *
     * @mbg.generated
     */
    public String getRgstDt() {
        return rgstDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.rgst_dt
     *
     * @param rgstDt the value for damoa_client_info_pull_hist.rgst_dt
     *
     * @mbg.generated
     */
    public void setRgstDt(String rgstDt) {
        this.rgstDt = rgstDt == null ? null : rgstDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.client_id_no
     *
     * @return the value of damoa_client_info_pull_hist.client_id_no
     *
     * @mbg.generated
     */
    public String getClientIdNo() {
        return clientIdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.client_id_no
     *
     * @param clientIdNo the value for damoa_client_info_pull_hist.client_id_no
     *
     * @mbg.generated
     */
    public void setClientIdNo(String clientIdNo) {
        this.clientIdNo = clientIdNo == null ? null : clientIdNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.client_status
     *
     * @return the value of damoa_client_info_pull_hist.client_status
     *
     * @mbg.generated
     */
    public String getClientStatus() {
        return clientStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.client_status
     *
     * @param clientStatus the value for damoa_client_info_pull_hist.client_status
     *
     * @mbg.generated
     */
    public void setClientStatus(String clientStatus) {
        this.clientStatus = clientStatus == null ? null : clientStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency1_code
     *
     * @return the value of damoa_client_info_pull_hist.agency1_code
     *
     * @mbg.generated
     */
    public String getAgency1Code() {
        return agency1Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency1_code
     *
     * @param agency1Code the value for damoa_client_info_pull_hist.agency1_code
     *
     * @mbg.generated
     */
    public void setAgency1Code(String agency1Code) {
        this.agency1Code = agency1Code == null ? null : agency1Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency1_name
     *
     * @return the value of damoa_client_info_pull_hist.agency1_name
     *
     * @mbg.generated
     */
    public String getAgency1Name() {
        return agency1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency1_name
     *
     * @param agency1Name the value for damoa_client_info_pull_hist.agency1_name
     *
     * @mbg.generated
     */
    public void setAgency1Name(String agency1Name) {
        this.agency1Name = agency1Name == null ? null : agency1Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency1_status
     *
     * @return the value of damoa_client_info_pull_hist.agency1_status
     *
     * @mbg.generated
     */
    public String getAgency1Status() {
        return agency1Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency1_status
     *
     * @param agency1Status the value for damoa_client_info_pull_hist.agency1_status
     *
     * @mbg.generated
     */
    public void setAgency1Status(String agency1Status) {
        this.agency1Status = agency1Status == null ? null : agency1Status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency2_code
     *
     * @return the value of damoa_client_info_pull_hist.agency2_code
     *
     * @mbg.generated
     */
    public String getAgency2Code() {
        return agency2Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency2_code
     *
     * @param agency2Code the value for damoa_client_info_pull_hist.agency2_code
     *
     * @mbg.generated
     */
    public void setAgency2Code(String agency2Code) {
        this.agency2Code = agency2Code == null ? null : agency2Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency2_name
     *
     * @return the value of damoa_client_info_pull_hist.agency2_name
     *
     * @mbg.generated
     */
    public String getAgency2Name() {
        return agency2Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency2_name
     *
     * @param agency2Name the value for damoa_client_info_pull_hist.agency2_name
     *
     * @mbg.generated
     */
    public void setAgency2Name(String agency2Name) {
        this.agency2Name = agency2Name == null ? null : agency2Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency2_status
     *
     * @return the value of damoa_client_info_pull_hist.agency2_status
     *
     * @mbg.generated
     */
    public String getAgency2Status() {
        return agency2Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency2_status
     *
     * @param agency2Status the value for damoa_client_info_pull_hist.agency2_status
     *
     * @mbg.generated
     */
    public void setAgency2Status(String agency2Status) {
        this.agency2Status = agency2Status == null ? null : agency2Status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency3_code
     *
     * @return the value of damoa_client_info_pull_hist.agency3_code
     *
     * @mbg.generated
     */
    public String getAgency3Code() {
        return agency3Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency3_code
     *
     * @param agency3Code the value for damoa_client_info_pull_hist.agency3_code
     *
     * @mbg.generated
     */
    public void setAgency3Code(String agency3Code) {
        this.agency3Code = agency3Code == null ? null : agency3Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency3_name
     *
     * @return the value of damoa_client_info_pull_hist.agency3_name
     *
     * @mbg.generated
     */
    public String getAgency3Name() {
        return agency3Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency3_name
     *
     * @param agency3Name the value for damoa_client_info_pull_hist.agency3_name
     *
     * @mbg.generated
     */
    public void setAgency3Name(String agency3Name) {
        this.agency3Name = agency3Name == null ? null : agency3Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency3_status
     *
     * @return the value of damoa_client_info_pull_hist.agency3_status
     *
     * @mbg.generated
     */
    public String getAgency3Status() {
        return agency3Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency3_status
     *
     * @param agency3Status the value for damoa_client_info_pull_hist.agency3_status
     *
     * @mbg.generated
     */
    public void setAgency3Status(String agency3Status) {
        this.agency3Status = agency3Status == null ? null : agency3Status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency4_code
     *
     * @return the value of damoa_client_info_pull_hist.agency4_code
     *
     * @mbg.generated
     */
    public String getAgency4Code() {
        return agency4Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency4_code
     *
     * @param agency4Code the value for damoa_client_info_pull_hist.agency4_code
     *
     * @mbg.generated
     */
    public void setAgency4Code(String agency4Code) {
        this.agency4Code = agency4Code == null ? null : agency4Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency4_name
     *
     * @return the value of damoa_client_info_pull_hist.agency4_name
     *
     * @mbg.generated
     */
    public String getAgency4Name() {
        return agency4Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency4_name
     *
     * @param agency4Name the value for damoa_client_info_pull_hist.agency4_name
     *
     * @mbg.generated
     */
    public void setAgency4Name(String agency4Name) {
        this.agency4Name = agency4Name == null ? null : agency4Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency4_status
     *
     * @return the value of damoa_client_info_pull_hist.agency4_status
     *
     * @mbg.generated
     */
    public String getAgency4Status() {
        return agency4Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency4_status
     *
     * @param agency4Status the value for damoa_client_info_pull_hist.agency4_status
     *
     * @mbg.generated
     */
    public void setAgency4Status(String agency4Status) {
        this.agency4Status = agency4Status == null ? null : agency4Status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency5_code
     *
     * @return the value of damoa_client_info_pull_hist.agency5_code
     *
     * @mbg.generated
     */
    public String getAgency5Code() {
        return agency5Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency5_code
     *
     * @param agency5Code the value for damoa_client_info_pull_hist.agency5_code
     *
     * @mbg.generated
     */
    public void setAgency5Code(String agency5Code) {
        this.agency5Code = agency5Code == null ? null : agency5Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency5_name
     *
     * @return the value of damoa_client_info_pull_hist.agency5_name
     *
     * @mbg.generated
     */
    public String getAgency5Name() {
        return agency5Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency5_name
     *
     * @param agency5Name the value for damoa_client_info_pull_hist.agency5_name
     *
     * @mbg.generated
     */
    public void setAgency5Name(String agency5Name) {
        this.agency5Name = agency5Name == null ? null : agency5Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency5_status
     *
     * @return the value of damoa_client_info_pull_hist.agency5_status
     *
     * @mbg.generated
     */
    public String getAgency5Status() {
        return agency5Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency5_status
     *
     * @param agency5Status the value for damoa_client_info_pull_hist.agency5_status
     *
     * @mbg.generated
     */
    public void setAgency5Status(String agency5Status) {
        this.agency5Status = agency5Status == null ? null : agency5Status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency6_code
     *
     * @return the value of damoa_client_info_pull_hist.agency6_code
     *
     * @mbg.generated
     */
    public String getAgency6Code() {
        return agency6Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency6_code
     *
     * @param agency6Code the value for damoa_client_info_pull_hist.agency6_code
     *
     * @mbg.generated
     */
    public void setAgency6Code(String agency6Code) {
        this.agency6Code = agency6Code == null ? null : agency6Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency6_name
     *
     * @return the value of damoa_client_info_pull_hist.agency6_name
     *
     * @mbg.generated
     */
    public String getAgency6Name() {
        return agency6Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency6_name
     *
     * @param agency6Name the value for damoa_client_info_pull_hist.agency6_name
     *
     * @mbg.generated
     */
    public void setAgency6Name(String agency6Name) {
        this.agency6Name = agency6Name == null ? null : agency6Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency6_status
     *
     * @return the value of damoa_client_info_pull_hist.agency6_status
     *
     * @mbg.generated
     */
    public String getAgency6Status() {
        return agency6Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency6_status
     *
     * @param agency6Status the value for damoa_client_info_pull_hist.agency6_status
     *
     * @mbg.generated
     */
    public void setAgency6Status(String agency6Status) {
        this.agency6Status = agency6Status == null ? null : agency6Status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency7_code
     *
     * @return the value of damoa_client_info_pull_hist.agency7_code
     *
     * @mbg.generated
     */
    public String getAgency7Code() {
        return agency7Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency7_code
     *
     * @param agency7Code the value for damoa_client_info_pull_hist.agency7_code
     *
     * @mbg.generated
     */
    public void setAgency7Code(String agency7Code) {
        this.agency7Code = agency7Code == null ? null : agency7Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency7_name
     *
     * @return the value of damoa_client_info_pull_hist.agency7_name
     *
     * @mbg.generated
     */
    public String getAgency7Name() {
        return agency7Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency7_name
     *
     * @param agency7Name the value for damoa_client_info_pull_hist.agency7_name
     *
     * @mbg.generated
     */
    public void setAgency7Name(String agency7Name) {
        this.agency7Name = agency7Name == null ? null : agency7Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency7_status
     *
     * @return the value of damoa_client_info_pull_hist.agency7_status
     *
     * @mbg.generated
     */
    public String getAgency7Status() {
        return agency7Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency7_status
     *
     * @param agency7Status the value for damoa_client_info_pull_hist.agency7_status
     *
     * @mbg.generated
     */
    public void setAgency7Status(String agency7Status) {
        this.agency7Status = agency7Status == null ? null : agency7Status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency8_code
     *
     * @return the value of damoa_client_info_pull_hist.agency8_code
     *
     * @mbg.generated
     */
    public String getAgency8Code() {
        return agency8Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency8_code
     *
     * @param agency8Code the value for damoa_client_info_pull_hist.agency8_code
     *
     * @mbg.generated
     */
    public void setAgency8Code(String agency8Code) {
        this.agency8Code = agency8Code == null ? null : agency8Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency8_name
     *
     * @return the value of damoa_client_info_pull_hist.agency8_name
     *
     * @mbg.generated
     */
    public String getAgency8Name() {
        return agency8Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency8_name
     *
     * @param agency8Name the value for damoa_client_info_pull_hist.agency8_name
     *
     * @mbg.generated
     */
    public void setAgency8Name(String agency8Name) {
        this.agency8Name = agency8Name == null ? null : agency8Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency8_status
     *
     * @return the value of damoa_client_info_pull_hist.agency8_status
     *
     * @mbg.generated
     */
    public String getAgency8Status() {
        return agency8Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency8_status
     *
     * @param agency8Status the value for damoa_client_info_pull_hist.agency8_status
     *
     * @mbg.generated
     */
    public void setAgency8Status(String agency8Status) {
        this.agency8Status = agency8Status == null ? null : agency8Status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency9_code
     *
     * @return the value of damoa_client_info_pull_hist.agency9_code
     *
     * @mbg.generated
     */
    public String getAgency9Code() {
        return agency9Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency9_code
     *
     * @param agency9Code the value for damoa_client_info_pull_hist.agency9_code
     *
     * @mbg.generated
     */
    public void setAgency9Code(String agency9Code) {
        this.agency9Code = agency9Code == null ? null : agency9Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency9_name
     *
     * @return the value of damoa_client_info_pull_hist.agency9_name
     *
     * @mbg.generated
     */
    public String getAgency9Name() {
        return agency9Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency9_name
     *
     * @param agency9Name the value for damoa_client_info_pull_hist.agency9_name
     *
     * @mbg.generated
     */
    public void setAgency9Name(String agency9Name) {
        this.agency9Name = agency9Name == null ? null : agency9Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency9_status
     *
     * @return the value of damoa_client_info_pull_hist.agency9_status
     *
     * @mbg.generated
     */
    public String getAgency9Status() {
        return agency9Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency9_status
     *
     * @param agency9Status the value for damoa_client_info_pull_hist.agency9_status
     *
     * @mbg.generated
     */
    public void setAgency9Status(String agency9Status) {
        this.agency9Status = agency9Status == null ? null : agency9Status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency10_code
     *
     * @return the value of damoa_client_info_pull_hist.agency10_code
     *
     * @mbg.generated
     */
    public String getAgency10Code() {
        return agency10Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency10_code
     *
     * @param agency10Code the value for damoa_client_info_pull_hist.agency10_code
     *
     * @mbg.generated
     */
    public void setAgency10Code(String agency10Code) {
        this.agency10Code = agency10Code == null ? null : agency10Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency10_name
     *
     * @return the value of damoa_client_info_pull_hist.agency10_name
     *
     * @mbg.generated
     */
    public String getAgency10Name() {
        return agency10Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency10_name
     *
     * @param agency10Name the value for damoa_client_info_pull_hist.agency10_name
     *
     * @mbg.generated
     */
    public void setAgency10Name(String agency10Name) {
        this.agency10Name = agency10Name == null ? null : agency10Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.agency10_status
     *
     * @return the value of damoa_client_info_pull_hist.agency10_status
     *
     * @mbg.generated
     */
    public String getAgency10Status() {
        return agency10Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.agency10_status
     *
     * @param agency10Status the value for damoa_client_info_pull_hist.agency10_status
     *
     * @mbg.generated
     */
    public void setAgency10Status(String agency10Status) {
        this.agency10Status = agency10Status == null ? null : agency10Status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.payment_fee_amt
     *
     * @return the value of damoa_client_info_pull_hist.payment_fee_amt
     *
     * @mbg.generated
     */
    public Integer getPaymentFeeAmt() {
        return paymentFeeAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.payment_fee_amt
     *
     * @param paymentFeeAmt the value for damoa_client_info_pull_hist.payment_fee_amt
     *
     * @mbg.generated
     */
    public void setPaymentFeeAmt(Integer paymentFeeAmt) {
        this.paymentFeeAmt = paymentFeeAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.finger_fee_rate
     *
     * @return the value of damoa_client_info_pull_hist.finger_fee_rate
     *
     * @mbg.generated
     */
    public Integer getFingerFeeRate() {
        return fingerFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.finger_fee_rate
     *
     * @param fingerFeeRate the value for damoa_client_info_pull_hist.finger_fee_rate
     *
     * @mbg.generated
     */
    public void setFingerFeeRate(Integer fingerFeeRate) {
        this.fingerFeeRate = fingerFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.brch_code
     *
     * @return the value of damoa_client_info_pull_hist.brch_code
     *
     * @mbg.generated
     */
    public String getBrchCode() {
        return brchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.brch_code
     *
     * @param brchCode the value for damoa_client_info_pull_hist.brch_code
     *
     * @mbg.generated
     */
    public void setBrchCode(String brchCode) {
        this.brchCode = brchCode == null ? null : brchCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.status_cd
     *
     * @return the value of damoa_client_info_pull_hist.status_cd
     *
     * @mbg.generated
     */
    public String getStatusCd() {
        return statusCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.status_cd
     *
     * @param statusCd the value for damoa_client_info_pull_hist.status_cd
     *
     * @mbg.generated
     */
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd == null ? null : statusCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.create_date
     *
     * @return the value of damoa_client_info_pull_hist.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.create_date
     *
     * @param createDate the value for damoa_client_info_pull_hist.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.create_user
     *
     * @return the value of damoa_client_info_pull_hist.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.create_user
     *
     * @param createUser the value for damoa_client_info_pull_hist.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.modify_date
     *
     * @return the value of damoa_client_info_pull_hist.modify_date
     *
     * @mbg.generated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.modify_date
     *
     * @param modifyDate the value for damoa_client_info_pull_hist.modify_date
     *
     * @mbg.generated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.modify_user
     *
     * @return the value of damoa_client_info_pull_hist.modify_user
     *
     * @mbg.generated
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.modify_user
     *
     * @param modifyUser the value for damoa_client_info_pull_hist.modify_user
     *
     * @mbg.generated
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.type_cd
     *
     * @return the value of damoa_client_info_pull_hist.type_cd
     *
     * @mbg.generated
     */
    public String getTypeCd() {
        return typeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.type_cd
     *
     * @param typeCd the value for damoa_client_info_pull_hist.type_cd
     *
     * @mbg.generated
     */
    public void setTypeCd(String typeCd) {
        this.typeCd = typeCd == null ? null : typeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.asis_client_name
     *
     * @return the value of damoa_client_info_pull_hist.asis_client_name
     *
     * @mbg.generated
     */
    public String getAsisClientName() {
        return asisClientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.asis_client_name
     *
     * @param asisClientName the value for damoa_client_info_pull_hist.asis_client_name
     *
     * @mbg.generated
     */
    public void setAsisClientName(String asisClientName) {
        this.asisClientName = asisClientName == null ? null : asisClientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.asis_client_id_no
     *
     * @return the value of damoa_client_info_pull_hist.asis_client_id_no
     *
     * @mbg.generated
     */
    public String getAsisClientIdNo() {
        return asisClientIdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.asis_client_id_no
     *
     * @param asisClientIdNo the value for damoa_client_info_pull_hist.asis_client_id_no
     *
     * @mbg.generated
     */
    public void setAsisClientIdNo(String asisClientIdNo) {
        this.asisClientIdNo = asisClientIdNo == null ? null : asisClientIdNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.asis_client_status
     *
     * @return the value of damoa_client_info_pull_hist.asis_client_status
     *
     * @mbg.generated
     */
    public String getAsisClientStatus() {
        return asisClientStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.asis_client_status
     *
     * @param asisClientStatus the value for damoa_client_info_pull_hist.asis_client_status
     *
     * @mbg.generated
     */
    public void setAsisClientStatus(String asisClientStatus) {
        this.asisClientStatus = asisClientStatus == null ? null : asisClientStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.asis_agency1_code
     *
     * @return the value of damoa_client_info_pull_hist.asis_agency1_code
     *
     * @mbg.generated
     */
    public String getAsisAgency1Code() {
        return asisAgency1Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.asis_agency1_code
     *
     * @param asisAgency1Code the value for damoa_client_info_pull_hist.asis_agency1_code
     *
     * @mbg.generated
     */
    public void setAsisAgency1Code(String asisAgency1Code) {
        this.asisAgency1Code = asisAgency1Code == null ? null : asisAgency1Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.asis_agency1_name
     *
     * @return the value of damoa_client_info_pull_hist.asis_agency1_name
     *
     * @mbg.generated
     */
    public String getAsisAgency1Name() {
        return asisAgency1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.asis_agency1_name
     *
     * @param asisAgency1Name the value for damoa_client_info_pull_hist.asis_agency1_name
     *
     * @mbg.generated
     */
    public void setAsisAgency1Name(String asisAgency1Name) {
        this.asisAgency1Name = asisAgency1Name == null ? null : asisAgency1Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.asis_agency2_code
     *
     * @return the value of damoa_client_info_pull_hist.asis_agency2_code
     *
     * @mbg.generated
     */
    public String getAsisAgency2Code() {
        return asisAgency2Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.asis_agency2_code
     *
     * @param asisAgency2Code the value for damoa_client_info_pull_hist.asis_agency2_code
     *
     * @mbg.generated
     */
    public void setAsisAgency2Code(String asisAgency2Code) {
        this.asisAgency2Code = asisAgency2Code == null ? null : asisAgency2Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.asis_agency2_name
     *
     * @return the value of damoa_client_info_pull_hist.asis_agency2_name
     *
     * @mbg.generated
     */
    public String getAsisAgency2Name() {
        return asisAgency2Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.asis_agency2_name
     *
     * @param asisAgency2Name the value for damoa_client_info_pull_hist.asis_agency2_name
     *
     * @mbg.generated
     */
    public void setAsisAgency2Name(String asisAgency2Name) {
        this.asisAgency2Name = asisAgency2Name == null ? null : asisAgency2Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.asis_agency3_code
     *
     * @return the value of damoa_client_info_pull_hist.asis_agency3_code
     *
     * @mbg.generated
     */
    public String getAsisAgency3Code() {
        return asisAgency3Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.asis_agency3_code
     *
     * @param asisAgency3Code the value for damoa_client_info_pull_hist.asis_agency3_code
     *
     * @mbg.generated
     */
    public void setAsisAgency3Code(String asisAgency3Code) {
        this.asisAgency3Code = asisAgency3Code == null ? null : asisAgency3Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.asis_agency3_name
     *
     * @return the value of damoa_client_info_pull_hist.asis_agency3_name
     *
     * @mbg.generated
     */
    public String getAsisAgency3Name() {
        return asisAgency3Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.asis_agency3_name
     *
     * @param asisAgency3Name the value for damoa_client_info_pull_hist.asis_agency3_name
     *
     * @mbg.generated
     */
    public void setAsisAgency3Name(String asisAgency3Name) {
        this.asisAgency3Name = asisAgency3Name == null ? null : asisAgency3Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.asis_agency4_code
     *
     * @return the value of damoa_client_info_pull_hist.asis_agency4_code
     *
     * @mbg.generated
     */
    public String getAsisAgency4Code() {
        return asisAgency4Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.asis_agency4_code
     *
     * @param asisAgency4Code the value for damoa_client_info_pull_hist.asis_agency4_code
     *
     * @mbg.generated
     */
    public void setAsisAgency4Code(String asisAgency4Code) {
        this.asisAgency4Code = asisAgency4Code == null ? null : asisAgency4Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.asis_agency4_name
     *
     * @return the value of damoa_client_info_pull_hist.asis_agency4_name
     *
     * @mbg.generated
     */
    public String getAsisAgency4Name() {
        return asisAgency4Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.asis_agency4_name
     *
     * @param asisAgency4Name the value for damoa_client_info_pull_hist.asis_agency4_name
     *
     * @mbg.generated
     */
    public void setAsisAgency4Name(String asisAgency4Name) {
        this.asisAgency4Name = asisAgency4Name == null ? null : asisAgency4Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.asis_agency5_code
     *
     * @return the value of damoa_client_info_pull_hist.asis_agency5_code
     *
     * @mbg.generated
     */
    public String getAsisAgency5Code() {
        return asisAgency5Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.asis_agency5_code
     *
     * @param asisAgency5Code the value for damoa_client_info_pull_hist.asis_agency5_code
     *
     * @mbg.generated
     */
    public void setAsisAgency5Code(String asisAgency5Code) {
        this.asisAgency5Code = asisAgency5Code == null ? null : asisAgency5Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.asis_agency5_name
     *
     * @return the value of damoa_client_info_pull_hist.asis_agency5_name
     *
     * @mbg.generated
     */
    public String getAsisAgency5Name() {
        return asisAgency5Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.asis_agency5_name
     *
     * @param asisAgency5Name the value for damoa_client_info_pull_hist.asis_agency5_name
     *
     * @mbg.generated
     */
    public void setAsisAgency5Name(String asisAgency5Name) {
        this.asisAgency5Name = asisAgency5Name == null ? null : asisAgency5Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.asis_agency6_code
     *
     * @return the value of damoa_client_info_pull_hist.asis_agency6_code
     *
     * @mbg.generated
     */
    public String getAsisAgency6Code() {
        return asisAgency6Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.asis_agency6_code
     *
     * @param asisAgency6Code the value for damoa_client_info_pull_hist.asis_agency6_code
     *
     * @mbg.generated
     */
    public void setAsisAgency6Code(String asisAgency6Code) {
        this.asisAgency6Code = asisAgency6Code == null ? null : asisAgency6Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.asis_agency6_name
     *
     * @return the value of damoa_client_info_pull_hist.asis_agency6_name
     *
     * @mbg.generated
     */
    public String getAsisAgency6Name() {
        return asisAgency6Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.asis_agency6_name
     *
     * @param asisAgency6Name the value for damoa_client_info_pull_hist.asis_agency6_name
     *
     * @mbg.generated
     */
    public void setAsisAgency6Name(String asisAgency6Name) {
        this.asisAgency6Name = asisAgency6Name == null ? null : asisAgency6Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.asis_agency7_code
     *
     * @return the value of damoa_client_info_pull_hist.asis_agency7_code
     *
     * @mbg.generated
     */
    public String getAsisAgency7Code() {
        return asisAgency7Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.asis_agency7_code
     *
     * @param asisAgency7Code the value for damoa_client_info_pull_hist.asis_agency7_code
     *
     * @mbg.generated
     */
    public void setAsisAgency7Code(String asisAgency7Code) {
        this.asisAgency7Code = asisAgency7Code == null ? null : asisAgency7Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.asis_agency7_name
     *
     * @return the value of damoa_client_info_pull_hist.asis_agency7_name
     *
     * @mbg.generated
     */
    public String getAsisAgency7Name() {
        return asisAgency7Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.asis_agency7_name
     *
     * @param asisAgency7Name the value for damoa_client_info_pull_hist.asis_agency7_name
     *
     * @mbg.generated
     */
    public void setAsisAgency7Name(String asisAgency7Name) {
        this.asisAgency7Name = asisAgency7Name == null ? null : asisAgency7Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.asis_agency8_code
     *
     * @return the value of damoa_client_info_pull_hist.asis_agency8_code
     *
     * @mbg.generated
     */
    public String getAsisAgency8Code() {
        return asisAgency8Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.asis_agency8_code
     *
     * @param asisAgency8Code the value for damoa_client_info_pull_hist.asis_agency8_code
     *
     * @mbg.generated
     */
    public void setAsisAgency8Code(String asisAgency8Code) {
        this.asisAgency8Code = asisAgency8Code == null ? null : asisAgency8Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.asis_agency8_name
     *
     * @return the value of damoa_client_info_pull_hist.asis_agency8_name
     *
     * @mbg.generated
     */
    public String getAsisAgency8Name() {
        return asisAgency8Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.asis_agency8_name
     *
     * @param asisAgency8Name the value for damoa_client_info_pull_hist.asis_agency8_name
     *
     * @mbg.generated
     */
    public void setAsisAgency8Name(String asisAgency8Name) {
        this.asisAgency8Name = asisAgency8Name == null ? null : asisAgency8Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.asis_agency9_code
     *
     * @return the value of damoa_client_info_pull_hist.asis_agency9_code
     *
     * @mbg.generated
     */
    public String getAsisAgency9Code() {
        return asisAgency9Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.asis_agency9_code
     *
     * @param asisAgency9Code the value for damoa_client_info_pull_hist.asis_agency9_code
     *
     * @mbg.generated
     */
    public void setAsisAgency9Code(String asisAgency9Code) {
        this.asisAgency9Code = asisAgency9Code == null ? null : asisAgency9Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.asis_agency9_name
     *
     * @return the value of damoa_client_info_pull_hist.asis_agency9_name
     *
     * @mbg.generated
     */
    public String getAsisAgency9Name() {
        return asisAgency9Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.asis_agency9_name
     *
     * @param asisAgency9Name the value for damoa_client_info_pull_hist.asis_agency9_name
     *
     * @mbg.generated
     */
    public void setAsisAgency9Name(String asisAgency9Name) {
        this.asisAgency9Name = asisAgency9Name == null ? null : asisAgency9Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.asis_agency10_code
     *
     * @return the value of damoa_client_info_pull_hist.asis_agency10_code
     *
     * @mbg.generated
     */
    public String getAsisAgency10Code() {
        return asisAgency10Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.asis_agency10_code
     *
     * @param asisAgency10Code the value for damoa_client_info_pull_hist.asis_agency10_code
     *
     * @mbg.generated
     */
    public void setAsisAgency10Code(String asisAgency10Code) {
        this.asisAgency10Code = asisAgency10Code == null ? null : asisAgency10Code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.asis_agency10_name
     *
     * @return the value of damoa_client_info_pull_hist.asis_agency10_name
     *
     * @mbg.generated
     */
    public String getAsisAgency10Name() {
        return asisAgency10Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.asis_agency10_name
     *
     * @param asisAgency10Name the value for damoa_client_info_pull_hist.asis_agency10_name
     *
     * @mbg.generated
     */
    public void setAsisAgency10Name(String asisAgency10Name) {
        this.asisAgency10Name = asisAgency10Name == null ? null : asisAgency10Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.asis_payment_fee_amt
     *
     * @return the value of damoa_client_info_pull_hist.asis_payment_fee_amt
     *
     * @mbg.generated
     */
    public Integer getAsisPaymentFeeAmt() {
        return asisPaymentFeeAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.asis_payment_fee_amt
     *
     * @param asisPaymentFeeAmt the value for damoa_client_info_pull_hist.asis_payment_fee_amt
     *
     * @mbg.generated
     */
    public void setAsisPaymentFeeAmt(Integer asisPaymentFeeAmt) {
        this.asisPaymentFeeAmt = asisPaymentFeeAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.asis_finger_fee_rate
     *
     * @return the value of damoa_client_info_pull_hist.asis_finger_fee_rate
     *
     * @mbg.generated
     */
    public Integer getAsisFingerFeeRate() {
        return asisFingerFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.asis_finger_fee_rate
     *
     * @param asisFingerFeeRate the value for damoa_client_info_pull_hist.asis_finger_fee_rate
     *
     * @mbg.generated
     */
    public void setAsisFingerFeeRate(Integer asisFingerFeeRate) {
        this.asisFingerFeeRate = asisFingerFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.asis_brch_code
     *
     * @return the value of damoa_client_info_pull_hist.asis_brch_code
     *
     * @mbg.generated
     */
    public String getAsisBrchCode() {
        return asisBrchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.asis_brch_code
     *
     * @param asisBrchCode the value for damoa_client_info_pull_hist.asis_brch_code
     *
     * @mbg.generated
     */
    public void setAsisBrchCode(String asisBrchCode) {
        this.asisBrchCode = asisBrchCode == null ? null : asisBrchCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damoa_client_info_pull_hist
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DamoaClientInfoPullHist other = (DamoaClientInfoPullHist) that;
        return (this.getPullDt() == null ? other.getPullDt() == null : this.getPullDt().equals(other.getPullDt()))
            && (this.getClientId() == null ? other.getClientId() == null : this.getClientId().equals(other.getClientId()))
            && (this.getClientName() == null ? other.getClientName() == null : this.getClientName().equals(other.getClientName()))
            && (this.getClientDeleteYn() == null ? other.getClientDeleteYn() == null : this.getClientDeleteYn().equals(other.getClientDeleteYn()))
            && (this.getRelayClientId() == null ? other.getRelayClientId() == null : this.getRelayClientId().equals(other.getRelayClientId()))
            && (this.getRgstDt() == null ? other.getRgstDt() == null : this.getRgstDt().equals(other.getRgstDt()))
            && (this.getClientIdNo() == null ? other.getClientIdNo() == null : this.getClientIdNo().equals(other.getClientIdNo()))
            && (this.getClientStatus() == null ? other.getClientStatus() == null : this.getClientStatus().equals(other.getClientStatus()))
            && (this.getAgency1Code() == null ? other.getAgency1Code() == null : this.getAgency1Code().equals(other.getAgency1Code()))
            && (this.getAgency1Name() == null ? other.getAgency1Name() == null : this.getAgency1Name().equals(other.getAgency1Name()))
            && (this.getAgency1Status() == null ? other.getAgency1Status() == null : this.getAgency1Status().equals(other.getAgency1Status()))
            && (this.getAgency2Code() == null ? other.getAgency2Code() == null : this.getAgency2Code().equals(other.getAgency2Code()))
            && (this.getAgency2Name() == null ? other.getAgency2Name() == null : this.getAgency2Name().equals(other.getAgency2Name()))
            && (this.getAgency2Status() == null ? other.getAgency2Status() == null : this.getAgency2Status().equals(other.getAgency2Status()))
            && (this.getAgency3Code() == null ? other.getAgency3Code() == null : this.getAgency3Code().equals(other.getAgency3Code()))
            && (this.getAgency3Name() == null ? other.getAgency3Name() == null : this.getAgency3Name().equals(other.getAgency3Name()))
            && (this.getAgency3Status() == null ? other.getAgency3Status() == null : this.getAgency3Status().equals(other.getAgency3Status()))
            && (this.getAgency4Code() == null ? other.getAgency4Code() == null : this.getAgency4Code().equals(other.getAgency4Code()))
            && (this.getAgency4Name() == null ? other.getAgency4Name() == null : this.getAgency4Name().equals(other.getAgency4Name()))
            && (this.getAgency4Status() == null ? other.getAgency4Status() == null : this.getAgency4Status().equals(other.getAgency4Status()))
            && (this.getAgency5Code() == null ? other.getAgency5Code() == null : this.getAgency5Code().equals(other.getAgency5Code()))
            && (this.getAgency5Name() == null ? other.getAgency5Name() == null : this.getAgency5Name().equals(other.getAgency5Name()))
            && (this.getAgency5Status() == null ? other.getAgency5Status() == null : this.getAgency5Status().equals(other.getAgency5Status()))
            && (this.getAgency6Code() == null ? other.getAgency6Code() == null : this.getAgency6Code().equals(other.getAgency6Code()))
            && (this.getAgency6Name() == null ? other.getAgency6Name() == null : this.getAgency6Name().equals(other.getAgency6Name()))
            && (this.getAgency6Status() == null ? other.getAgency6Status() == null : this.getAgency6Status().equals(other.getAgency6Status()))
            && (this.getAgency7Code() == null ? other.getAgency7Code() == null : this.getAgency7Code().equals(other.getAgency7Code()))
            && (this.getAgency7Name() == null ? other.getAgency7Name() == null : this.getAgency7Name().equals(other.getAgency7Name()))
            && (this.getAgency7Status() == null ? other.getAgency7Status() == null : this.getAgency7Status().equals(other.getAgency7Status()))
            && (this.getAgency8Code() == null ? other.getAgency8Code() == null : this.getAgency8Code().equals(other.getAgency8Code()))
            && (this.getAgency8Name() == null ? other.getAgency8Name() == null : this.getAgency8Name().equals(other.getAgency8Name()))
            && (this.getAgency8Status() == null ? other.getAgency8Status() == null : this.getAgency8Status().equals(other.getAgency8Status()))
            && (this.getAgency9Code() == null ? other.getAgency9Code() == null : this.getAgency9Code().equals(other.getAgency9Code()))
            && (this.getAgency9Name() == null ? other.getAgency9Name() == null : this.getAgency9Name().equals(other.getAgency9Name()))
            && (this.getAgency9Status() == null ? other.getAgency9Status() == null : this.getAgency9Status().equals(other.getAgency9Status()))
            && (this.getAgency10Code() == null ? other.getAgency10Code() == null : this.getAgency10Code().equals(other.getAgency10Code()))
            && (this.getAgency10Name() == null ? other.getAgency10Name() == null : this.getAgency10Name().equals(other.getAgency10Name()))
            && (this.getAgency10Status() == null ? other.getAgency10Status() == null : this.getAgency10Status().equals(other.getAgency10Status()))
            && (this.getPaymentFeeAmt() == null ? other.getPaymentFeeAmt() == null : this.getPaymentFeeAmt().equals(other.getPaymentFeeAmt()))
            && (this.getFingerFeeRate() == null ? other.getFingerFeeRate() == null : this.getFingerFeeRate().equals(other.getFingerFeeRate()))
            && (this.getBrchCode() == null ? other.getBrchCode() == null : this.getBrchCode().equals(other.getBrchCode()))
            && (this.getStatusCd() == null ? other.getStatusCd() == null : this.getStatusCd().equals(other.getStatusCd()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getModifyDate() == null ? other.getModifyDate() == null : this.getModifyDate().equals(other.getModifyDate()))
            && (this.getModifyUser() == null ? other.getModifyUser() == null : this.getModifyUser().equals(other.getModifyUser()))
            && (this.getTypeCd() == null ? other.getTypeCd() == null : this.getTypeCd().equals(other.getTypeCd()))
            && (this.getAsisClientName() == null ? other.getAsisClientName() == null : this.getAsisClientName().equals(other.getAsisClientName()))
            && (this.getAsisClientIdNo() == null ? other.getAsisClientIdNo() == null : this.getAsisClientIdNo().equals(other.getAsisClientIdNo()))
            && (this.getAsisClientStatus() == null ? other.getAsisClientStatus() == null : this.getAsisClientStatus().equals(other.getAsisClientStatus()))
            && (this.getAsisAgency1Code() == null ? other.getAsisAgency1Code() == null : this.getAsisAgency1Code().equals(other.getAsisAgency1Code()))
            && (this.getAsisAgency1Name() == null ? other.getAsisAgency1Name() == null : this.getAsisAgency1Name().equals(other.getAsisAgency1Name()))
            && (this.getAsisAgency2Code() == null ? other.getAsisAgency2Code() == null : this.getAsisAgency2Code().equals(other.getAsisAgency2Code()))
            && (this.getAsisAgency2Name() == null ? other.getAsisAgency2Name() == null : this.getAsisAgency2Name().equals(other.getAsisAgency2Name()))
            && (this.getAsisAgency3Code() == null ? other.getAsisAgency3Code() == null : this.getAsisAgency3Code().equals(other.getAsisAgency3Code()))
            && (this.getAsisAgency3Name() == null ? other.getAsisAgency3Name() == null : this.getAsisAgency3Name().equals(other.getAsisAgency3Name()))
            && (this.getAsisAgency4Code() == null ? other.getAsisAgency4Code() == null : this.getAsisAgency4Code().equals(other.getAsisAgency4Code()))
            && (this.getAsisAgency4Name() == null ? other.getAsisAgency4Name() == null : this.getAsisAgency4Name().equals(other.getAsisAgency4Name()))
            && (this.getAsisAgency5Code() == null ? other.getAsisAgency5Code() == null : this.getAsisAgency5Code().equals(other.getAsisAgency5Code()))
            && (this.getAsisAgency5Name() == null ? other.getAsisAgency5Name() == null : this.getAsisAgency5Name().equals(other.getAsisAgency5Name()))
            && (this.getAsisAgency6Code() == null ? other.getAsisAgency6Code() == null : this.getAsisAgency6Code().equals(other.getAsisAgency6Code()))
            && (this.getAsisAgency6Name() == null ? other.getAsisAgency6Name() == null : this.getAsisAgency6Name().equals(other.getAsisAgency6Name()))
            && (this.getAsisAgency7Code() == null ? other.getAsisAgency7Code() == null : this.getAsisAgency7Code().equals(other.getAsisAgency7Code()))
            && (this.getAsisAgency7Name() == null ? other.getAsisAgency7Name() == null : this.getAsisAgency7Name().equals(other.getAsisAgency7Name()))
            && (this.getAsisAgency8Code() == null ? other.getAsisAgency8Code() == null : this.getAsisAgency8Code().equals(other.getAsisAgency8Code()))
            && (this.getAsisAgency8Name() == null ? other.getAsisAgency8Name() == null : this.getAsisAgency8Name().equals(other.getAsisAgency8Name()))
            && (this.getAsisAgency9Code() == null ? other.getAsisAgency9Code() == null : this.getAsisAgency9Code().equals(other.getAsisAgency9Code()))
            && (this.getAsisAgency9Name() == null ? other.getAsisAgency9Name() == null : this.getAsisAgency9Name().equals(other.getAsisAgency9Name()))
            && (this.getAsisAgency10Code() == null ? other.getAsisAgency10Code() == null : this.getAsisAgency10Code().equals(other.getAsisAgency10Code()))
            && (this.getAsisAgency10Name() == null ? other.getAsisAgency10Name() == null : this.getAsisAgency10Name().equals(other.getAsisAgency10Name()))
            && (this.getAsisPaymentFeeAmt() == null ? other.getAsisPaymentFeeAmt() == null : this.getAsisPaymentFeeAmt().equals(other.getAsisPaymentFeeAmt()))
            && (this.getAsisFingerFeeRate() == null ? other.getAsisFingerFeeRate() == null : this.getAsisFingerFeeRate().equals(other.getAsisFingerFeeRate()))
            && (this.getAsisBrchCode() == null ? other.getAsisBrchCode() == null : this.getAsisBrchCode().equals(other.getAsisBrchCode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damoa_client_info_pull_hist
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPullDt() == null) ? 0 : getPullDt().hashCode());
        result = prime * result + ((getClientId() == null) ? 0 : getClientId().hashCode());
        result = prime * result + ((getClientName() == null) ? 0 : getClientName().hashCode());
        result = prime * result + ((getClientDeleteYn() == null) ? 0 : getClientDeleteYn().hashCode());
        result = prime * result + ((getRelayClientId() == null) ? 0 : getRelayClientId().hashCode());
        result = prime * result + ((getRgstDt() == null) ? 0 : getRgstDt().hashCode());
        result = prime * result + ((getClientIdNo() == null) ? 0 : getClientIdNo().hashCode());
        result = prime * result + ((getClientStatus() == null) ? 0 : getClientStatus().hashCode());
        result = prime * result + ((getAgency1Code() == null) ? 0 : getAgency1Code().hashCode());
        result = prime * result + ((getAgency1Name() == null) ? 0 : getAgency1Name().hashCode());
        result = prime * result + ((getAgency1Status() == null) ? 0 : getAgency1Status().hashCode());
        result = prime * result + ((getAgency2Code() == null) ? 0 : getAgency2Code().hashCode());
        result = prime * result + ((getAgency2Name() == null) ? 0 : getAgency2Name().hashCode());
        result = prime * result + ((getAgency2Status() == null) ? 0 : getAgency2Status().hashCode());
        result = prime * result + ((getAgency3Code() == null) ? 0 : getAgency3Code().hashCode());
        result = prime * result + ((getAgency3Name() == null) ? 0 : getAgency3Name().hashCode());
        result = prime * result + ((getAgency3Status() == null) ? 0 : getAgency3Status().hashCode());
        result = prime * result + ((getAgency4Code() == null) ? 0 : getAgency4Code().hashCode());
        result = prime * result + ((getAgency4Name() == null) ? 0 : getAgency4Name().hashCode());
        result = prime * result + ((getAgency4Status() == null) ? 0 : getAgency4Status().hashCode());
        result = prime * result + ((getAgency5Code() == null) ? 0 : getAgency5Code().hashCode());
        result = prime * result + ((getAgency5Name() == null) ? 0 : getAgency5Name().hashCode());
        result = prime * result + ((getAgency5Status() == null) ? 0 : getAgency5Status().hashCode());
        result = prime * result + ((getAgency6Code() == null) ? 0 : getAgency6Code().hashCode());
        result = prime * result + ((getAgency6Name() == null) ? 0 : getAgency6Name().hashCode());
        result = prime * result + ((getAgency6Status() == null) ? 0 : getAgency6Status().hashCode());
        result = prime * result + ((getAgency7Code() == null) ? 0 : getAgency7Code().hashCode());
        result = prime * result + ((getAgency7Name() == null) ? 0 : getAgency7Name().hashCode());
        result = prime * result + ((getAgency7Status() == null) ? 0 : getAgency7Status().hashCode());
        result = prime * result + ((getAgency8Code() == null) ? 0 : getAgency8Code().hashCode());
        result = prime * result + ((getAgency8Name() == null) ? 0 : getAgency8Name().hashCode());
        result = prime * result + ((getAgency8Status() == null) ? 0 : getAgency8Status().hashCode());
        result = prime * result + ((getAgency9Code() == null) ? 0 : getAgency9Code().hashCode());
        result = prime * result + ((getAgency9Name() == null) ? 0 : getAgency9Name().hashCode());
        result = prime * result + ((getAgency9Status() == null) ? 0 : getAgency9Status().hashCode());
        result = prime * result + ((getAgency10Code() == null) ? 0 : getAgency10Code().hashCode());
        result = prime * result + ((getAgency10Name() == null) ? 0 : getAgency10Name().hashCode());
        result = prime * result + ((getAgency10Status() == null) ? 0 : getAgency10Status().hashCode());
        result = prime * result + ((getPaymentFeeAmt() == null) ? 0 : getPaymentFeeAmt().hashCode());
        result = prime * result + ((getFingerFeeRate() == null) ? 0 : getFingerFeeRate().hashCode());
        result = prime * result + ((getBrchCode() == null) ? 0 : getBrchCode().hashCode());
        result = prime * result + ((getStatusCd() == null) ? 0 : getStatusCd().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getModifyDate() == null) ? 0 : getModifyDate().hashCode());
        result = prime * result + ((getModifyUser() == null) ? 0 : getModifyUser().hashCode());
        result = prime * result + ((getTypeCd() == null) ? 0 : getTypeCd().hashCode());
        result = prime * result + ((getAsisClientName() == null) ? 0 : getAsisClientName().hashCode());
        result = prime * result + ((getAsisClientIdNo() == null) ? 0 : getAsisClientIdNo().hashCode());
        result = prime * result + ((getAsisClientStatus() == null) ? 0 : getAsisClientStatus().hashCode());
        result = prime * result + ((getAsisAgency1Code() == null) ? 0 : getAsisAgency1Code().hashCode());
        result = prime * result + ((getAsisAgency1Name() == null) ? 0 : getAsisAgency1Name().hashCode());
        result = prime * result + ((getAsisAgency2Code() == null) ? 0 : getAsisAgency2Code().hashCode());
        result = prime * result + ((getAsisAgency2Name() == null) ? 0 : getAsisAgency2Name().hashCode());
        result = prime * result + ((getAsisAgency3Code() == null) ? 0 : getAsisAgency3Code().hashCode());
        result = prime * result + ((getAsisAgency3Name() == null) ? 0 : getAsisAgency3Name().hashCode());
        result = prime * result + ((getAsisAgency4Code() == null) ? 0 : getAsisAgency4Code().hashCode());
        result = prime * result + ((getAsisAgency4Name() == null) ? 0 : getAsisAgency4Name().hashCode());
        result = prime * result + ((getAsisAgency5Code() == null) ? 0 : getAsisAgency5Code().hashCode());
        result = prime * result + ((getAsisAgency5Name() == null) ? 0 : getAsisAgency5Name().hashCode());
        result = prime * result + ((getAsisAgency6Code() == null) ? 0 : getAsisAgency6Code().hashCode());
        result = prime * result + ((getAsisAgency6Name() == null) ? 0 : getAsisAgency6Name().hashCode());
        result = prime * result + ((getAsisAgency7Code() == null) ? 0 : getAsisAgency7Code().hashCode());
        result = prime * result + ((getAsisAgency7Name() == null) ? 0 : getAsisAgency7Name().hashCode());
        result = prime * result + ((getAsisAgency8Code() == null) ? 0 : getAsisAgency8Code().hashCode());
        result = prime * result + ((getAsisAgency8Name() == null) ? 0 : getAsisAgency8Name().hashCode());
        result = prime * result + ((getAsisAgency9Code() == null) ? 0 : getAsisAgency9Code().hashCode());
        result = prime * result + ((getAsisAgency9Name() == null) ? 0 : getAsisAgency9Name().hashCode());
        result = prime * result + ((getAsisAgency10Code() == null) ? 0 : getAsisAgency10Code().hashCode());
        result = prime * result + ((getAsisAgency10Name() == null) ? 0 : getAsisAgency10Name().hashCode());
        result = prime * result + ((getAsisPaymentFeeAmt() == null) ? 0 : getAsisPaymentFeeAmt().hashCode());
        result = prime * result + ((getAsisFingerFeeRate() == null) ? 0 : getAsisFingerFeeRate().hashCode());
        result = prime * result + ((getAsisBrchCode() == null) ? 0 : getAsisBrchCode().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damoa_client_info_pull_hist
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", clientName=").append(clientName);
        sb.append(", clientDeleteYn=").append(clientDeleteYn);
        sb.append(", relayClientId=").append(relayClientId);
        sb.append(", rgstDt=").append(rgstDt);
        sb.append(", clientIdNo=").append(clientIdNo);
        sb.append(", clientStatus=").append(clientStatus);
        sb.append(", agency1Code=").append(agency1Code);
        sb.append(", agency1Name=").append(agency1Name);
        sb.append(", agency1Status=").append(agency1Status);
        sb.append(", agency2Code=").append(agency2Code);
        sb.append(", agency2Name=").append(agency2Name);
        sb.append(", agency2Status=").append(agency2Status);
        sb.append(", agency3Code=").append(agency3Code);
        sb.append(", agency3Name=").append(agency3Name);
        sb.append(", agency3Status=").append(agency3Status);
        sb.append(", agency4Code=").append(agency4Code);
        sb.append(", agency4Name=").append(agency4Name);
        sb.append(", agency4Status=").append(agency4Status);
        sb.append(", agency5Code=").append(agency5Code);
        sb.append(", agency5Name=").append(agency5Name);
        sb.append(", agency5Status=").append(agency5Status);
        sb.append(", agency6Code=").append(agency6Code);
        sb.append(", agency6Name=").append(agency6Name);
        sb.append(", agency6Status=").append(agency6Status);
        sb.append(", agency7Code=").append(agency7Code);
        sb.append(", agency7Name=").append(agency7Name);
        sb.append(", agency7Status=").append(agency7Status);
        sb.append(", agency8Code=").append(agency8Code);
        sb.append(", agency8Name=").append(agency8Name);
        sb.append(", agency8Status=").append(agency8Status);
        sb.append(", agency9Code=").append(agency9Code);
        sb.append(", agency9Name=").append(agency9Name);
        sb.append(", agency9Status=").append(agency9Status);
        sb.append(", agency10Code=").append(agency10Code);
        sb.append(", agency10Name=").append(agency10Name);
        sb.append(", agency10Status=").append(agency10Status);
        sb.append(", paymentFeeAmt=").append(paymentFeeAmt);
        sb.append(", fingerFeeRate=").append(fingerFeeRate);
        sb.append(", brchCode=").append(brchCode);
        sb.append(", statusCd=").append(statusCd);
        sb.append(", createDate=").append(createDate);
        sb.append(", createUser=").append(createUser);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", modifyUser=").append(modifyUser);
        sb.append(", typeCd=").append(typeCd);
        sb.append(", asisClientName=").append(asisClientName);
        sb.append(", asisClientIdNo=").append(asisClientIdNo);
        sb.append(", asisClientStatus=").append(asisClientStatus);
        sb.append(", asisAgency1Code=").append(asisAgency1Code);
        sb.append(", asisAgency1Name=").append(asisAgency1Name);
        sb.append(", asisAgency2Code=").append(asisAgency2Code);
        sb.append(", asisAgency2Name=").append(asisAgency2Name);
        sb.append(", asisAgency3Code=").append(asisAgency3Code);
        sb.append(", asisAgency3Name=").append(asisAgency3Name);
        sb.append(", asisAgency4Code=").append(asisAgency4Code);
        sb.append(", asisAgency4Name=").append(asisAgency4Name);
        sb.append(", asisAgency5Code=").append(asisAgency5Code);
        sb.append(", asisAgency5Name=").append(asisAgency5Name);
        sb.append(", asisAgency6Code=").append(asisAgency6Code);
        sb.append(", asisAgency6Name=").append(asisAgency6Name);
        sb.append(", asisAgency7Code=").append(asisAgency7Code);
        sb.append(", asisAgency7Name=").append(asisAgency7Name);
        sb.append(", asisAgency8Code=").append(asisAgency8Code);
        sb.append(", asisAgency8Name=").append(asisAgency8Name);
        sb.append(", asisAgency9Code=").append(asisAgency9Code);
        sb.append(", asisAgency9Name=").append(asisAgency9Name);
        sb.append(", asisAgency10Code=").append(asisAgency10Code);
        sb.append(", asisAgency10Name=").append(asisAgency10Name);
        sb.append(", asisPaymentFeeAmt=").append(asisPaymentFeeAmt);
        sb.append(", asisFingerFeeRate=").append(asisFingerFeeRate);
        sb.append(", asisBrchCode=").append(asisBrchCode);
        sb.append("]");
        return sb.toString();
    }
}