package kr.co.finger.shinhandamoa.data.table.model;

import java.io.Serializable;

public class DamoaClientInfoPullHistKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.pull_dt
     *
     * @mbg.generated
     */
    private String pullDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column damoa_client_info_pull_hist.client_id
     *
     * @mbg.generated
     */
    private String clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table damoa_client_info_pull_hist
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.pull_dt
     *
     * @return the value of damoa_client_info_pull_hist.pull_dt
     *
     * @mbg.generated
     */
    public String getPullDt() {
        return pullDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.pull_dt
     *
     * @param pullDt the value for damoa_client_info_pull_hist.pull_dt
     *
     * @mbg.generated
     */
    public void setPullDt(String pullDt) {
        this.pullDt = pullDt == null ? null : pullDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column damoa_client_info_pull_hist.client_id
     *
     * @return the value of damoa_client_info_pull_hist.client_id
     *
     * @mbg.generated
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column damoa_client_info_pull_hist.client_id
     *
     * @param clientId the value for damoa_client_info_pull_hist.client_id
     *
     * @mbg.generated
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damoa_client_info_pull_hist
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DamoaClientInfoPullHistKey other = (DamoaClientInfoPullHistKey) that;
        return (this.getPullDt() == null ? other.getPullDt() == null : this.getPullDt().equals(other.getPullDt()))
            && (this.getClientId() == null ? other.getClientId() == null : this.getClientId().equals(other.getClientId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damoa_client_info_pull_hist
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPullDt() == null) ? 0 : getPullDt().hashCode());
        result = prime * result + ((getClientId() == null) ? 0 : getClientId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damoa_client_info_pull_hist
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pullDt=").append(pullDt);
        sb.append(", clientId=").append(clientId);
        sb.append("]");
        return sb.toString();
    }
}