package kr.co.finger.shinhandamoa.data.table.model;

import java.util.ArrayList;
import java.util.List;

public class XdaysumnotiExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    public XdaysumnotiExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andChacdIsNull() {
            addCriterion("chacd is null");
            return (Criteria) this;
        }

        public Criteria andChacdIsNotNull() {
            addCriterion("chacd is not null");
            return (Criteria) this;
        }

        public Criteria andChacdEqualTo(String value) {
            addCriterion("chacd =", value, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdNotEqualTo(String value) {
            addCriterion("chacd <>", value, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdGreaterThan(String value) {
            addCriterion("chacd >", value, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdGreaterThanOrEqualTo(String value) {
            addCriterion("chacd >=", value, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdLessThan(String value) {
            addCriterion("chacd <", value, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdLessThanOrEqualTo(String value) {
            addCriterion("chacd <=", value, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdLike(String value) {
            addCriterion("chacd like", value, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdNotLike(String value) {
            addCriterion("chacd not like", value, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdIn(List<String> values) {
            addCriterion("chacd in", values, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdNotIn(List<String> values) {
            addCriterion("chacd not in", values, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdBetween(String value1, String value2) {
            addCriterion("chacd between", value1, value2, "chacd");
            return (Criteria) this;
        }

        public Criteria andChacdNotBetween(String value1, String value2) {
            addCriterion("chacd not between", value1, value2, "chacd");
            return (Criteria) this;
        }

        public Criteria andNotidayIsNull() {
            addCriterion("notiday is null");
            return (Criteria) this;
        }

        public Criteria andNotidayIsNotNull() {
            addCriterion("notiday is not null");
            return (Criteria) this;
        }

        public Criteria andNotidayEqualTo(String value) {
            addCriterion("notiday =", value, "notiday");
            return (Criteria) this;
        }

        public Criteria andNotidayNotEqualTo(String value) {
            addCriterion("notiday <>", value, "notiday");
            return (Criteria) this;
        }

        public Criteria andNotidayGreaterThan(String value) {
            addCriterion("notiday >", value, "notiday");
            return (Criteria) this;
        }

        public Criteria andNotidayGreaterThanOrEqualTo(String value) {
            addCriterion("notiday >=", value, "notiday");
            return (Criteria) this;
        }

        public Criteria andNotidayLessThan(String value) {
            addCriterion("notiday <", value, "notiday");
            return (Criteria) this;
        }

        public Criteria andNotidayLessThanOrEqualTo(String value) {
            addCriterion("notiday <=", value, "notiday");
            return (Criteria) this;
        }

        public Criteria andNotidayLike(String value) {
            addCriterion("notiday like", value, "notiday");
            return (Criteria) this;
        }

        public Criteria andNotidayNotLike(String value) {
            addCriterion("notiday not like", value, "notiday");
            return (Criteria) this;
        }

        public Criteria andNotidayIn(List<String> values) {
            addCriterion("notiday in", values, "notiday");
            return (Criteria) this;
        }

        public Criteria andNotidayNotIn(List<String> values) {
            addCriterion("notiday not in", values, "notiday");
            return (Criteria) this;
        }

        public Criteria andNotidayBetween(String value1, String value2) {
            addCriterion("notiday between", value1, value2, "notiday");
            return (Criteria) this;
        }

        public Criteria andNotidayNotBetween(String value1, String value2) {
            addCriterion("notiday not between", value1, value2, "notiday");
            return (Criteria) this;
        }

        public Criteria andNoticntIsNull() {
            addCriterion("noticnt is null");
            return (Criteria) this;
        }

        public Criteria andNoticntIsNotNull() {
            addCriterion("noticnt is not null");
            return (Criteria) this;
        }

        public Criteria andNoticntEqualTo(Integer value) {
            addCriterion("noticnt =", value, "noticnt");
            return (Criteria) this;
        }

        public Criteria andNoticntNotEqualTo(Integer value) {
            addCriterion("noticnt <>", value, "noticnt");
            return (Criteria) this;
        }

        public Criteria andNoticntGreaterThan(Integer value) {
            addCriterion("noticnt >", value, "noticnt");
            return (Criteria) this;
        }

        public Criteria andNoticntGreaterThanOrEqualTo(Integer value) {
            addCriterion("noticnt >=", value, "noticnt");
            return (Criteria) this;
        }

        public Criteria andNoticntLessThan(Integer value) {
            addCriterion("noticnt <", value, "noticnt");
            return (Criteria) this;
        }

        public Criteria andNoticntLessThanOrEqualTo(Integer value) {
            addCriterion("noticnt <=", value, "noticnt");
            return (Criteria) this;
        }

        public Criteria andNoticntIn(List<Integer> values) {
            addCriterion("noticnt in", values, "noticnt");
            return (Criteria) this;
        }

        public Criteria andNoticntNotIn(List<Integer> values) {
            addCriterion("noticnt not in", values, "noticnt");
            return (Criteria) this;
        }

        public Criteria andNoticntBetween(Integer value1, Integer value2) {
            addCriterion("noticnt between", value1, value2, "noticnt");
            return (Criteria) this;
        }

        public Criteria andNoticntNotBetween(Integer value1, Integer value2) {
            addCriterion("noticnt not between", value1, value2, "noticnt");
            return (Criteria) this;
        }

        public Criteria andNotiamtIsNull() {
            addCriterion("notiamt is null");
            return (Criteria) this;
        }

        public Criteria andNotiamtIsNotNull() {
            addCriterion("notiamt is not null");
            return (Criteria) this;
        }

        public Criteria andNotiamtEqualTo(Long value) {
            addCriterion("notiamt =", value, "notiamt");
            return (Criteria) this;
        }

        public Criteria andNotiamtNotEqualTo(Long value) {
            addCriterion("notiamt <>", value, "notiamt");
            return (Criteria) this;
        }

        public Criteria andNotiamtGreaterThan(Long value) {
            addCriterion("notiamt >", value, "notiamt");
            return (Criteria) this;
        }

        public Criteria andNotiamtGreaterThanOrEqualTo(Long value) {
            addCriterion("notiamt >=", value, "notiamt");
            return (Criteria) this;
        }

        public Criteria andNotiamtLessThan(Long value) {
            addCriterion("notiamt <", value, "notiamt");
            return (Criteria) this;
        }

        public Criteria andNotiamtLessThanOrEqualTo(Long value) {
            addCriterion("notiamt <=", value, "notiamt");
            return (Criteria) this;
        }

        public Criteria andNotiamtIn(List<Long> values) {
            addCriterion("notiamt in", values, "notiamt");
            return (Criteria) this;
        }

        public Criteria andNotiamtNotIn(List<Long> values) {
            addCriterion("notiamt not in", values, "notiamt");
            return (Criteria) this;
        }

        public Criteria andNotiamtBetween(Long value1, Long value2) {
            addCriterion("notiamt between", value1, value2, "notiamt");
            return (Criteria) this;
        }

        public Criteria andNotiamtNotBetween(Long value1, Long value2) {
            addCriterion("notiamt not between", value1, value2, "notiamt");
            return (Criteria) this;
        }

        public Criteria andChacdLikeInsensitive(String value) {
            addCriterion("upper(chacd) like", value.toUpperCase(), "chacd");
            return (Criteria) this;
        }

        public Criteria andNotidayLikeInsensitive(String value) {
            addCriterion("upper(notiday) like", value.toUpperCase(), "notiday");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xdaysumnoti
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}