package kr.co.finger.shinhandamoa.data.table.model;

import java.io.Serializable;
import java.util.Date;

public class Xnotimasreq implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.notimasreqcd
     *
     * @mbg.generated
     */
    private String notimasreqcd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.chacd
     *
     * @mbg.generated
     */
    private String chacd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.reqdate
     *
     * @mbg.generated
     */
    private String reqdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.masmonth
     *
     * @mbg.generated
     */
    private String masmonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.zipcode
     *
     * @mbg.generated
     */
    private String zipcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.address1
     *
     * @mbg.generated
     */
    private String address1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.address2
     *
     * @mbg.generated
     */
    private String address2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.reqname
     *
     * @mbg.generated
     */
    private String reqname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.reqhp
     *
     * @mbg.generated
     */
    private String reqhp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.sortty
     *
     * @mbg.generated
     */
    private String sortty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.reqst
     *
     * @mbg.generated
     */
    private String reqst;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.regdt
     *
     * @mbg.generated
     */
    private Date regdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.sendcnt
     *
     * @mbg.generated
     */
    private Integer sendcnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.senddt
     *
     * @mbg.generated
     */
    private Date senddt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.billno
     *
     * @mbg.generated
     */
    private String billno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.rcusgubn
     *
     * @mbg.generated
     */
    private String rcusgubn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.cusgubna
     *
     * @mbg.generated
     */
    private String cusgubna;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.cusgubnb
     *
     * @mbg.generated
     */
    private String cusgubnb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.billgubn
     *
     * @mbg.generated
     */
    private String billgubn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.sendfileseq
     *
     * @mbg.generated
     */
    private String sendfileseq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.sort_1_cd
     *
     * @mbg.generated
     */
    private String sort1Cd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.sort_2_cd
     *
     * @mbg.generated
     */
    private String sort2Cd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.dlvr_type_cd
     *
     * @mbg.generated
     */
    private String dlvrTypeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.maker
     *
     * @mbg.generated
     */
    private String maker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.makedt
     *
     * @mbg.generated
     */
    private Date makedt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.res_sts_cd
     *
     * @mbg.generated
     */
    private String resStsCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreq.filedt
     *
     * @mbg.generated
     */
    private String filedt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xnotimasreq
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.notimasreqcd
     *
     * @return the value of xnotimasreq.notimasreqcd
     *
     * @mbg.generated
     */
    public String getNotimasreqcd() {
        return notimasreqcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.notimasreqcd
     *
     * @param notimasreqcd the value for xnotimasreq.notimasreqcd
     *
     * @mbg.generated
     */
    public void setNotimasreqcd(String notimasreqcd) {
        this.notimasreqcd = notimasreqcd == null ? null : notimasreqcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.chacd
     *
     * @return the value of xnotimasreq.chacd
     *
     * @mbg.generated
     */
    public String getChacd() {
        return chacd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.chacd
     *
     * @param chacd the value for xnotimasreq.chacd
     *
     * @mbg.generated
     */
    public void setChacd(String chacd) {
        this.chacd = chacd == null ? null : chacd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.reqdate
     *
     * @return the value of xnotimasreq.reqdate
     *
     * @mbg.generated
     */
    public String getReqdate() {
        return reqdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.reqdate
     *
     * @param reqdate the value for xnotimasreq.reqdate
     *
     * @mbg.generated
     */
    public void setReqdate(String reqdate) {
        this.reqdate = reqdate == null ? null : reqdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.masmonth
     *
     * @return the value of xnotimasreq.masmonth
     *
     * @mbg.generated
     */
    public String getMasmonth() {
        return masmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.masmonth
     *
     * @param masmonth the value for xnotimasreq.masmonth
     *
     * @mbg.generated
     */
    public void setMasmonth(String masmonth) {
        this.masmonth = masmonth == null ? null : masmonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.zipcode
     *
     * @return the value of xnotimasreq.zipcode
     *
     * @mbg.generated
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.zipcode
     *
     * @param zipcode the value for xnotimasreq.zipcode
     *
     * @mbg.generated
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.address1
     *
     * @return the value of xnotimasreq.address1
     *
     * @mbg.generated
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.address1
     *
     * @param address1 the value for xnotimasreq.address1
     *
     * @mbg.generated
     */
    public void setAddress1(String address1) {
        this.address1 = address1 == null ? null : address1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.address2
     *
     * @return the value of xnotimasreq.address2
     *
     * @mbg.generated
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.address2
     *
     * @param address2 the value for xnotimasreq.address2
     *
     * @mbg.generated
     */
    public void setAddress2(String address2) {
        this.address2 = address2 == null ? null : address2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.reqname
     *
     * @return the value of xnotimasreq.reqname
     *
     * @mbg.generated
     */
    public String getReqname() {
        return reqname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.reqname
     *
     * @param reqname the value for xnotimasreq.reqname
     *
     * @mbg.generated
     */
    public void setReqname(String reqname) {
        this.reqname = reqname == null ? null : reqname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.reqhp
     *
     * @return the value of xnotimasreq.reqhp
     *
     * @mbg.generated
     */
    public String getReqhp() {
        return reqhp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.reqhp
     *
     * @param reqhp the value for xnotimasreq.reqhp
     *
     * @mbg.generated
     */
    public void setReqhp(String reqhp) {
        this.reqhp = reqhp == null ? null : reqhp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.sortty
     *
     * @return the value of xnotimasreq.sortty
     *
     * @mbg.generated
     */
    public String getSortty() {
        return sortty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.sortty
     *
     * @param sortty the value for xnotimasreq.sortty
     *
     * @mbg.generated
     */
    public void setSortty(String sortty) {
        this.sortty = sortty == null ? null : sortty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.remark
     *
     * @return the value of xnotimasreq.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.remark
     *
     * @param remark the value for xnotimasreq.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.reqst
     *
     * @return the value of xnotimasreq.reqst
     *
     * @mbg.generated
     */
    public String getReqst() {
        return reqst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.reqst
     *
     * @param reqst the value for xnotimasreq.reqst
     *
     * @mbg.generated
     */
    public void setReqst(String reqst) {
        this.reqst = reqst == null ? null : reqst.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.regdt
     *
     * @return the value of xnotimasreq.regdt
     *
     * @mbg.generated
     */
    public Date getRegdt() {
        return regdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.regdt
     *
     * @param regdt the value for xnotimasreq.regdt
     *
     * @mbg.generated
     */
    public void setRegdt(Date regdt) {
        this.regdt = regdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.sendcnt
     *
     * @return the value of xnotimasreq.sendcnt
     *
     * @mbg.generated
     */
    public Integer getSendcnt() {
        return sendcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.sendcnt
     *
     * @param sendcnt the value for xnotimasreq.sendcnt
     *
     * @mbg.generated
     */
    public void setSendcnt(Integer sendcnt) {
        this.sendcnt = sendcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.senddt
     *
     * @return the value of xnotimasreq.senddt
     *
     * @mbg.generated
     */
    public Date getSenddt() {
        return senddt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.senddt
     *
     * @param senddt the value for xnotimasreq.senddt
     *
     * @mbg.generated
     */
    public void setSenddt(Date senddt) {
        this.senddt = senddt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.billno
     *
     * @return the value of xnotimasreq.billno
     *
     * @mbg.generated
     */
    public String getBillno() {
        return billno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.billno
     *
     * @param billno the value for xnotimasreq.billno
     *
     * @mbg.generated
     */
    public void setBillno(String billno) {
        this.billno = billno == null ? null : billno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.rcusgubn
     *
     * @return the value of xnotimasreq.rcusgubn
     *
     * @mbg.generated
     */
    public String getRcusgubn() {
        return rcusgubn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.rcusgubn
     *
     * @param rcusgubn the value for xnotimasreq.rcusgubn
     *
     * @mbg.generated
     */
    public void setRcusgubn(String rcusgubn) {
        this.rcusgubn = rcusgubn == null ? null : rcusgubn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.cusgubna
     *
     * @return the value of xnotimasreq.cusgubna
     *
     * @mbg.generated
     */
    public String getCusgubna() {
        return cusgubna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.cusgubna
     *
     * @param cusgubna the value for xnotimasreq.cusgubna
     *
     * @mbg.generated
     */
    public void setCusgubna(String cusgubna) {
        this.cusgubna = cusgubna == null ? null : cusgubna.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.cusgubnb
     *
     * @return the value of xnotimasreq.cusgubnb
     *
     * @mbg.generated
     */
    public String getCusgubnb() {
        return cusgubnb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.cusgubnb
     *
     * @param cusgubnb the value for xnotimasreq.cusgubnb
     *
     * @mbg.generated
     */
    public void setCusgubnb(String cusgubnb) {
        this.cusgubnb = cusgubnb == null ? null : cusgubnb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.billgubn
     *
     * @return the value of xnotimasreq.billgubn
     *
     * @mbg.generated
     */
    public String getBillgubn() {
        return billgubn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.billgubn
     *
     * @param billgubn the value for xnotimasreq.billgubn
     *
     * @mbg.generated
     */
    public void setBillgubn(String billgubn) {
        this.billgubn = billgubn == null ? null : billgubn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.sendfileseq
     *
     * @return the value of xnotimasreq.sendfileseq
     *
     * @mbg.generated
     */
    public String getSendfileseq() {
        return sendfileseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.sendfileseq
     *
     * @param sendfileseq the value for xnotimasreq.sendfileseq
     *
     * @mbg.generated
     */
    public void setSendfileseq(String sendfileseq) {
        this.sendfileseq = sendfileseq == null ? null : sendfileseq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.sort_1_cd
     *
     * @return the value of xnotimasreq.sort_1_cd
     *
     * @mbg.generated
     */
    public String getSort1Cd() {
        return sort1Cd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.sort_1_cd
     *
     * @param sort1Cd the value for xnotimasreq.sort_1_cd
     *
     * @mbg.generated
     */
    public void setSort1Cd(String sort1Cd) {
        this.sort1Cd = sort1Cd == null ? null : sort1Cd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.sort_2_cd
     *
     * @return the value of xnotimasreq.sort_2_cd
     *
     * @mbg.generated
     */
    public String getSort2Cd() {
        return sort2Cd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.sort_2_cd
     *
     * @param sort2Cd the value for xnotimasreq.sort_2_cd
     *
     * @mbg.generated
     */
    public void setSort2Cd(String sort2Cd) {
        this.sort2Cd = sort2Cd == null ? null : sort2Cd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.dlvr_type_cd
     *
     * @return the value of xnotimasreq.dlvr_type_cd
     *
     * @mbg.generated
     */
    public String getDlvrTypeCd() {
        return dlvrTypeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.dlvr_type_cd
     *
     * @param dlvrTypeCd the value for xnotimasreq.dlvr_type_cd
     *
     * @mbg.generated
     */
    public void setDlvrTypeCd(String dlvrTypeCd) {
        this.dlvrTypeCd = dlvrTypeCd == null ? null : dlvrTypeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.maker
     *
     * @return the value of xnotimasreq.maker
     *
     * @mbg.generated
     */
    public String getMaker() {
        return maker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.maker
     *
     * @param maker the value for xnotimasreq.maker
     *
     * @mbg.generated
     */
    public void setMaker(String maker) {
        this.maker = maker == null ? null : maker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.makedt
     *
     * @return the value of xnotimasreq.makedt
     *
     * @mbg.generated
     */
    public Date getMakedt() {
        return makedt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.makedt
     *
     * @param makedt the value for xnotimasreq.makedt
     *
     * @mbg.generated
     */
    public void setMakedt(Date makedt) {
        this.makedt = makedt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.res_sts_cd
     *
     * @return the value of xnotimasreq.res_sts_cd
     *
     * @mbg.generated
     */
    public String getResStsCd() {
        return resStsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.res_sts_cd
     *
     * @param resStsCd the value for xnotimasreq.res_sts_cd
     *
     * @mbg.generated
     */
    public void setResStsCd(String resStsCd) {
        this.resStsCd = resStsCd == null ? null : resStsCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreq.filedt
     *
     * @return the value of xnotimasreq.filedt
     *
     * @mbg.generated
     */
    public String getFiledt() {
        return filedt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreq.filedt
     *
     * @param filedt the value for xnotimasreq.filedt
     *
     * @mbg.generated
     */
    public void setFiledt(String filedt) {
        this.filedt = filedt == null ? null : filedt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimasreq
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Xnotimasreq other = (Xnotimasreq) that;
        return (this.getNotimasreqcd() == null ? other.getNotimasreqcd() == null : this.getNotimasreqcd().equals(other.getNotimasreqcd()))
            && (this.getChacd() == null ? other.getChacd() == null : this.getChacd().equals(other.getChacd()))
            && (this.getReqdate() == null ? other.getReqdate() == null : this.getReqdate().equals(other.getReqdate()))
            && (this.getMasmonth() == null ? other.getMasmonth() == null : this.getMasmonth().equals(other.getMasmonth()))
            && (this.getZipcode() == null ? other.getZipcode() == null : this.getZipcode().equals(other.getZipcode()))
            && (this.getAddress1() == null ? other.getAddress1() == null : this.getAddress1().equals(other.getAddress1()))
            && (this.getAddress2() == null ? other.getAddress2() == null : this.getAddress2().equals(other.getAddress2()))
            && (this.getReqname() == null ? other.getReqname() == null : this.getReqname().equals(other.getReqname()))
            && (this.getReqhp() == null ? other.getReqhp() == null : this.getReqhp().equals(other.getReqhp()))
            && (this.getSortty() == null ? other.getSortty() == null : this.getSortty().equals(other.getSortty()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getReqst() == null ? other.getReqst() == null : this.getReqst().equals(other.getReqst()))
            && (this.getRegdt() == null ? other.getRegdt() == null : this.getRegdt().equals(other.getRegdt()))
            && (this.getSendcnt() == null ? other.getSendcnt() == null : this.getSendcnt().equals(other.getSendcnt()))
            && (this.getSenddt() == null ? other.getSenddt() == null : this.getSenddt().equals(other.getSenddt()))
            && (this.getBillno() == null ? other.getBillno() == null : this.getBillno().equals(other.getBillno()))
            && (this.getRcusgubn() == null ? other.getRcusgubn() == null : this.getRcusgubn().equals(other.getRcusgubn()))
            && (this.getCusgubna() == null ? other.getCusgubna() == null : this.getCusgubna().equals(other.getCusgubna()))
            && (this.getCusgubnb() == null ? other.getCusgubnb() == null : this.getCusgubnb().equals(other.getCusgubnb()))
            && (this.getBillgubn() == null ? other.getBillgubn() == null : this.getBillgubn().equals(other.getBillgubn()))
            && (this.getSendfileseq() == null ? other.getSendfileseq() == null : this.getSendfileseq().equals(other.getSendfileseq()))
            && (this.getSort1Cd() == null ? other.getSort1Cd() == null : this.getSort1Cd().equals(other.getSort1Cd()))
            && (this.getSort2Cd() == null ? other.getSort2Cd() == null : this.getSort2Cd().equals(other.getSort2Cd()))
            && (this.getDlvrTypeCd() == null ? other.getDlvrTypeCd() == null : this.getDlvrTypeCd().equals(other.getDlvrTypeCd()))
            && (this.getMaker() == null ? other.getMaker() == null : this.getMaker().equals(other.getMaker()))
            && (this.getMakedt() == null ? other.getMakedt() == null : this.getMakedt().equals(other.getMakedt()))
            && (this.getResStsCd() == null ? other.getResStsCd() == null : this.getResStsCd().equals(other.getResStsCd()))
            && (this.getFiledt() == null ? other.getFiledt() == null : this.getFiledt().equals(other.getFiledt()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimasreq
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getNotimasreqcd() == null) ? 0 : getNotimasreqcd().hashCode());
        result = prime * result + ((getChacd() == null) ? 0 : getChacd().hashCode());
        result = prime * result + ((getReqdate() == null) ? 0 : getReqdate().hashCode());
        result = prime * result + ((getMasmonth() == null) ? 0 : getMasmonth().hashCode());
        result = prime * result + ((getZipcode() == null) ? 0 : getZipcode().hashCode());
        result = prime * result + ((getAddress1() == null) ? 0 : getAddress1().hashCode());
        result = prime * result + ((getAddress2() == null) ? 0 : getAddress2().hashCode());
        result = prime * result + ((getReqname() == null) ? 0 : getReqname().hashCode());
        result = prime * result + ((getReqhp() == null) ? 0 : getReqhp().hashCode());
        result = prime * result + ((getSortty() == null) ? 0 : getSortty().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getReqst() == null) ? 0 : getReqst().hashCode());
        result = prime * result + ((getRegdt() == null) ? 0 : getRegdt().hashCode());
        result = prime * result + ((getSendcnt() == null) ? 0 : getSendcnt().hashCode());
        result = prime * result + ((getSenddt() == null) ? 0 : getSenddt().hashCode());
        result = prime * result + ((getBillno() == null) ? 0 : getBillno().hashCode());
        result = prime * result + ((getRcusgubn() == null) ? 0 : getRcusgubn().hashCode());
        result = prime * result + ((getCusgubna() == null) ? 0 : getCusgubna().hashCode());
        result = prime * result + ((getCusgubnb() == null) ? 0 : getCusgubnb().hashCode());
        result = prime * result + ((getBillgubn() == null) ? 0 : getBillgubn().hashCode());
        result = prime * result + ((getSendfileseq() == null) ? 0 : getSendfileseq().hashCode());
        result = prime * result + ((getSort1Cd() == null) ? 0 : getSort1Cd().hashCode());
        result = prime * result + ((getSort2Cd() == null) ? 0 : getSort2Cd().hashCode());
        result = prime * result + ((getDlvrTypeCd() == null) ? 0 : getDlvrTypeCd().hashCode());
        result = prime * result + ((getMaker() == null) ? 0 : getMaker().hashCode());
        result = prime * result + ((getMakedt() == null) ? 0 : getMakedt().hashCode());
        result = prime * result + ((getResStsCd() == null) ? 0 : getResStsCd().hashCode());
        result = prime * result + ((getFiledt() == null) ? 0 : getFiledt().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimasreq
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", notimasreqcd=").append(notimasreqcd);
        sb.append(", chacd=").append(chacd);
        sb.append(", reqdate=").append(reqdate);
        sb.append(", masmonth=").append(masmonth);
        sb.append(", zipcode=").append(zipcode);
        sb.append(", address1=").append(address1);
        sb.append(", address2=").append(address2);
        sb.append(", reqname=").append(reqname);
        sb.append(", reqhp=").append(reqhp);
        sb.append(", sortty=").append(sortty);
        sb.append(", remark=").append(remark);
        sb.append(", reqst=").append(reqst);
        sb.append(", regdt=").append(regdt);
        sb.append(", sendcnt=").append(sendcnt);
        sb.append(", senddt=").append(senddt);
        sb.append(", billno=").append(billno);
        sb.append(", rcusgubn=").append(rcusgubn);
        sb.append(", cusgubna=").append(cusgubna);
        sb.append(", cusgubnb=").append(cusgubnb);
        sb.append(", billgubn=").append(billgubn);
        sb.append(", sendfileseq=").append(sendfileseq);
        sb.append(", sort1Cd=").append(sort1Cd);
        sb.append(", sort2Cd=").append(sort2Cd);
        sb.append(", dlvrTypeCd=").append(dlvrTypeCd);
        sb.append(", maker=").append(maker);
        sb.append(", makedt=").append(makedt);
        sb.append(", resStsCd=").append(resStsCd);
        sb.append(", filedt=").append(filedt);
        sb.append("]");
        return sb.toString();
    }
}