package kr.co.finger.shinhandamoa.data.table.model;

import java.io.Serializable;

public class XnotimasreqdetKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreqdet.notimasreqcd
     *
     * @mbg.generated
     */
    private String notimasreqcd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnotimasreqdet.seq_no
     *
     * @mbg.generated
     */
    private String seqNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xnotimasreqdet
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreqdet.notimasreqcd
     *
     * @return the value of xnotimasreqdet.notimasreqcd
     *
     * @mbg.generated
     */
    public String getNotimasreqcd() {
        return notimasreqcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreqdet.notimasreqcd
     *
     * @param notimasreqcd the value for xnotimasreqdet.notimasreqcd
     *
     * @mbg.generated
     */
    public void setNotimasreqcd(String notimasreqcd) {
        this.notimasreqcd = notimasreqcd == null ? null : notimasreqcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnotimasreqdet.seq_no
     *
     * @return the value of xnotimasreqdet.seq_no
     *
     * @mbg.generated
     */
    public String getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnotimasreqdet.seq_no
     *
     * @param seqNo the value for xnotimasreqdet.seq_no
     *
     * @mbg.generated
     */
    public void setSeqNo(String seqNo) {
        this.seqNo = seqNo == null ? null : seqNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimasreqdet
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        XnotimasreqdetKey other = (XnotimasreqdetKey) that;
        return (this.getNotimasreqcd() == null ? other.getNotimasreqcd() == null : this.getNotimasreqcd().equals(other.getNotimasreqcd()))
            && (this.getSeqNo() == null ? other.getSeqNo() == null : this.getSeqNo().equals(other.getSeqNo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimasreqdet
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getNotimasreqcd() == null) ? 0 : getNotimasreqcd().hashCode());
        result = prime * result + ((getSeqNo() == null) ? 0 : getSeqNo().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimasreqdet
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", notimasreqcd=").append(notimasreqcd);
        sb.append(", seqNo=").append(seqNo);
        sb.append("]");
        return sb.toString();
    }
}