package kr.co.finger.shinhandamoa.data.table.model;

import java.io.Serializable;
import java.util.Date;

public class Xrcpmas implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.rcpmascd
     *
     * @mbg.generated
     */
    private String rcpmascd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.notimascd
     *
     * @mbg.generated
     */
    private String notimascd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.svecd
     *
     * @mbg.generated
     */
    private String svecd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.chacd
     *
     * @mbg.generated
     */
    private String chacd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.vano
     *
     * @mbg.generated
     */
    private String vano;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.maskey
     *
     * @mbg.generated
     */
    private String maskey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.masmonth
     *
     * @mbg.generated
     */
    private String masmonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.masday
     *
     * @mbg.generated
     */
    private String masday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.cuskey
     *
     * @mbg.generated
     */
    private String cuskey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.cusgubn1
     *
     * @mbg.generated
     */
    private String cusgubn1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.cusgubn2
     *
     * @mbg.generated
     */
    private String cusgubn2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.cusgubn3
     *
     * @mbg.generated
     */
    private String cusgubn3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.cusgubn4
     *
     * @mbg.generated
     */
    private String cusgubn4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.cusname
     *
     * @mbg.generated
     */
    private String cusname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.cushp
     *
     * @mbg.generated
     */
    private String cushp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.cusmail
     *
     * @mbg.generated
     */
    private String cusmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.smsyn
     *
     * @mbg.generated
     */
    private String smsyn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.mailyn
     *
     * @mbg.generated
     */
    private String mailyn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.cusoffno
     *
     * @mbg.generated
     */
    private String cusoffno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.payday
     *
     * @mbg.generated
     */
    private String payday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.paytime
     *
     * @mbg.generated
     */
    private String paytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.bnkmsgno
     *
     * @mbg.generated
     */
    private String bnkmsgno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.ficd
     *
     * @mbg.generated
     */
    private String ficd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.bnkcd
     *
     * @mbg.generated
     */
    private String bnkcd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.bchcd
     *
     * @mbg.generated
     */
    private String bchcd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.rcpusrname
     *
     * @mbg.generated
     */
    private String rcpusrname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.rcpamt
     *
     * @mbg.generated
     */
    private Long rcpamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.occgubn
     *
     * @mbg.generated
     */
    private String occgubn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.mdgubn
     *
     * @mbg.generated
     */
    private String mdgubn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.sucday
     *
     * @mbg.generated
     */
    private String sucday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.suctime
     *
     * @mbg.generated
     */
    private String suctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.canday
     *
     * @mbg.generated
     */
    private String canday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.cantime
     *
     * @mbg.generated
     */
    private String cantime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.trnday
     *
     * @mbg.generated
     */
    private String trnday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.trntime
     *
     * @mbg.generated
     */
    private String trntime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.trncnt
     *
     * @mbg.generated
     */
    private Short trncnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.trnst
     *
     * @mbg.generated
     */
    private String trnst;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.packetno
     *
     * @mbg.generated
     */
    private String packetno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.rcpmasst
     *
     * @mbg.generated
     */
    private String rcpmasst;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.makedt
     *
     * @mbg.generated
     */
    private Date makedt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.maker
     *
     * @mbg.generated
     */
    private String maker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.regdt
     *
     * @mbg.generated
     */
    private Date regdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.chatrty
     *
     * @mbg.generated
     */
    private String chatrty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.cashday
     *
     * @mbg.generated
     */
    private String cashday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.displayyn
     *
     * @mbg.generated
     */
    private String displayyn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xrcpmas.dealseqno
     *
     * @mbg.generated
     */
    private String dealseqno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.rcpmascd
     *
     * @return the value of xrcpmas.rcpmascd
     *
     * @mbg.generated
     */
    public String getRcpmascd() {
        return rcpmascd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.rcpmascd
     *
     * @param rcpmascd the value for xrcpmas.rcpmascd
     *
     * @mbg.generated
     */
    public void setRcpmascd(String rcpmascd) {
        this.rcpmascd = rcpmascd == null ? null : rcpmascd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.notimascd
     *
     * @return the value of xrcpmas.notimascd
     *
     * @mbg.generated
     */
    public String getNotimascd() {
        return notimascd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.notimascd
     *
     * @param notimascd the value for xrcpmas.notimascd
     *
     * @mbg.generated
     */
    public void setNotimascd(String notimascd) {
        this.notimascd = notimascd == null ? null : notimascd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.svecd
     *
     * @return the value of xrcpmas.svecd
     *
     * @mbg.generated
     */
    public String getSvecd() {
        return svecd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.svecd
     *
     * @param svecd the value for xrcpmas.svecd
     *
     * @mbg.generated
     */
    public void setSvecd(String svecd) {
        this.svecd = svecd == null ? null : svecd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.chacd
     *
     * @return the value of xrcpmas.chacd
     *
     * @mbg.generated
     */
    public String getChacd() {
        return chacd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.chacd
     *
     * @param chacd the value for xrcpmas.chacd
     *
     * @mbg.generated
     */
    public void setChacd(String chacd) {
        this.chacd = chacd == null ? null : chacd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.vano
     *
     * @return the value of xrcpmas.vano
     *
     * @mbg.generated
     */
    public String getVano() {
        return vano;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.vano
     *
     * @param vano the value for xrcpmas.vano
     *
     * @mbg.generated
     */
    public void setVano(String vano) {
        this.vano = vano == null ? null : vano.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.maskey
     *
     * @return the value of xrcpmas.maskey
     *
     * @mbg.generated
     */
    public String getMaskey() {
        return maskey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.maskey
     *
     * @param maskey the value for xrcpmas.maskey
     *
     * @mbg.generated
     */
    public void setMaskey(String maskey) {
        this.maskey = maskey == null ? null : maskey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.masmonth
     *
     * @return the value of xrcpmas.masmonth
     *
     * @mbg.generated
     */
    public String getMasmonth() {
        return masmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.masmonth
     *
     * @param masmonth the value for xrcpmas.masmonth
     *
     * @mbg.generated
     */
    public void setMasmonth(String masmonth) {
        this.masmonth = masmonth == null ? null : masmonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.masday
     *
     * @return the value of xrcpmas.masday
     *
     * @mbg.generated
     */
    public String getMasday() {
        return masday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.masday
     *
     * @param masday the value for xrcpmas.masday
     *
     * @mbg.generated
     */
    public void setMasday(String masday) {
        this.masday = masday == null ? null : masday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.cuskey
     *
     * @return the value of xrcpmas.cuskey
     *
     * @mbg.generated
     */
    public String getCuskey() {
        return cuskey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.cuskey
     *
     * @param cuskey the value for xrcpmas.cuskey
     *
     * @mbg.generated
     */
    public void setCuskey(String cuskey) {
        this.cuskey = cuskey == null ? null : cuskey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.cusgubn1
     *
     * @return the value of xrcpmas.cusgubn1
     *
     * @mbg.generated
     */
    public String getCusgubn1() {
        return cusgubn1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.cusgubn1
     *
     * @param cusgubn1 the value for xrcpmas.cusgubn1
     *
     * @mbg.generated
     */
    public void setCusgubn1(String cusgubn1) {
        this.cusgubn1 = cusgubn1 == null ? null : cusgubn1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.cusgubn2
     *
     * @return the value of xrcpmas.cusgubn2
     *
     * @mbg.generated
     */
    public String getCusgubn2() {
        return cusgubn2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.cusgubn2
     *
     * @param cusgubn2 the value for xrcpmas.cusgubn2
     *
     * @mbg.generated
     */
    public void setCusgubn2(String cusgubn2) {
        this.cusgubn2 = cusgubn2 == null ? null : cusgubn2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.cusgubn3
     *
     * @return the value of xrcpmas.cusgubn3
     *
     * @mbg.generated
     */
    public String getCusgubn3() {
        return cusgubn3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.cusgubn3
     *
     * @param cusgubn3 the value for xrcpmas.cusgubn3
     *
     * @mbg.generated
     */
    public void setCusgubn3(String cusgubn3) {
        this.cusgubn3 = cusgubn3 == null ? null : cusgubn3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.cusgubn4
     *
     * @return the value of xrcpmas.cusgubn4
     *
     * @mbg.generated
     */
    public String getCusgubn4() {
        return cusgubn4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.cusgubn4
     *
     * @param cusgubn4 the value for xrcpmas.cusgubn4
     *
     * @mbg.generated
     */
    public void setCusgubn4(String cusgubn4) {
        this.cusgubn4 = cusgubn4 == null ? null : cusgubn4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.cusname
     *
     * @return the value of xrcpmas.cusname
     *
     * @mbg.generated
     */
    public String getCusname() {
        return cusname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.cusname
     *
     * @param cusname the value for xrcpmas.cusname
     *
     * @mbg.generated
     */
    public void setCusname(String cusname) {
        this.cusname = cusname == null ? null : cusname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.cushp
     *
     * @return the value of xrcpmas.cushp
     *
     * @mbg.generated
     */
    public String getCushp() {
        return cushp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.cushp
     *
     * @param cushp the value for xrcpmas.cushp
     *
     * @mbg.generated
     */
    public void setCushp(String cushp) {
        this.cushp = cushp == null ? null : cushp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.cusmail
     *
     * @return the value of xrcpmas.cusmail
     *
     * @mbg.generated
     */
    public String getCusmail() {
        return cusmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.cusmail
     *
     * @param cusmail the value for xrcpmas.cusmail
     *
     * @mbg.generated
     */
    public void setCusmail(String cusmail) {
        this.cusmail = cusmail == null ? null : cusmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.smsyn
     *
     * @return the value of xrcpmas.smsyn
     *
     * @mbg.generated
     */
    public String getSmsyn() {
        return smsyn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.smsyn
     *
     * @param smsyn the value for xrcpmas.smsyn
     *
     * @mbg.generated
     */
    public void setSmsyn(String smsyn) {
        this.smsyn = smsyn == null ? null : smsyn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.mailyn
     *
     * @return the value of xrcpmas.mailyn
     *
     * @mbg.generated
     */
    public String getMailyn() {
        return mailyn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.mailyn
     *
     * @param mailyn the value for xrcpmas.mailyn
     *
     * @mbg.generated
     */
    public void setMailyn(String mailyn) {
        this.mailyn = mailyn == null ? null : mailyn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.cusoffno
     *
     * @return the value of xrcpmas.cusoffno
     *
     * @mbg.generated
     */
    public String getCusoffno() {
        return cusoffno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.cusoffno
     *
     * @param cusoffno the value for xrcpmas.cusoffno
     *
     * @mbg.generated
     */
    public void setCusoffno(String cusoffno) {
        this.cusoffno = cusoffno == null ? null : cusoffno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.payday
     *
     * @return the value of xrcpmas.payday
     *
     * @mbg.generated
     */
    public String getPayday() {
        return payday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.payday
     *
     * @param payday the value for xrcpmas.payday
     *
     * @mbg.generated
     */
    public void setPayday(String payday) {
        this.payday = payday == null ? null : payday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.paytime
     *
     * @return the value of xrcpmas.paytime
     *
     * @mbg.generated
     */
    public String getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.paytime
     *
     * @param paytime the value for xrcpmas.paytime
     *
     * @mbg.generated
     */
    public void setPaytime(String paytime) {
        this.paytime = paytime == null ? null : paytime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.bnkmsgno
     *
     * @return the value of xrcpmas.bnkmsgno
     *
     * @mbg.generated
     */
    public String getBnkmsgno() {
        return bnkmsgno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.bnkmsgno
     *
     * @param bnkmsgno the value for xrcpmas.bnkmsgno
     *
     * @mbg.generated
     */
    public void setBnkmsgno(String bnkmsgno) {
        this.bnkmsgno = bnkmsgno == null ? null : bnkmsgno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.ficd
     *
     * @return the value of xrcpmas.ficd
     *
     * @mbg.generated
     */
    public String getFicd() {
        return ficd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.ficd
     *
     * @param ficd the value for xrcpmas.ficd
     *
     * @mbg.generated
     */
    public void setFicd(String ficd) {
        this.ficd = ficd == null ? null : ficd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.bnkcd
     *
     * @return the value of xrcpmas.bnkcd
     *
     * @mbg.generated
     */
    public String getBnkcd() {
        return bnkcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.bnkcd
     *
     * @param bnkcd the value for xrcpmas.bnkcd
     *
     * @mbg.generated
     */
    public void setBnkcd(String bnkcd) {
        this.bnkcd = bnkcd == null ? null : bnkcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.bchcd
     *
     * @return the value of xrcpmas.bchcd
     *
     * @mbg.generated
     */
    public String getBchcd() {
        return bchcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.bchcd
     *
     * @param bchcd the value for xrcpmas.bchcd
     *
     * @mbg.generated
     */
    public void setBchcd(String bchcd) {
        this.bchcd = bchcd == null ? null : bchcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.rcpusrname
     *
     * @return the value of xrcpmas.rcpusrname
     *
     * @mbg.generated
     */
    public String getRcpusrname() {
        return rcpusrname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.rcpusrname
     *
     * @param rcpusrname the value for xrcpmas.rcpusrname
     *
     * @mbg.generated
     */
    public void setRcpusrname(String rcpusrname) {
        this.rcpusrname = rcpusrname == null ? null : rcpusrname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.rcpamt
     *
     * @return the value of xrcpmas.rcpamt
     *
     * @mbg.generated
     */
    public Long getRcpamt() {
        return rcpamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.rcpamt
     *
     * @param rcpamt the value for xrcpmas.rcpamt
     *
     * @mbg.generated
     */
    public void setRcpamt(Long rcpamt) {
        this.rcpamt = rcpamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.occgubn
     *
     * @return the value of xrcpmas.occgubn
     *
     * @mbg.generated
     */
    public String getOccgubn() {
        return occgubn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.occgubn
     *
     * @param occgubn the value for xrcpmas.occgubn
     *
     * @mbg.generated
     */
    public void setOccgubn(String occgubn) {
        this.occgubn = occgubn == null ? null : occgubn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.mdgubn
     *
     * @return the value of xrcpmas.mdgubn
     *
     * @mbg.generated
     */
    public String getMdgubn() {
        return mdgubn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.mdgubn
     *
     * @param mdgubn the value for xrcpmas.mdgubn
     *
     * @mbg.generated
     */
    public void setMdgubn(String mdgubn) {
        this.mdgubn = mdgubn == null ? null : mdgubn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.sucday
     *
     * @return the value of xrcpmas.sucday
     *
     * @mbg.generated
     */
    public String getSucday() {
        return sucday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.sucday
     *
     * @param sucday the value for xrcpmas.sucday
     *
     * @mbg.generated
     */
    public void setSucday(String sucday) {
        this.sucday = sucday == null ? null : sucday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.suctime
     *
     * @return the value of xrcpmas.suctime
     *
     * @mbg.generated
     */
    public String getSuctime() {
        return suctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.suctime
     *
     * @param suctime the value for xrcpmas.suctime
     *
     * @mbg.generated
     */
    public void setSuctime(String suctime) {
        this.suctime = suctime == null ? null : suctime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.canday
     *
     * @return the value of xrcpmas.canday
     *
     * @mbg.generated
     */
    public String getCanday() {
        return canday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.canday
     *
     * @param canday the value for xrcpmas.canday
     *
     * @mbg.generated
     */
    public void setCanday(String canday) {
        this.canday = canday == null ? null : canday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.cantime
     *
     * @return the value of xrcpmas.cantime
     *
     * @mbg.generated
     */
    public String getCantime() {
        return cantime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.cantime
     *
     * @param cantime the value for xrcpmas.cantime
     *
     * @mbg.generated
     */
    public void setCantime(String cantime) {
        this.cantime = cantime == null ? null : cantime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.trnday
     *
     * @return the value of xrcpmas.trnday
     *
     * @mbg.generated
     */
    public String getTrnday() {
        return trnday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.trnday
     *
     * @param trnday the value for xrcpmas.trnday
     *
     * @mbg.generated
     */
    public void setTrnday(String trnday) {
        this.trnday = trnday == null ? null : trnday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.trntime
     *
     * @return the value of xrcpmas.trntime
     *
     * @mbg.generated
     */
    public String getTrntime() {
        return trntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.trntime
     *
     * @param trntime the value for xrcpmas.trntime
     *
     * @mbg.generated
     */
    public void setTrntime(String trntime) {
        this.trntime = trntime == null ? null : trntime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.trncnt
     *
     * @return the value of xrcpmas.trncnt
     *
     * @mbg.generated
     */
    public Short getTrncnt() {
        return trncnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.trncnt
     *
     * @param trncnt the value for xrcpmas.trncnt
     *
     * @mbg.generated
     */
    public void setTrncnt(Short trncnt) {
        this.trncnt = trncnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.trnst
     *
     * @return the value of xrcpmas.trnst
     *
     * @mbg.generated
     */
    public String getTrnst() {
        return trnst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.trnst
     *
     * @param trnst the value for xrcpmas.trnst
     *
     * @mbg.generated
     */
    public void setTrnst(String trnst) {
        this.trnst = trnst == null ? null : trnst.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.packetno
     *
     * @return the value of xrcpmas.packetno
     *
     * @mbg.generated
     */
    public String getPacketno() {
        return packetno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.packetno
     *
     * @param packetno the value for xrcpmas.packetno
     *
     * @mbg.generated
     */
    public void setPacketno(String packetno) {
        this.packetno = packetno == null ? null : packetno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.rcpmasst
     *
     * @return the value of xrcpmas.rcpmasst
     *
     * @mbg.generated
     */
    public String getRcpmasst() {
        return rcpmasst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.rcpmasst
     *
     * @param rcpmasst the value for xrcpmas.rcpmasst
     *
     * @mbg.generated
     */
    public void setRcpmasst(String rcpmasst) {
        this.rcpmasst = rcpmasst == null ? null : rcpmasst.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.makedt
     *
     * @return the value of xrcpmas.makedt
     *
     * @mbg.generated
     */
    public Date getMakedt() {
        return makedt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.makedt
     *
     * @param makedt the value for xrcpmas.makedt
     *
     * @mbg.generated
     */
    public void setMakedt(Date makedt) {
        this.makedt = makedt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.maker
     *
     * @return the value of xrcpmas.maker
     *
     * @mbg.generated
     */
    public String getMaker() {
        return maker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.maker
     *
     * @param maker the value for xrcpmas.maker
     *
     * @mbg.generated
     */
    public void setMaker(String maker) {
        this.maker = maker == null ? null : maker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.regdt
     *
     * @return the value of xrcpmas.regdt
     *
     * @mbg.generated
     */
    public Date getRegdt() {
        return regdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.regdt
     *
     * @param regdt the value for xrcpmas.regdt
     *
     * @mbg.generated
     */
    public void setRegdt(Date regdt) {
        this.regdt = regdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.chatrty
     *
     * @return the value of xrcpmas.chatrty
     *
     * @mbg.generated
     */
    public String getChatrty() {
        return chatrty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.chatrty
     *
     * @param chatrty the value for xrcpmas.chatrty
     *
     * @mbg.generated
     */
    public void setChatrty(String chatrty) {
        this.chatrty = chatrty == null ? null : chatrty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.cashday
     *
     * @return the value of xrcpmas.cashday
     *
     * @mbg.generated
     */
    public String getCashday() {
        return cashday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.cashday
     *
     * @param cashday the value for xrcpmas.cashday
     *
     * @mbg.generated
     */
    public void setCashday(String cashday) {
        this.cashday = cashday == null ? null : cashday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.displayyn
     *
     * @return the value of xrcpmas.displayyn
     *
     * @mbg.generated
     */
    public String getDisplayyn() {
        return displayyn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.displayyn
     *
     * @param displayyn the value for xrcpmas.displayyn
     *
     * @mbg.generated
     */
    public void setDisplayyn(String displayyn) {
        this.displayyn = displayyn == null ? null : displayyn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xrcpmas.dealseqno
     *
     * @return the value of xrcpmas.dealseqno
     *
     * @mbg.generated
     */
    public String getDealseqno() {
        return dealseqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xrcpmas.dealseqno
     *
     * @param dealseqno the value for xrcpmas.dealseqno
     *
     * @mbg.generated
     */
    public void setDealseqno(String dealseqno) {
        this.dealseqno = dealseqno == null ? null : dealseqno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Xrcpmas other = (Xrcpmas) that;
        return (this.getRcpmascd() == null ? other.getRcpmascd() == null : this.getRcpmascd().equals(other.getRcpmascd()))
            && (this.getNotimascd() == null ? other.getNotimascd() == null : this.getNotimascd().equals(other.getNotimascd()))
            && (this.getSvecd() == null ? other.getSvecd() == null : this.getSvecd().equals(other.getSvecd()))
            && (this.getChacd() == null ? other.getChacd() == null : this.getChacd().equals(other.getChacd()))
            && (this.getVano() == null ? other.getVano() == null : this.getVano().equals(other.getVano()))
            && (this.getMaskey() == null ? other.getMaskey() == null : this.getMaskey().equals(other.getMaskey()))
            && (this.getMasmonth() == null ? other.getMasmonth() == null : this.getMasmonth().equals(other.getMasmonth()))
            && (this.getMasday() == null ? other.getMasday() == null : this.getMasday().equals(other.getMasday()))
            && (this.getCuskey() == null ? other.getCuskey() == null : this.getCuskey().equals(other.getCuskey()))
            && (this.getCusgubn1() == null ? other.getCusgubn1() == null : this.getCusgubn1().equals(other.getCusgubn1()))
            && (this.getCusgubn2() == null ? other.getCusgubn2() == null : this.getCusgubn2().equals(other.getCusgubn2()))
            && (this.getCusgubn3() == null ? other.getCusgubn3() == null : this.getCusgubn3().equals(other.getCusgubn3()))
            && (this.getCusgubn4() == null ? other.getCusgubn4() == null : this.getCusgubn4().equals(other.getCusgubn4()))
            && (this.getCusname() == null ? other.getCusname() == null : this.getCusname().equals(other.getCusname()))
            && (this.getCushp() == null ? other.getCushp() == null : this.getCushp().equals(other.getCushp()))
            && (this.getCusmail() == null ? other.getCusmail() == null : this.getCusmail().equals(other.getCusmail()))
            && (this.getSmsyn() == null ? other.getSmsyn() == null : this.getSmsyn().equals(other.getSmsyn()))
            && (this.getMailyn() == null ? other.getMailyn() == null : this.getMailyn().equals(other.getMailyn()))
            && (this.getCusoffno() == null ? other.getCusoffno() == null : this.getCusoffno().equals(other.getCusoffno()))
            && (this.getPayday() == null ? other.getPayday() == null : this.getPayday().equals(other.getPayday()))
            && (this.getPaytime() == null ? other.getPaytime() == null : this.getPaytime().equals(other.getPaytime()))
            && (this.getBnkmsgno() == null ? other.getBnkmsgno() == null : this.getBnkmsgno().equals(other.getBnkmsgno()))
            && (this.getFicd() == null ? other.getFicd() == null : this.getFicd().equals(other.getFicd()))
            && (this.getBnkcd() == null ? other.getBnkcd() == null : this.getBnkcd().equals(other.getBnkcd()))
            && (this.getBchcd() == null ? other.getBchcd() == null : this.getBchcd().equals(other.getBchcd()))
            && (this.getRcpusrname() == null ? other.getRcpusrname() == null : this.getRcpusrname().equals(other.getRcpusrname()))
            && (this.getRcpamt() == null ? other.getRcpamt() == null : this.getRcpamt().equals(other.getRcpamt()))
            && (this.getOccgubn() == null ? other.getOccgubn() == null : this.getOccgubn().equals(other.getOccgubn()))
            && (this.getMdgubn() == null ? other.getMdgubn() == null : this.getMdgubn().equals(other.getMdgubn()))
            && (this.getSucday() == null ? other.getSucday() == null : this.getSucday().equals(other.getSucday()))
            && (this.getSuctime() == null ? other.getSuctime() == null : this.getSuctime().equals(other.getSuctime()))
            && (this.getCanday() == null ? other.getCanday() == null : this.getCanday().equals(other.getCanday()))
            && (this.getCantime() == null ? other.getCantime() == null : this.getCantime().equals(other.getCantime()))
            && (this.getTrnday() == null ? other.getTrnday() == null : this.getTrnday().equals(other.getTrnday()))
            && (this.getTrntime() == null ? other.getTrntime() == null : this.getTrntime().equals(other.getTrntime()))
            && (this.getTrncnt() == null ? other.getTrncnt() == null : this.getTrncnt().equals(other.getTrncnt()))
            && (this.getTrnst() == null ? other.getTrnst() == null : this.getTrnst().equals(other.getTrnst()))
            && (this.getPacketno() == null ? other.getPacketno() == null : this.getPacketno().equals(other.getPacketno()))
            && (this.getRcpmasst() == null ? other.getRcpmasst() == null : this.getRcpmasst().equals(other.getRcpmasst()))
            && (this.getMakedt() == null ? other.getMakedt() == null : this.getMakedt().equals(other.getMakedt()))
            && (this.getMaker() == null ? other.getMaker() == null : this.getMaker().equals(other.getMaker()))
            && (this.getRegdt() == null ? other.getRegdt() == null : this.getRegdt().equals(other.getRegdt()))
            && (this.getChatrty() == null ? other.getChatrty() == null : this.getChatrty().equals(other.getChatrty()))
            && (this.getCashday() == null ? other.getCashday() == null : this.getCashday().equals(other.getCashday()))
            && (this.getDisplayyn() == null ? other.getDisplayyn() == null : this.getDisplayyn().equals(other.getDisplayyn()))
            && (this.getDealseqno() == null ? other.getDealseqno() == null : this.getDealseqno().equals(other.getDealseqno()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRcpmascd() == null) ? 0 : getRcpmascd().hashCode());
        result = prime * result + ((getNotimascd() == null) ? 0 : getNotimascd().hashCode());
        result = prime * result + ((getSvecd() == null) ? 0 : getSvecd().hashCode());
        result = prime * result + ((getChacd() == null) ? 0 : getChacd().hashCode());
        result = prime * result + ((getVano() == null) ? 0 : getVano().hashCode());
        result = prime * result + ((getMaskey() == null) ? 0 : getMaskey().hashCode());
        result = prime * result + ((getMasmonth() == null) ? 0 : getMasmonth().hashCode());
        result = prime * result + ((getMasday() == null) ? 0 : getMasday().hashCode());
        result = prime * result + ((getCuskey() == null) ? 0 : getCuskey().hashCode());
        result = prime * result + ((getCusgubn1() == null) ? 0 : getCusgubn1().hashCode());
        result = prime * result + ((getCusgubn2() == null) ? 0 : getCusgubn2().hashCode());
        result = prime * result + ((getCusgubn3() == null) ? 0 : getCusgubn3().hashCode());
        result = prime * result + ((getCusgubn4() == null) ? 0 : getCusgubn4().hashCode());
        result = prime * result + ((getCusname() == null) ? 0 : getCusname().hashCode());
        result = prime * result + ((getCushp() == null) ? 0 : getCushp().hashCode());
        result = prime * result + ((getCusmail() == null) ? 0 : getCusmail().hashCode());
        result = prime * result + ((getSmsyn() == null) ? 0 : getSmsyn().hashCode());
        result = prime * result + ((getMailyn() == null) ? 0 : getMailyn().hashCode());
        result = prime * result + ((getCusoffno() == null) ? 0 : getCusoffno().hashCode());
        result = prime * result + ((getPayday() == null) ? 0 : getPayday().hashCode());
        result = prime * result + ((getPaytime() == null) ? 0 : getPaytime().hashCode());
        result = prime * result + ((getBnkmsgno() == null) ? 0 : getBnkmsgno().hashCode());
        result = prime * result + ((getFicd() == null) ? 0 : getFicd().hashCode());
        result = prime * result + ((getBnkcd() == null) ? 0 : getBnkcd().hashCode());
        result = prime * result + ((getBchcd() == null) ? 0 : getBchcd().hashCode());
        result = prime * result + ((getRcpusrname() == null) ? 0 : getRcpusrname().hashCode());
        result = prime * result + ((getRcpamt() == null) ? 0 : getRcpamt().hashCode());
        result = prime * result + ((getOccgubn() == null) ? 0 : getOccgubn().hashCode());
        result = prime * result + ((getMdgubn() == null) ? 0 : getMdgubn().hashCode());
        result = prime * result + ((getSucday() == null) ? 0 : getSucday().hashCode());
        result = prime * result + ((getSuctime() == null) ? 0 : getSuctime().hashCode());
        result = prime * result + ((getCanday() == null) ? 0 : getCanday().hashCode());
        result = prime * result + ((getCantime() == null) ? 0 : getCantime().hashCode());
        result = prime * result + ((getTrnday() == null) ? 0 : getTrnday().hashCode());
        result = prime * result + ((getTrntime() == null) ? 0 : getTrntime().hashCode());
        result = prime * result + ((getTrncnt() == null) ? 0 : getTrncnt().hashCode());
        result = prime * result + ((getTrnst() == null) ? 0 : getTrnst().hashCode());
        result = prime * result + ((getPacketno() == null) ? 0 : getPacketno().hashCode());
        result = prime * result + ((getRcpmasst() == null) ? 0 : getRcpmasst().hashCode());
        result = prime * result + ((getMakedt() == null) ? 0 : getMakedt().hashCode());
        result = prime * result + ((getMaker() == null) ? 0 : getMaker().hashCode());
        result = prime * result + ((getRegdt() == null) ? 0 : getRegdt().hashCode());
        result = prime * result + ((getChatrty() == null) ? 0 : getChatrty().hashCode());
        result = prime * result + ((getCashday() == null) ? 0 : getCashday().hashCode());
        result = prime * result + ((getDisplayyn() == null) ? 0 : getDisplayyn().hashCode());
        result = prime * result + ((getDealseqno() == null) ? 0 : getDealseqno().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rcpmascd=").append(rcpmascd);
        sb.append(", notimascd=").append(notimascd);
        sb.append(", svecd=").append(svecd);
        sb.append(", chacd=").append(chacd);
        sb.append(", vano=").append(vano);
        sb.append(", maskey=").append(maskey);
        sb.append(", masmonth=").append(masmonth);
        sb.append(", masday=").append(masday);
        sb.append(", cuskey=").append(cuskey);
        sb.append(", cusgubn1=").append(cusgubn1);
        sb.append(", cusgubn2=").append(cusgubn2);
        sb.append(", cusgubn3=").append(cusgubn3);
        sb.append(", cusgubn4=").append(cusgubn4);
        sb.append(", cusname=").append(cusname);
        sb.append(", cushp=").append(cushp);
        sb.append(", cusmail=").append(cusmail);
        sb.append(", smsyn=").append(smsyn);
        sb.append(", mailyn=").append(mailyn);
        sb.append(", cusoffno=").append(cusoffno);
        sb.append(", payday=").append(payday);
        sb.append(", paytime=").append(paytime);
        sb.append(", bnkmsgno=").append(bnkmsgno);
        sb.append(", ficd=").append(ficd);
        sb.append(", bnkcd=").append(bnkcd);
        sb.append(", bchcd=").append(bchcd);
        sb.append(", rcpusrname=").append(rcpusrname);
        sb.append(", rcpamt=").append(rcpamt);
        sb.append(", occgubn=").append(occgubn);
        sb.append(", mdgubn=").append(mdgubn);
        sb.append(", sucday=").append(sucday);
        sb.append(", suctime=").append(suctime);
        sb.append(", canday=").append(canday);
        sb.append(", cantime=").append(cantime);
        sb.append(", trnday=").append(trnday);
        sb.append(", trntime=").append(trntime);
        sb.append(", trncnt=").append(trncnt);
        sb.append(", trnst=").append(trnst);
        sb.append(", packetno=").append(packetno);
        sb.append(", rcpmasst=").append(rcpmasst);
        sb.append(", makedt=").append(makedt);
        sb.append(", maker=").append(maker);
        sb.append(", regdt=").append(regdt);
        sb.append(", chatrty=").append(chatrty);
        sb.append(", cashday=").append(cashday);
        sb.append(", displayyn=").append(displayyn);
        sb.append(", dealseqno=").append(dealseqno);
        sb.append("]");
        return sb.toString();
    }
}