CREATE TABLE FW_CODE
(
  CODE CHAR(6) NOT NULL,
  CODE_GROUP CHAR(2) NOT NULL,
  NAME VARCHAR2(20),
  DESCRIPTION VARCHAR2(2000),
  MODIFY_USER VARCHAR2(100),
  MODIFY_DATE DATE
);
COMMENT ON COLUMN FW_CODE.CODE IS '코드';
COMMENT ON COLUMN FW_CODE.CODE_GROUP IS '그룹코드';
COMMENT ON COLUMN FW_CODE.NAME IS '코드명';
COMMENT ON COLUMN FW_CODE.DESCRIPTION IS '설명';
COMMENT ON COLUMN FW_CODE.MODIFY_USER IS '변경자';
COMMENT ON COLUMN FW_CODE.MODIFY_DATE IS '변경일시';
COMMENT ON TABLE FW_CODE IS '프레임워크/공통코드';

INSERT INTO FW_CODE (CODE, CODE_GROUP, NAME, DESCRIPTION, MODIFY_USER, MODIFY_DATE) VALUES ('A00000', 'A0', '동의', 'NULL', 'wisehouse', TO_DATE('2018-09-13 05:24:31', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO FW_CODE (CODE, CODE_GROUP, NAME, DESCRIPTION, MODIFY_USER, MODIFY_DATE) VALUES ('A00001', 'A0', '미동의', 'NULL', 'wisehouse', TO_DATE('2018-09-13 05:24:31', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO FW_CODE (CODE, CODE_GROUP, NAME, DESCRIPTION, MODIFY_USER, MODIFY_DATE) VALUES ('A00002', 'A0', '승인대기', 'NULL', 'wisehouse', TO_DATE('2018-09-13 05:24:31', 'YYYY-MM-DD HH24:MI:SS'));

