-- --------------------------------------------------------------------------------
-- 출금이체 테이블
-- --------------------------------------------------------------------------------

CREATE TABLE "KFTC_WITHDRAW"
(	"ID" CHAR(20 BYTE) NOT NULL ENABLE,
   "EB21_ID" CHAR(10 BYTE),
   "EB22_ID" CHAR(10 BYTE),
   "DATA_NO" CHAR(8 BYTE),
   "PAYER_KFTC_CODE" CHAR(3 BYTE) NOT NULL ENABLE,
   "PAYER_ACCOUNT_NO" VARCHAR2(16 BYTE) NOT NULL ENABLE,
   "AMOUNT" NUMBER(14,0) NOT NULL ENABLE,
   "PAYER_IDENTITY_NO" VARCHAR2(20 BYTE) NOT NULL ENABLE,
   "SUCCESS_YN" CHAR(1 BYTE),
   "RESULT_CD" CHAR(6 BYTE),
   "REMARK" CHAR(16 CHAR) NOT NULL ENABLE,
   "FUND_TYPE_CD" CHAR(6 BYTE) NOT NULL ENABLE,
   "PAYER_NO" CHAR(20 BYTE) NOT NULL ENABLE,
   "USER_AREA" VARCHAR2(5 BYTE),
   "WITHDRAW_TYPE_CD" CHAR(6 BYTE) NOT NULL ENABLE,
   "CONTACT_NO" VARCHAR2(12 BYTE) NOT NULL ENABLE,
   "CREATE_DATE" DATE NOT NULL ENABLE,
   "CREATE_USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
   "STATUS_CD" CHAR(6 BYTE) NOT NULL ENABLE,
  CONSTRAINT "KFTC_WITHDRAW_PK" PRIMARY KEY ("ID")
);

COMMENT ON COLUMN "KFTC_WITHDRAW"."ID" IS '아이디';
COMMENT ON COLUMN "KFTC_WITHDRAW"."DATA_NO" IS '데이터 일련번호';
COMMENT ON COLUMN "KFTC_WITHDRAW"."PAYER_KFTC_CODE" IS '출금참가기관점코드';
COMMENT ON COLUMN "KFTC_WITHDRAW"."PAYER_ACCOUNT_NO" IS '출금계좌번호';
COMMENT ON COLUMN "KFTC_WITHDRAW"."AMOUNT" IS '출금의뢰금액';
COMMENT ON COLUMN "KFTC_WITHDRAW"."PAYER_IDENTITY_NO" IS '예금주 생년월일 또는 사업자등록번호';
COMMENT ON COLUMN "KFTC_WITHDRAW"."SUCCESS_YN" IS '성공여부';
COMMENT ON COLUMN "KFTC_WITHDRAW"."RESULT_CD" IS '결과코드(K4)';
COMMENT ON COLUMN "KFTC_WITHDRAW"."REMARK" IS '적요';
COMMENT ON COLUMN "KFTC_WITHDRAW"."FUND_TYPE_CD" IS '자금종류 (K2)';
COMMENT ON COLUMN "KFTC_WITHDRAW"."PAYER_NO" IS '납부자번호';
COMMENT ON COLUMN "KFTC_WITHDRAW"."USER_AREA" IS '이용기관사용영역';
COMMENT ON COLUMN "KFTC_WITHDRAW"."WITHDRAW_TYPE_CD" IS '출금형태 (K5)';
COMMENT ON COLUMN "KFTC_WITHDRAW"."CONTACT_NO" IS '전화번호';
COMMENT ON COLUMN "KFTC_WITHDRAW"."CREATE_DATE" IS '등록일시';
COMMENT ON COLUMN "KFTC_WITHDRAW"."CREATE_USER" IS '등록자';
COMMENT ON COLUMN "KFTC_WITHDRAW"."STATUS_CD" IS '상태코드 (K0)';

CREATE SEQUENCE "KFTC_WITHDRAW_ID"
  MINVALUE 10000000000000000000
  MAXVALUE 99999999999999999999
  INCREMENT BY 1
  START WITH 10000000000000000000
  CACHE 20
  NOORDER
  NOCYCLE;

-- --------------------------------------------------------------------------------
-- EB21 전문 테이블
-- --------------------------------------------------------------------------------
CREATE TABLE "KFTC_EB21"
(
  "ID"                 CHAR(10 BYTE)      NOT NULL ENABLE,
  "CLIENT_ID"          CHAR(10 BYTE)      NOT NULL ENABLE,
  "FILE_NAME"          CHAR(8 BYTE)       NOT NULL ENABLE,
  "WITHDRAW_DATE"      CHAR(8 BYTE)       NOT NULL ENABLE,
  "BANK_CODE"          CHAR(1 BYTE)       NOT NULL ENABLE,
  "ACCOUNT_NO"         VARCHAR2(16 BYTE)  NOT NULL ENABLE,
  "TOTAL_RECORD_COUNT" NUMBER(9, 0)       NOT NULL ENABLE,
  "FULL_COUNT"         NUMBER(9, 0)       NOT NULL ENABLE,
  "FULL_AMOUNT"        NUMBER(14, 0)      NOT NULL ENABLE,
  "CREATE_DATE"        DATE               NOT NULL ENABLE,
  "CREATE_USER"        VARCHAR2(100 BYTE) NOT NULL ENABLE,
  CONSTRAINT "KFTC_EB21_PK" PRIMARY KEY ("ID")
);

COMMENT ON COLUMN "KFTC_EB21"."ID" IS '아이디';
COMMENT ON COLUMN "KFTC_EB21"."CLIENT_ID" IS '금결원 CMS 기관코드';
COMMENT ON COLUMN "KFTC_EB21"."FILE_NAME" IS '파일(EB21MMDD)';
COMMENT ON COLUMN "KFTC_EB21"."WITHDRAW_DATE" IS '출금일(YYMMDD)';
COMMENT ON COLUMN "KFTC_EB21"."BANK_CODE" IS 'KFTC+지점코드';
COMMENT ON COLUMN "KFTC_EB21"."ACCOUNT_NO" IS '수납모계좌번호';
COMMENT ON COLUMN "KFTC_EB21"."TOTAL_RECORD_COUNT" IS '전체 레코드';
COMMENT ON COLUMN "KFTC_EB21"."FULL_COUNT" IS '의뢰 건수';
COMMENT ON COLUMN "KFTC_EB21"."FULL_AMOUNT" IS '의뢰 금액';
COMMENT ON COLUMN "KFTC_EB21"."CREATE_DATE" IS '등록일시';
COMMENT ON COLUMN "KFTC_EB21"."CREATE_USER" IS '등록자';

CREATE SEQUENCE "KFTC_EB21_ID"
  MINVALUE 1000000000
  MAXVALUE 9999999999
  INCREMENT BY 1
  START WITH 1000000000
  CACHE 20
  NOORDER
  NOCYCLE;

-- --------------------------------------------------------------------------------
-- 금결원 고객 등록
-- --------------------------------------------------------------------------------
CREATE TABLE "KFTC_PAYER"
(
  "ID"                CHAR(10 BYTE) NOT NULL ENABLE,
  "APPLY_DATE"        CHAR(8 BYTE),
  "APPLY_TYPE_CD"     CHAR(6 BYTE),
  "PAYER_KFTC_CODE"   CHAR(3 BYTE),
  "PAYER_ACCOUNT_NO"  VARCHAR2(16 BYTE),
  "PAYER_IDENTITY_NO" VARCHAR2(16 BYTE),
  "FUND_TYPE_CD"      CHAR(6 BYTE) DEFAULT 'K20000',
  "SUCCESS_YN"        CHAR(1 BYTE),
  "RESULT_CD"         CHAR(6 BYTE),
  "CONTACT_NO"        VARCHAR2(12 BYTE),
  "CREATE_DATE"       DATE,
  "CREATE_USER"       VARCHAR2(100 BYTE),
  "STATUS_CD"         CHAR(6 BYTE),
  CONSTRAINT "KFTC_PAYER_PK" PRIMARY KEY ("ID")
);

COMMENT ON COLUMN "KFTC_PAYER"."APPLY_DATE" IS '신청일 (납부자의 서비스 신청일자)';
COMMENT ON COLUMN "KFTC_PAYER"."APPLY_TYPE_CD" IS '신청구분코드 (K1)';
COMMENT ON COLUMN "KFTC_PAYER"."PAYER_KFTC_CODE" IS '참가기관(은행)점 코드';
COMMENT ON COLUMN "KFTC_PAYER"."PAYER_ACCOUNT_NO" IS '지정출금계좌번호';
COMMENT ON COLUMN "KFTC_PAYER"."PAYER_IDENTITY_NO" IS '예금주 생년월일 또는 사업자등록번호';
COMMENT ON COLUMN "KFTC_PAYER"."FUND_TYPE_CD" IS '자금 종류 (K2)';
COMMENT ON COLUMN "KFTC_PAYER"."SUCCESS_YN" IS '성공여부';
COMMENT ON COLUMN "KFTC_PAYER"."RESULT_CD" IS '처리결과 (K3)';
COMMENT ON COLUMN "KFTC_PAYER"."CONTACT_NO" IS '전화번호(핸드폰)';
COMMENT ON COLUMN "KFTC_PAYER"."CREATE_DATE" IS '등록일시';
COMMENT ON COLUMN "KFTC_PAYER"."CREATE_USER" IS '등록자';
COMMENT ON COLUMN "KFTC_PAYER"."STATUS_CD" IS '상태코드 (K0)';

CREATE SEQUENCE "KFTC_PAYER_ID"
  MINVALUE 1000000000
  MAXVALUE 9999999999
  INCREMENT BY 1
  START WITH 1000000000
  CACHE 20
  NOORDER
  NOCYCLE;

