ALTER TABLE XCHALIST ADD FINGER_FEE_BANK_CODE CHAR(3) DEFAULT '088' NULL;
COMMENT ON COLUMN XCHALIST.CHARGE_PAYMENT_BANK_CODE IS '관리요금 출금은행';
ALTER TABLE XCHALIST ADD FINGER_FEE_ACCOUNT_NO VARCHAR(16) NULL;
COMMENT ON COLUMN XCHALIST.CHARGE_PAYMENT_ACCOUNT_NO IS '관리요금 출금계좌번호';
UPDATE XCHALIST SET FINGER_FEE_ACCOUNT_NO=FEEACCNO;
