ALTER TABLE XCHALIST 
ADD (FINGER_FEE_OWNER_NO VARCHAR2(10 CHAR) );

ALTER TABLE XCHALIST 
ADD (FINGER_FEE_PAYTY VARCHAR2(3 CHAR) );

COMMENT ON COLUMN XCHALIST.FINGER_FEE_OWNER_NO IS '납부자번호';

COMMENT ON COLUMN XCHALIST.FINGER_FEE_PAYTY IS '납부방법';