CREATE TABLE KFTC_CODE
(
    CODE CHAR(3) PRIMARY KEY,
    VALUE VARCHAR2(20 char) NOT NULL,
    REMARK varchar2(200)
);
COMMENT ON COLUMN KFTC_CODE.CODE IS '금결원 코드';
COMMENT ON COLUMN KFTC_CODE.VALUE IS '기관명';
COMMENT ON COLUMN KFTC_CODE.REMARK IS '비고';
COMMENT ON TABLE KFTC_CODE IS '금융결제원 기관코드';
