CREATE TABLE WITHDRAW_AGREEMENT
(
  ID CHAR(10) PRIMARY KEY,
  TYPE CHAR(6),
  STATUS CHAR(6) DEFAULT 'A00001' NOT NULL,
  FILE_ID CHAR(10),
  CREATE_DATE DATE,
  CREATE_USER VARCHAR2(100)
);
COMMENT ON COLUMN WITHDRAW_AGREEMENT.ID IS '아이디';
COMMENT ON COLUMN WITHDRAW_AGREEMENT.TYPE IS '출금동의 형태 (WAXXXX)';
COMMENT ON COLUMN WITHDRAW_AGREEMENT.STATUS IS '동의서 상태 (A0XXXX)';
COMMENT ON COLUMN WITHDRAW_AGREEMENT.FILE_ID IS '파일 아이디';
COMMENT ON COLUMN WITHDRAW_AGREEMENT.CREATE_DATE IS '등록일시';
COMMENT ON COLUMN WITHDRAW_AGREEMENT.CREATE_USER IS '등록자';
COMMENT ON TABLE WITHDRAW_AGREEMENT IS '출금동의서';

CREATE SEQUENCE  WITHDRAW_AGREEMENT_ID  MINVALUE 1000000001 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1000000001;
CREATE SEQUENCE  COOCON_ARS_ID  MINVALUE 1000000001 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1000000001;

ALTER TABLE XCHALIST ADD WITHDRAW_AGREEMENT_ID CHAR(10) NULL;
COMMENT ON COLUMN XCHALIST.WITHDRAW_AGREEMENT_ID IS '출금동의서 아이디';

create table FW_FILE
(
  ID CHAR(20) not null
    constraint FW_FILE_PK
    primary key,
  BUCKET VARCHAR2(100),
  NAME VARCHAR2(2000 char),
  MIME_TYPE VARCHAR2(2000),
  LENGTH NUMBER(14),
  CREATE_DATE DATE,
  CREATE_USER VARCHAR2(100)
);
comment on column FW_FILE.ID is '아이디';
comment on column FW_FILE.BUCKET is '버킷 이름';
comment on column FW_FILE.NAME is '파일 이름';
comment on column FW_FILE.MIME_TYPE is '파일 형식';
comment on column FW_FILE.LENGTH is '파일 크기';
comment on column FW_FILE.CREATE_DATE is '등록일시';
comment on column FW_FILE.CREATE_USER is '등록자';

CREATE SEQUENCE  FW_FILE_ID  MINVALUE 10000000000000000001 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 10000000000000000001;
