ALTER TABLE XCUSMASFAIL ADD VANO varchar2(20) NULL;
COMMENT ON COLUMN XCUSMASFAIL.VANO IS '계좌번호';
ALTER TABLE XCUSMASFAIL ADD MEMO VARCHAR2(1000) NULL;
COMMENT ON COLUMN XCUSMASFAIL.MEMO IS '메모';
ALTER TABLE XCUSMASFAIL ADD column_23 int NULL;
