CREATE INDEX IDX_XRCPDET_02 ON XRCPDET(NOTIDETCD);
ALTER TABLE XCASHMAS MODIFY RCPAMT NUMBER(14) DEFAULT NULL;
ALTER TABLE XCASHMAS MODIFY TIP NUMBER(14) DEFAULT NULL;
ALTER TABLE XCASHMAS MODIFY TAX NUMBER(14) DEFAULT NULL;
