package kr.co.finger.shinhandamoa.data.domain.mapper;

import kr.co.finger.shinhandamoa.data.table.model.Smsreq;
import kr.co.finger.shinhandamoa.data.table.model.SmsreqExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface ClientStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMSREQ
     *
     * @mbg.generated
     */
    long countByExample(SmsreqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMSREQ
     *
     * @mbg.generated
     */
    int deleteByExample(SmsreqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMSREQ
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String smsreqcd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMSREQ
     *
     * @mbg.generated
     */
    int insert(Smsreq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMSREQ
     *
     * @mbg.generated
     */
    int insertSelective(Smsreq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMSREQ
     *
     * @mbg.generated
     */
    List<Smsreq> selectByExampleWithRowbounds(SmsreqExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMSREQ
     *
     * @mbg.generated
     */
    List<Smsreq> selectByExample(SmsreqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMSREQ
     *
     * @mbg.generated
     */
    Smsreq selectByPrimaryKey(String smsreqcd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMSREQ
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Smsreq record, @Param("example") SmsreqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMSREQ
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Smsreq record, @Param("example") SmsreqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMSREQ
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Smsreq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMSREQ
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Smsreq record);
}
