package com.finger.shinhandamoa.data.table.mapper;

import com.finger.shinhandamoa.data.table.model.CashHst;
import com.finger.shinhandamoa.data.table.model.CashHstExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface CashHstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashhst
     *
     * @mbg.generated
     */
    long countByExample(CashHstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashhst
     *
     * @mbg.generated
     */
    int deleteByExample(CashHstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashhst
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cashhstId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashhst
     *
     * @mbg.generated
     */
    int insert(CashHst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashhst
     *
     * @mbg.generated
     */
    int insertSelective(CashHst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashhst
     *
     * @mbg.generated
     */
    List<CashHst> selectByExampleWithRowbounds(CashHstExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashhst
     *
     * @mbg.generated
     */
    List<CashHst> selectByExample(CashHstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashhst
     *
     * @mbg.generated
     */
    CashHst selectByPrimaryKey(String cashhstId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashhst
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CashHst record, @Param("example") CashHstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashhst
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CashHst record, @Param("example") CashHstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashhst
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CashHst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashhst
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CashHst record);
}