package com.finger.shinhandamoa.data.table.mapper;

import com.finger.shinhandamoa.data.table.model.CashReceiptMaster;
import com.finger.shinhandamoa.data.table.model.CashReceiptMasterExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface CashReceiptMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashmas
     *
     * @mbg.generated
     */
    long countByExample(CashReceiptMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashmas
     *
     * @mbg.generated
     */
    int deleteByExample(CashReceiptMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashmas
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cashmascd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashmas
     *
     * @mbg.generated
     */
    int insert(CashReceiptMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashmas
     *
     * @mbg.generated
     */
    int insertSelective(CashReceiptMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashmas
     *
     * @mbg.generated
     */
    List<CashReceiptMaster> selectByExampleWithRowbounds(CashReceiptMasterExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashmas
     *
     * @mbg.generated
     */
    List<CashReceiptMaster> selectByExample(CashReceiptMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashmas
     *
     * @mbg.generated
     */
    CashReceiptMaster selectByPrimaryKey(String cashmascd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashmas
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CashReceiptMaster record, @Param("example") CashReceiptMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashmas
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CashReceiptMaster record, @Param("example") CashReceiptMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashmas
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CashReceiptMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashmas
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CashReceiptMaster record);
}