package com.finger.shinhandamoa.data.table.mapper;

import com.finger.shinhandamoa.data.table.model.Cha;
import com.finger.shinhandamoa.data.table.model.ChaExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface ChaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xchalist
     *
     * @mbg.generated
     */
    long countByExample(ChaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xchalist
     *
     * @mbg.generated
     */
    int deleteByExample(ChaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xchalist
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String chacd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xchalist
     *
     * @mbg.generated
     */
    int insert(Cha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xchalist
     *
     * @mbg.generated
     */
    int insertSelective(Cha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xchalist
     *
     * @mbg.generated
     */
    List<Cha> selectByExampleWithRowbounds(ChaExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xchalist
     *
     * @mbg.generated
     */
    List<Cha> selectByExample(ChaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xchalist
     *
     * @mbg.generated
     */
    Cha selectByPrimaryKey(String chacd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xchalist
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Cha record, @Param("example") ChaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xchalist
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Cha record, @Param("example") ChaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xchalist
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Cha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xchalist
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cha record);
}