package com.finger.shinhandamoa.data.table.mapper;

import com.finger.shinhandamoa.data.table.model.CustomerMaster;
import com.finger.shinhandamoa.data.table.model.CustomerMasterExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface CustomerMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcusmas
     *
     * @mbg.generated
     */
    long countByExample(CustomerMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcusmas
     *
     * @mbg.generated
     */
    int deleteByExample(CustomerMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcusmas
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String vano);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcusmas
     *
     * @mbg.generated
     */
    int insert(CustomerMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcusmas
     *
     * @mbg.generated
     */
    int insertSelective(CustomerMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcusmas
     *
     * @mbg.generated
     */
    List<CustomerMaster> selectByExampleWithRowbounds(CustomerMasterExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcusmas
     *
     * @mbg.generated
     */
    List<CustomerMaster> selectByExample(CustomerMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcusmas
     *
     * @mbg.generated
     */
    CustomerMaster selectByPrimaryKey(String vano);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcusmas
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CustomerMaster record, @Param("example") CustomerMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcusmas
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CustomerMaster record, @Param("example") CustomerMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcusmas
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CustomerMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcusmas
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CustomerMaster record);
}