package com.finger.shinhandamoa.data.table.mapper;

import com.finger.shinhandamoa.data.table.model.FwFile;
import com.finger.shinhandamoa.data.table.model.FwFileExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface FwFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_file
     *
     * @mbg.generated
     */
    long countByExample(FwFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_file
     *
     * @mbg.generated
     */
    int deleteByExample(FwFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_file
     *
     * @mbg.generated
     */
    int insert(FwFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_file
     *
     * @mbg.generated
     */
    int insertSelective(FwFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_file
     *
     * @mbg.generated
     */
    List<FwFile> selectByExampleWithRowbounds(FwFileExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_file
     *
     * @mbg.generated
     */
    List<FwFile> selectByExample(FwFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_file
     *
     * @mbg.generated
     */
    FwFile selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_file
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FwFile record, @Param("example") FwFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_file
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FwFile record, @Param("example") FwFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FwFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FwFile record);
}