package com.finger.shinhandamoa.data.table.mapper;

import com.finger.shinhandamoa.data.table.model.KftcWithdraw;
import com.finger.shinhandamoa.data.table.model.KftcWithdrawExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface KftcWithdrawMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_withdraw
     *
     * @mbg.generated
     */
    long countByExample(KftcWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_withdraw
     *
     * @mbg.generated
     */
    int deleteByExample(KftcWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_withdraw
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_withdraw
     *
     * @mbg.generated
     */
    int insert(KftcWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_withdraw
     *
     * @mbg.generated
     */
    int insertSelective(KftcWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_withdraw
     *
     * @mbg.generated
     */
    List<KftcWithdraw> selectByExampleWithRowbounds(KftcWithdrawExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_withdraw
     *
     * @mbg.generated
     */
    List<KftcWithdraw> selectByExample(KftcWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_withdraw
     *
     * @mbg.generated
     */
    KftcWithdraw selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_withdraw
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") KftcWithdraw record, @Param("example") KftcWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_withdraw
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") KftcWithdraw record, @Param("example") KftcWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_withdraw
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(KftcWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_withdraw
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KftcWithdraw record);
}