package com.finger.shinhandamoa.data.table.mapper;

import com.finger.shinhandamoa.data.table.model.KftcCode;
import com.finger.shinhandamoa.data.table.model.KftcCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface KftcCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_code
     *
     * @mbg.generated
     */
    long countByExample(KftcCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_code
     *
     * @mbg.generated
     */
    int deleteByExample(KftcCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_code
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_code
     *
     * @mbg.generated
     */
    int insert(KftcCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_code
     *
     * @mbg.generated
     */
    int insertSelective(KftcCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_code
     *
     * @mbg.generated
     */
    List<KftcCode> selectByExampleWithRowbounds(KftcCodeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_code
     *
     * @mbg.generated
     */
    List<KftcCode> selectByExample(KftcCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_code
     *
     * @mbg.generated
     */
    KftcCode selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_code
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") KftcCode record, @Param("example") KftcCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_code
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") KftcCode record, @Param("example") KftcCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(KftcCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KftcCode record);
}