package com.finger.shinhandamoa.data.table.mapper;

import com.finger.shinhandamoa.data.table.model.KftcEb21;
import com.finger.shinhandamoa.data.table.model.KftcEb21Example;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface KftcEb21Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_eb21
     *
     * @mbg.generated
     */
    long countByExample(KftcEb21Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_eb21
     *
     * @mbg.generated
     */
    int deleteByExample(KftcEb21Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_eb21
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_eb21
     *
     * @mbg.generated
     */
    int insert(KftcEb21 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_eb21
     *
     * @mbg.generated
     */
    int insertSelective(KftcEb21 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_eb21
     *
     * @mbg.generated
     */
    List<KftcEb21> selectByExampleWithRowbounds(KftcEb21Example example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_eb21
     *
     * @mbg.generated
     */
    List<KftcEb21> selectByExample(KftcEb21Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_eb21
     *
     * @mbg.generated
     */
    KftcEb21 selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_eb21
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") KftcEb21 record, @Param("example") KftcEb21Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_eb21
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") KftcEb21 record, @Param("example") KftcEb21Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_eb21
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(KftcEb21 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_eb21
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KftcEb21 record);
}