package com.finger.shinhandamoa.data.table.mapper;

import com.finger.shinhandamoa.data.table.model.KftcPayer;
import com.finger.shinhandamoa.data.table.model.KftcPayerExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface KftcPayerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_payer
     *
     * @mbg.generated
     */
    long countByExample(KftcPayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_payer
     *
     * @mbg.generated
     */
    int deleteByExample(KftcPayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_payer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_payer
     *
     * @mbg.generated
     */
    int insert(KftcPayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_payer
     *
     * @mbg.generated
     */
    int insertSelective(KftcPayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_payer
     *
     * @mbg.generated
     */
    List<KftcPayer> selectByExampleWithRowbounds(KftcPayerExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_payer
     *
     * @mbg.generated
     */
    List<KftcPayer> selectByExample(KftcPayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_payer
     *
     * @mbg.generated
     */
    KftcPayer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_payer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") KftcPayer record, @Param("example") KftcPayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_payer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") KftcPayer record, @Param("example") KftcPayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_payer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(KftcPayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kftc_payer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KftcPayer record);
}