package com.finger.shinhandamoa.data.table.mapper;

import com.finger.shinhandamoa.data.table.model.NoticeDetails;
import com.finger.shinhandamoa.data.table.model.NoticeDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface NoticeDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotidet
     *
     * @mbg.generated
     */
    long countByExample(NoticeDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotidet
     *
     * @mbg.generated
     */
    int deleteByExample(NoticeDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotidet
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String notidetcd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotidet
     *
     * @mbg.generated
     */
    int insert(NoticeDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotidet
     *
     * @mbg.generated
     */
    int insertSelective(NoticeDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotidet
     *
     * @mbg.generated
     */
    List<NoticeDetails> selectByExampleWithRowbounds(NoticeDetailsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotidet
     *
     * @mbg.generated
     */
    List<NoticeDetails> selectByExample(NoticeDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotidet
     *
     * @mbg.generated
     */
    NoticeDetails selectByPrimaryKey(String notidetcd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotidet
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") NoticeDetails record, @Param("example") NoticeDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotidet
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") NoticeDetails record, @Param("example") NoticeDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotidet
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NoticeDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotidet
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NoticeDetails record);
}