package com.finger.shinhandamoa.data.table.mapper;

import com.finger.shinhandamoa.data.table.model.NoticeDetailsType;
import com.finger.shinhandamoa.data.table.model.NoticeDetailsTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface NoticeDetailsTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpayitem
     *
     * @mbg.generated
     */
    long countByExample(NoticeDetailsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpayitem
     *
     * @mbg.generated
     */
    int deleteByExample(NoticeDetailsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpayitem
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String payitemcd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpayitem
     *
     * @mbg.generated
     */
    int insert(NoticeDetailsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpayitem
     *
     * @mbg.generated
     */
    int insertSelective(NoticeDetailsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpayitem
     *
     * @mbg.generated
     */
    List<NoticeDetailsType> selectByExampleWithRowbounds(NoticeDetailsTypeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpayitem
     *
     * @mbg.generated
     */
    List<NoticeDetailsType> selectByExample(NoticeDetailsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpayitem
     *
     * @mbg.generated
     */
    NoticeDetailsType selectByPrimaryKey(String payitemcd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpayitem
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") NoticeDetailsType record, @Param("example") NoticeDetailsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpayitem
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") NoticeDetailsType record, @Param("example") NoticeDetailsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpayitem
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NoticeDetailsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpayitem
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NoticeDetailsType record);
}