package com.finger.shinhandamoa.data.table.mapper;

import com.finger.shinhandamoa.data.table.model.NoticeMaster;
import com.finger.shinhandamoa.data.table.model.NoticeMasterExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface NoticeMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimas
     *
     * @mbg.generated
     */
    long countByExample(NoticeMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimas
     *
     * @mbg.generated
     */
    int deleteByExample(NoticeMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimas
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String notimascd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimas
     *
     * @mbg.generated
     */
    int insert(NoticeMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimas
     *
     * @mbg.generated
     */
    int insertSelective(NoticeMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimas
     *
     * @mbg.generated
     */
    List<NoticeMaster> selectByExampleWithRowbounds(NoticeMasterExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimas
     *
     * @mbg.generated
     */
    List<NoticeMaster> selectByExample(NoticeMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimas
     *
     * @mbg.generated
     */
    NoticeMaster selectByPrimaryKey(String notimascd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimas
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") NoticeMaster record, @Param("example") NoticeMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimas
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") NoticeMaster record, @Param("example") NoticeMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimas
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NoticeMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimas
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NoticeMaster record);
}