package com.finger.shinhandamoa.data.table.mapper;

import com.finger.shinhandamoa.data.table.model.ReceiptMaster;
import com.finger.shinhandamoa.data.table.model.ReceiptMasterExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface ReceiptMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    long countByExample(ReceiptMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    int deleteByExample(ReceiptMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String rcpmascd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    int insert(ReceiptMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    int insertSelective(ReceiptMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    List<ReceiptMaster> selectByExampleWithRowbounds(ReceiptMasterExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    List<ReceiptMaster> selectByExample(ReceiptMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    ReceiptMaster selectByPrimaryKey(String rcpmascd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ReceiptMaster record, @Param("example") ReceiptMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ReceiptMaster record, @Param("example") ReceiptMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReceiptMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReceiptMaster record);
}