package com.finger.shinhandamoa.data.table.mapper;

import com.finger.shinhandamoa.data.table.model.ReceiptDetails;
import com.finger.shinhandamoa.data.table.model.ReceiptDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface ReceiptDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpdet
     *
     * @mbg.generated
     */
    long countByExample(ReceiptDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpdet
     *
     * @mbg.generated
     */
    int deleteByExample(ReceiptDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpdet
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String rcpdetcd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpdet
     *
     * @mbg.generated
     */
    int insert(ReceiptDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpdet
     *
     * @mbg.generated
     */
    int insertSelective(ReceiptDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpdet
     *
     * @mbg.generated
     */
    List<ReceiptDetails> selectByExampleWithRowbounds(ReceiptDetailsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpdet
     *
     * @mbg.generated
     */
    List<ReceiptDetails> selectByExample(ReceiptDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpdet
     *
     * @mbg.generated
     */
    ReceiptDetails selectByPrimaryKey(String rcpdetcd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpdet
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ReceiptDetails record, @Param("example") ReceiptDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpdet
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ReceiptDetails record, @Param("example") ReceiptDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpdet
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReceiptDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpdet
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReceiptDetails record);
}