package com.finger.shinhandamoa.data.table.mapper;

import com.finger.shinhandamoa.data.table.model.RePayMaster;
import com.finger.shinhandamoa.data.table.model.RePayMasterExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface RePayMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrepaymas
     *
     * @mbg.generated
     */
    long countByExample(RePayMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrepaymas
     *
     * @mbg.generated
     */
    int deleteByExample(RePayMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrepaymas
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String repaymascd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrepaymas
     *
     * @mbg.generated
     */
    int insert(RePayMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrepaymas
     *
     * @mbg.generated
     */
    int insertSelective(RePayMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrepaymas
     *
     * @mbg.generated
     */
    List<RePayMaster> selectByExampleWithRowbounds(RePayMasterExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrepaymas
     *
     * @mbg.generated
     */
    List<RePayMaster> selectByExample(RePayMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrepaymas
     *
     * @mbg.generated
     */
    RePayMaster selectByPrimaryKey(String repaymascd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrepaymas
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RePayMaster record, @Param("example") RePayMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrepaymas
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RePayMaster record, @Param("example") RePayMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrepaymas
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RePayMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrepaymas
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RePayMaster record);
}