package com.finger.shinhandamoa.data.table.mapper;

import com.finger.shinhandamoa.data.table.model.Xadjgroup;
import com.finger.shinhandamoa.data.table.model.XadjgroupExample;
import com.finger.shinhandamoa.data.table.model.XadjgroupKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface XadjgroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xadjgroup
     *
     * @mbg.generated
     */
    long countByExample(XadjgroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xadjgroup
     *
     * @mbg.generated
     */
    int deleteByExample(XadjgroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xadjgroup
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(XadjgroupKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xadjgroup
     *
     * @mbg.generated
     */
    int insert(Xadjgroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xadjgroup
     *
     * @mbg.generated
     */
    int insertSelective(Xadjgroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xadjgroup
     *
     * @mbg.generated
     */
    List<Xadjgroup> selectByExampleWithRowbounds(XadjgroupExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xadjgroup
     *
     * @mbg.generated
     */
    List<Xadjgroup> selectByExample(XadjgroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xadjgroup
     *
     * @mbg.generated
     */
    Xadjgroup selectByPrimaryKey(XadjgroupKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xadjgroup
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Xadjgroup record, @Param("example") XadjgroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xadjgroup
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Xadjgroup record, @Param("example") XadjgroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xadjgroup
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Xadjgroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xadjgroup
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Xadjgroup record);
}