package com.finger.shinhandamoa.data.table.mapper;

import com.finger.shinhandamoa.data.table.model.Xdaysumrcp;
import com.finger.shinhandamoa.data.table.model.XdaysumrcpExample;
import com.finger.shinhandamoa.data.table.model.XdaysumrcpKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface XdaysumrcpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    long countByExample(XdaysumrcpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    int deleteByExample(XdaysumrcpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(XdaysumrcpKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    int insert(Xdaysumrcp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    int insertSelective(Xdaysumrcp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    List<Xdaysumrcp> selectByExampleWithRowbounds(XdaysumrcpExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    List<Xdaysumrcp> selectByExample(XdaysumrcpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    Xdaysumrcp selectByPrimaryKey(XdaysumrcpKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Xdaysumrcp record, @Param("example") XdaysumrcpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Xdaysumrcp record, @Param("example") XdaysumrcpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Xdaysumrcp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCP
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Xdaysumrcp record);
}