package com.finger.shinhandamoa.data.table.mapper;

import com.finger.shinhandamoa.data.table.model.Xdaysumrcpetc;
import com.finger.shinhandamoa.data.table.model.XdaysumrcpetcExample;
import com.finger.shinhandamoa.data.table.model.XdaysumrcpetcKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface XdaysumrcpetcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCPETC
     *
     * @mbg.generated
     */
    long countByExample(XdaysumrcpetcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCPETC
     *
     * @mbg.generated
     */
    int deleteByExample(XdaysumrcpetcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCPETC
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(XdaysumrcpetcKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCPETC
     *
     * @mbg.generated
     */
    int insert(Xdaysumrcpetc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCPETC
     *
     * @mbg.generated
     */
    int insertSelective(Xdaysumrcpetc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCPETC
     *
     * @mbg.generated
     */
    List<Xdaysumrcpetc> selectByExampleWithRowbounds(XdaysumrcpetcExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCPETC
     *
     * @mbg.generated
     */
    List<Xdaysumrcpetc> selectByExample(XdaysumrcpetcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCPETC
     *
     * @mbg.generated
     */
    Xdaysumrcpetc selectByPrimaryKey(XdaysumrcpetcKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCPETC
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Xdaysumrcpetc record, @Param("example") XdaysumrcpetcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCPETC
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Xdaysumrcpetc record, @Param("example") XdaysumrcpetcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCPETC
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Xdaysumrcpetc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XDAYSUMRCPETC
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Xdaysumrcpetc record);
}