package com.finger.shinhandamoa.data.table.mapper;

import com.finger.shinhandamoa.data.table.model.Xdaysum;
import com.finger.shinhandamoa.data.table.model.XdaysumExample;
import com.finger.shinhandamoa.data.table.model.XdaysumKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface XdaysumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysum
     *
     * @mbg.generated
     */
    long countByExample(XdaysumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysum
     *
     * @mbg.generated
     */
    int deleteByExample(XdaysumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysum
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(XdaysumKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysum
     *
     * @mbg.generated
     */
    int insert(Xdaysum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysum
     *
     * @mbg.generated
     */
    int insertSelective(Xdaysum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysum
     *
     * @mbg.generated
     */
    List<Xdaysum> selectByExampleWithRowbounds(XdaysumExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysum
     *
     * @mbg.generated
     */
    List<Xdaysum> selectByExample(XdaysumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysum
     *
     * @mbg.generated
     */
    Xdaysum selectByPrimaryKey(XdaysumKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysum
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Xdaysum record, @Param("example") XdaysumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysum
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Xdaysum record, @Param("example") XdaysumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysum
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Xdaysum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysum
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Xdaysum record);
}