package kr.co.finger.shinhandamoa.data.table.mapper;

import java.util.List;
import kr.co.finger.shinhandamoa.data.table.model.Smsreq;
import kr.co.finger.shinhandamoa.data.table.model.SmsreqExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface SmsreqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smsreq
     *
     * @mbg.generated
     */
    long countByExample(SmsreqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smsreq
     *
     * @mbg.generated
     */
    int deleteByExample(SmsreqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smsreq
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String smsreqcd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smsreq
     *
     * @mbg.generated
     */
    int insert(Smsreq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smsreq
     *
     * @mbg.generated
     */
    int insertSelective(Smsreq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smsreq
     *
     * @mbg.generated
     */
    List<Smsreq> selectByExampleWithRowbounds(SmsreqExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smsreq
     *
     * @mbg.generated
     */
    List<Smsreq> selectByExample(SmsreqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smsreq
     *
     * @mbg.generated
     */
    Smsreq selectByPrimaryKey(String smsreqcd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smsreq
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Smsreq record, @Param("example") SmsreqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smsreq
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Smsreq record, @Param("example") SmsreqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smsreq
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Smsreq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smsreq
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Smsreq record);
}