package kr.co.finger.shinhandamoa.data.table.mapper;

import java.util.List;
import kr.co.finger.shinhandamoa.data.table.model.Valist;
import kr.co.finger.shinhandamoa.data.table.model.ValistExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface ValistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table valist
     *
     * @mbg.generated
     */
    long countByExample(ValistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table valist
     *
     * @mbg.generated
     */
    int deleteByExample(ValistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table valist
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String vano);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table valist
     *
     * @mbg.generated
     */
    int insert(Valist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table valist
     *
     * @mbg.generated
     */
    int insertSelective(Valist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table valist
     *
     * @mbg.generated
     */
    List<Valist> selectByExampleWithRowbounds(ValistExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table valist
     *
     * @mbg.generated
     */
    List<Valist> selectByExample(ValistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table valist
     *
     * @mbg.generated
     */
    Valist selectByPrimaryKey(String vano);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table valist
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Valist record, @Param("example") ValistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table valist
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Valist record, @Param("example") ValistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table valist
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Valist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table valist
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Valist record);
}