package kr.co.finger.shinhandamoa.data.table.mapper;

import java.util.List;
import kr.co.finger.shinhandamoa.data.table.model.Xcashmas;
import kr.co.finger.shinhandamoa.data.table.model.XcashmasExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface XcashmasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashmas
     *
     * @mbg.generated
     */
    long countByExample(XcashmasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashmas
     *
     * @mbg.generated
     */
    int deleteByExample(XcashmasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashmas
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cashmascd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashmas
     *
     * @mbg.generated
     */
    int insert(Xcashmas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashmas
     *
     * @mbg.generated
     */
    int insertSelective(Xcashmas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashmas
     *
     * @mbg.generated
     */
    List<Xcashmas> selectByExampleWithRowbounds(XcashmasExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashmas
     *
     * @mbg.generated
     */
    List<Xcashmas> selectByExample(XcashmasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashmas
     *
     * @mbg.generated
     */
    Xcashmas selectByPrimaryKey(String cashmascd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashmas
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Xcashmas record, @Param("example") XcashmasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashmas
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Xcashmas record, @Param("example") XcashmasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashmas
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Xcashmas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashmas
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Xcashmas record);
}