package kr.co.finger.shinhandamoa.data.table.mapper;

import java.util.List;
import kr.co.finger.shinhandamoa.data.table.model.Xchalist;
import kr.co.finger.shinhandamoa.data.table.model.XchalistExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface XchalistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xchalist
     *
     * @mbg.generated
     */
    long countByExample(XchalistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xchalist
     *
     * @mbg.generated
     */
    int deleteByExample(XchalistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xchalist
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String chacd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xchalist
     *
     * @mbg.generated
     */
    int insert(Xchalist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xchalist
     *
     * @mbg.generated
     */
    int insertSelective(Xchalist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xchalist
     *
     * @mbg.generated
     */
    List<Xchalist> selectByExampleWithRowbounds(XchalistExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xchalist
     *
     * @mbg.generated
     */
    List<Xchalist> selectByExample(XchalistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xchalist
     *
     * @mbg.generated
     */
    Xchalist selectByPrimaryKey(String chacd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xchalist
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Xchalist record, @Param("example") XchalistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xchalist
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Xchalist record, @Param("example") XchalistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xchalist
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Xchalist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xchalist
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Xchalist record);
}