package kr.co.finger.shinhandamoa.data.table.mapper;

import java.util.List;
import kr.co.finger.shinhandamoa.data.table.model.Xcusmas;
import kr.co.finger.shinhandamoa.data.table.model.XcusmasExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface XcusmasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcusmas
     *
     * @mbg.generated
     */
    long countByExample(XcusmasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcusmas
     *
     * @mbg.generated
     */
    int deleteByExample(XcusmasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcusmas
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String vano);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcusmas
     *
     * @mbg.generated
     */
    int insert(Xcusmas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcusmas
     *
     * @mbg.generated
     */
    int insertSelective(Xcusmas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcusmas
     *
     * @mbg.generated
     */
    List<Xcusmas> selectByExampleWithRowbounds(XcusmasExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcusmas
     *
     * @mbg.generated
     */
    List<Xcusmas> selectByExample(XcusmasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcusmas
     *
     * @mbg.generated
     */
    Xcusmas selectByPrimaryKey(String vano);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcusmas
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Xcusmas record, @Param("example") XcusmasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcusmas
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Xcusmas record, @Param("example") XcusmasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcusmas
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Xcusmas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcusmas
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Xcusmas record);
}