package kr.co.finger.shinhandamoa.data.table.mapper;

import java.util.List;
import kr.co.finger.shinhandamoa.data.table.model.Xpayitem;
import kr.co.finger.shinhandamoa.data.table.model.XpayitemExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface XpayitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpayitem
     *
     * @mbg.generated
     */
    long countByExample(XpayitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpayitem
     *
     * @mbg.generated
     */
    int deleteByExample(XpayitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpayitem
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String payitemcd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpayitem
     *
     * @mbg.generated
     */
    int insert(Xpayitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpayitem
     *
     * @mbg.generated
     */
    int insertSelective(Xpayitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpayitem
     *
     * @mbg.generated
     */
    List<Xpayitem> selectByExampleWithRowbounds(XpayitemExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpayitem
     *
     * @mbg.generated
     */
    List<Xpayitem> selectByExample(XpayitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpayitem
     *
     * @mbg.generated
     */
    Xpayitem selectByPrimaryKey(String payitemcd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpayitem
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Xpayitem record, @Param("example") XpayitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpayitem
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Xpayitem record, @Param("example") XpayitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpayitem
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Xpayitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpayitem
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Xpayitem record);
}