package kr.co.finger.shinhandamoa.data.table.mapper;

import java.util.List;
import kr.co.finger.shinhandamoa.data.table.model.Xrcpmas;
import kr.co.finger.shinhandamoa.data.table.model.XrcpmasExample;
import kr.co.finger.shinhandamoa.data.table.model.xrcpmas.TransNotiHistDTO;
import kr.co.finger.shinhandamoa.data.table.model.xrcpmas.TransNotiMasDTO;
import kr.co.finger.shinhandamoa.data.table.model.xrcpmas.XrcpmasDTO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface XrcpmasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    long countByExample(XrcpmasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    int deleteByExample(XrcpmasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String rcpmascd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    int insert(Xrcpmas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    int insertSelective(Xrcpmas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    List<Xrcpmas> selectByExampleWithRowbounds(XrcpmasExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    List<Xrcpmas> selectByExample(XrcpmasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    Xrcpmas selectByPrimaryKey(String rcpmascd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Xrcpmas record, @Param("example") XrcpmasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Xrcpmas record, @Param("example") XrcpmasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Xrcpmas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpmas
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Xrcpmas record);

    /**
     * 입금 통지할 수납정보 가져오기
     *
     */
//    List<XrcpmasDTO> selectXrcpmasByRcpmascd(String rcpmascd);
    XrcpmasDTO selectXrcpmasByRcpmascd(String rcpmascd);

    /**
     * 입금 통지 발송 결과 내역 적재
     *
     */
    void insertTransNotiMas(TransNotiMasDTO transNotiMas);

    /**
     * 입금 통지 발송 결과 update
     *
     */
    void updateTransNotiMas(TransNotiMasDTO transNotiMas);

    /**
     * 입금 통지 발송 이력 내역 적재
     *
     */
    void insertTransNotiHist(TransNotiHistDTO transNotiHist);
}