--------------------------------------------------------------------------------
-- 기관 연동 전문 수신 이력
--
-- @author wisehouse@finger.co.kr
--------------------------------------------------------------------------------

CREATE TABLE "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"
(	"PULL_DT" CHAR(8 BYTE) NOT NULL ENABLE,
   "CLIENT_ID" CHAR(8 BYTE) NOT NULL ENABLE,
   "CLIENT_NAME" VARCHAR2(30 CHAR),
   "CLIENT_DELETE_YN" CHAR(1 BYTE),
   "RELAY_CLIENT_ID" CHAR(8 BYTE) NOT NULL ENABLE,
   "RGST_DT" CHAR(8 BYTE) NOT NULL ENABLE,
   "CLIENT_ID_NO" VARCHAR2(13 BYTE),
   "CLIENT_STATUS" CHAR(1 BYTE) NOT NULL ENABLE,
   "AGENCY1_CODE" CHAR(5 BYTE),
   "AGENCY1_NAME" VARCHAR2(30 CHAR),
   "AGENCY1_STATUS" CHAR(1 BYTE),
   "AGENCY2_CODE" CHAR(5 BYTE),
   "AGENCY2_NAME" VARCHAR2(30 CHAR),
   "AGENCY2_STATUS" CHAR(1 BYTE),
   "AGENCY3_CODE" CHAR(5 BYTE),
   "AGENCY3_NAME" VARCHAR2(30 CHAR),
   "AGENCY3_STATUS" CHAR(1 BYTE),
   "AGENCY4_CODE" CHAR(5 BYTE),
   "AGENCY4_NAME" VARCHAR2(30 CHAR),
   "AGENCY4_STATUS" CHAR(1 BYTE),
   "AGENCY5_CODE" CHAR(5 BYTE),
   "AGENCY5_NAME" VARCHAR2(30 CHAR),
   "AGENCY5_STATUS" CHAR(1 BYTE),
   "AGENCY6_CODE" CHAR(5 BYTE),
   "AGENCY6_NAME" VARCHAR2(20 BYTE),
   "AGENCY6_STATUS" CHAR(1 BYTE),
   "AGENCY7_CODE" CHAR(5 BYTE),
   "AGENCY7_NAME" VARCHAR2(30 CHAR),
   "AGENCY7_STATUS" CHAR(1 BYTE),
   "AGENCY8_CODE" CHAR(5 BYTE),
   "AGENCY8_NAME" VARCHAR2(30 CHAR),
   "AGENCY8_STATUS" CHAR(1 BYTE),
   "AGENCY9_CODE" CHAR(5 BYTE),
   "AGENCY9_NAME" VARCHAR2(30 CHAR),
   "AGENCY9_STATUS" CHAR(1 BYTE),
   "AGENCY10_CODE" CHAR(5 BYTE),
   "AGENCY10_NAME" VARCHAR2(30 CHAR),
   "AGENCY10_STATUS" CHAR(1 BYTE),
   "PAYMENT_FEE_AMT" NUMBER(5,0) NOT NULL ENABLE,
   "FINGER_FEE_RATE" NUMBER(9,0) NOT NULL ENABLE,
   "BRCH_CODE" CHAR(4 BYTE) NOT NULL ENABLE,
   "STATUS_CD" CHAR(6 BYTE) NOT NULL ENABLE,
   "CREATE_DATE" DATE NOT NULL ENABLE,
   "CREATE_USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
   "MODIFY_DATE" DATE NOT NULL ENABLE,
   "MODIFY_USER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
   "TYPE_CD" CHAR(6 BYTE) DEFAULT NULL NOT NULL ENABLE,
   "ASIS_CLIENT_NAME" VARCHAR2(30 CHAR),
   "ASIS_CLIENT_ID_NO" VARCHAR2(13 BYTE),
   "ASIS_CLIENT_STATUS" CHAR(1 BYTE),
   "ASIS_AGENCY1_CODE" CHAR(5 BYTE),
   "ASIS_AGENCY1_NAME" VARCHAR2(30 CHAR),
   "ASIS_AGENCY2_CODE" CHAR(5 BYTE),
   "ASIS_AGENCY2_NAME" VARCHAR2(30 CHAR),
   "ASIS_AGENCY3_CODE" CHAR(5 BYTE),
   "ASIS_AGENCY3_NAME" VARCHAR2(30 CHAR),
   "ASIS_AGENCY4_CODE" CHAR(5 BYTE),
   "ASIS_AGENCY4_NAME" VARCHAR2(30 CHAR),
   "ASIS_AGENCY5_CODE" CHAR(5 BYTE),
   "ASIS_AGENCY5_NAME" VARCHAR2(30 CHAR),
   "ASIS_AGENCY6_CODE" CHAR(5 BYTE),
   "ASIS_AGENCY6_NAME" VARCHAR2(20 BYTE),
   "ASIS_AGENCY7_CODE" CHAR(5 BYTE),
   "ASIS_AGENCY7_NAME" VARCHAR2(30 CHAR),
   "ASIS_AGENCY8_CODE" CHAR(5 BYTE),
   "ASIS_AGENCY8_NAME" VARCHAR2(30 CHAR),
   "ASIS_AGENCY9_CODE" CHAR(5 BYTE),
   "ASIS_AGENCY9_NAME" VARCHAR2(30 CHAR),
   "ASIS_AGENCY10_CODE" CHAR(5 BYTE),
   "ASIS_AGENCY10_NAME" VARCHAR2(30 CHAR),
   "ASIS_PAYMENT_FEE_AMT" NUMBER(5,0),
   "ASIS_FINGER_FEE_RATE" NUMBER(9,0),
   "ASIS_BRCH_CODE" CHAR(4 BYTE),
  CONSTRAINT "DAMOA_CLIENT_PULL_HIST_PK" PRIMARY KEY ("PULL_DT", "CLIENT_ID")
) ;

COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."PULL_DT" IS '수신일자';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."CLIENT_ID" IS '기관코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."CLIENT_NAME" IS '기관명';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."CLIENT_DELETE_YN" IS '기관삭제여부';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."RELAY_CLIENT_ID" IS '중계기관코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."RGST_DT" IS '신규일자';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."CLIENT_ID_NO" IS '기관식별번호';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."CLIENT_STATUS" IS '기관상태코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY1_CODE" IS '대리점1 코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY1_NAME" IS '대리점1 이름';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY1_STATUS" IS '대리점1 상태코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY2_CODE" IS '대리점2 코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY2_NAME" IS '대리점2 이름';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY2_STATUS" IS '대리점2 상태코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY3_CODE" IS '대리점3 코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY3_NAME" IS '대리점3 이름';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY3_STATUS" IS '대리점3 상태코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY4_CODE" IS '대리점4 코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY4_NAME" IS '대리점4 이름';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY4_STATUS" IS '대리점4 상태코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY5_CODE" IS '대리점5 코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY5_NAME" IS '대리점5 이름';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY5_STATUS" IS '대리점5 상태코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY6_CODE" IS '대리점6 코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY6_NAME" IS '대리점6 이름';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY6_STATUS" IS '대리점6 상태코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY7_CODE" IS '대리점7 코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY7_NAME" IS '대리점7 이름';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY7_STATUS" IS '대리점7 상태코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY8_CODE" IS '대리점8 코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY8_NAME" IS '대리점8 이름';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY8_STATUS" IS '대리점8 상태코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY9_CODE" IS '대리점9 코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY9_NAME" IS '대리점9 이름';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY9_STATUS" IS '대리점9 상태코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY10_CODE" IS '대리점10 코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY10_NAME" IS '대리점10 이름';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."AGENCY10_STATUS" IS '대리점10 상태코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."PAYMENT_FEE_AMT" IS '입금 수수료';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."FINGER_FEE_RATE" IS '핑거 수수료 비율';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."BRCH_CODE" IS '관리점 코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."STATUS_CD" IS '상태코드 (C1)';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."CREATE_DATE" IS '등록일시';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."CREATE_USER" IS '등록자';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."MODIFY_DATE" IS '변경일시';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."MODIFY_USER" IS '변경자';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."TYPE_CD" IS '작업 분류 (C2)';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."ASIS_CLIENT_NAME" IS '기존 기관명';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."ASIS_CLIENT_ID_NO" IS '기존 기관식별번호';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."ASIS_CLIENT_STATUS" IS '기존 기관상태코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."ASIS_AGENCY1_CODE" IS '기존 대리점1 코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."ASIS_AGENCY1_NAME" IS '기존 대리점1 이름';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."ASIS_AGENCY2_CODE" IS '기존 대리점2 코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."ASIS_AGENCY2_NAME" IS '기존 대리점2 이름';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."ASIS_AGENCY3_CODE" IS '기존 대리점3 코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."ASIS_AGENCY3_NAME" IS '기존 대리점3 이름';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."ASIS_AGENCY4_CODE" IS '기존 대리점4 코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."ASIS_AGENCY4_NAME" IS '기존 대리점4 이름';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."ASIS_AGENCY5_CODE" IS '기존 대리점5 코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."ASIS_AGENCY5_NAME" IS '기존 대리점5 이름';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."ASIS_AGENCY6_CODE" IS '기존 대리점6 코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."ASIS_AGENCY6_NAME" IS '기존 대리점6 이름';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."ASIS_AGENCY7_CODE" IS '기존 대리점7 코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."ASIS_AGENCY7_NAME" IS '기존 대리점7 이름';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."ASIS_AGENCY8_CODE" IS '기존 대리점8 코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."ASIS_AGENCY8_NAME" IS '기존 대리점8 이름';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."ASIS_AGENCY9_CODE" IS '기존 대리점9 코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."ASIS_AGENCY9_NAME" IS '기존 대리점9 이름';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."ASIS_AGENCY10_CODE" IS '기존 대리점10 코드';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."ASIS_AGENCY10_NAME" IS '기존 대리점10 이름';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."ASIS_PAYMENT_FEE_AMT" IS '기존 입금 수수료';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."ASIS_FINGER_FEE_RATE" IS '기존 핑거 수수료 비율';
COMMENT ON COLUMN "DAMOA_S2"."DAMOA_CLIENT_INFO_PULL_HIST"."ASIS_BRCH_CODE" IS '기존 관리점 코드';

--------------------------------------------------------------------------------
-- 기관 원장
-- 
-- 은행 등록일자와 은행 승인일자 추가
--
-- @author wisehouse@finger.co.kr
--------------------------------------------------------------------------------
ALTER TABLE XCHALIST ADD (
  BANK_REGI_DT CHAR(8) NULL,
  BANK_ACPT_DT CHAR(8) NULL  
);


--------------------------------------------------------------------------------
-- 공통 코드
--
-- 기관 정보 연동 테이블의 코드 추가

-- @author wisehouse@finger.co.kr
--------------------------------------------------------------------------------
Insert into FW_CODE (CODE,CODE_GROUP,NAME,DESCRIPTION,MODIFY_USER,MODIFY_DATE) values ('C20001','C2','신규',null,'wisehouse',to_date('18/12/12','RR/MM/DD'));
Insert into FW_CODE (CODE,CODE_GROUP,NAME,DESCRIPTION,MODIFY_USER,MODIFY_DATE) values ('C20002','C2','변경',null,'wisehouse',to_date('18/12/12','RR/MM/DD'));
Insert into FW_CODE (CODE,CODE_GROUP,NAME,DESCRIPTION,MODIFY_USER,MODIFY_DATE) values ('C20003','C2','해지',null,'wisehouse',to_date('18/12/12','RR/MM/DD'));
Insert into FW_CODE (CODE,CODE_GROUP,NAME,DESCRIPTION,MODIFY_USER,MODIFY_DATE) values ('C10001','C1','대기',null,'wisehouse',to_date('18/12/04','RR/MM/DD'));
Insert into FW_CODE (CODE,CODE_GROUP,NAME,DESCRIPTION,MODIFY_USER,MODIFY_DATE) values ('C10002','C1','준비',null,'wisehouse',to_date('18/12/04','RR/MM/DD'));
Insert into FW_CODE (CODE,CODE_GROUP,NAME,DESCRIPTION,MODIFY_USER,MODIFY_DATE) values ('C10003','C1','실행 중',null,'wisehouse',to_date('18/12/04','RR/MM/DD'));
Insert into FW_CODE (CODE,CODE_GROUP,NAME,DESCRIPTION,MODIFY_USER,MODIFY_DATE) values ('C10004','C1','성공',null,'wisehouse',to_date('18/12/04','RR/MM/DD'));
Insert into FW_CODE (CODE,CODE_GROUP,NAME,DESCRIPTION,MODIFY_USER,MODIFY_DATE) values ('C10005','C1','실패',null,'wisehouse',to_date('18/12/04','RR/MM/DD'));
