package kr.co.finger.shinhandamoa.data.table.mapper;

import java.util.List;
import kr.co.finger.shinhandamoa.data.table.model.CashFileTranHist;
import kr.co.finger.shinhandamoa.data.table.model.CashFileTranHistExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface CashFileTranHistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_file_tran_hist
     *
     * @mbg.generated
     */
    long countByExample(CashFileTranHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_file_tran_hist
     *
     * @mbg.generated
     */
    int deleteByExample(CashFileTranHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_file_tran_hist
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String transDt);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_file_tran_hist
     *
     * @mbg.generated
     */
    int insert(CashFileTranHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_file_tran_hist
     *
     * @mbg.generated
     */
    int insertSelective(CashFileTranHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_file_tran_hist
     *
     * @mbg.generated
     */
    List<CashFileTranHist> selectByExampleWithRowbounds(CashFileTranHistExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_file_tran_hist
     *
     * @mbg.generated
     */
    List<CashFileTranHist> selectByExample(CashFileTranHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_file_tran_hist
     *
     * @mbg.generated
     */
    CashFileTranHist selectByPrimaryKey(String transDt);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_file_tran_hist
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CashFileTranHist record, @Param("example") CashFileTranHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_file_tran_hist
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CashFileTranHist record, @Param("example") CashFileTranHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_file_tran_hist
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CashFileTranHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cash_file_tran_hist
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CashFileTranHist record);
}