package kr.co.finger.shinhandamoa.data.table.mapper;

import java.util.List;
import kr.co.finger.shinhandamoa.data.table.model.Cashreq;
import kr.co.finger.shinhandamoa.data.table.model.CashreqExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface CashreqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cashreq
     *
     * @mbg.generated
     */
    long countByExample(CashreqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cashreq
     *
     * @mbg.generated
     */
    int deleteByExample(CashreqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cashreq
     *
     * @mbg.generated
     */
    int insert(Cashreq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cashreq
     *
     * @mbg.generated
     */
    int insertSelective(Cashreq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cashreq
     *
     * @mbg.generated
     */
    List<Cashreq> selectByExampleWithRowbounds(CashreqExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cashreq
     *
     * @mbg.generated
     */
    List<Cashreq> selectByExample(CashreqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cashreq
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Cashreq record, @Param("example") CashreqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cashreq
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Cashreq record, @Param("example") CashreqExample example);
}