package kr.co.finger.shinhandamoa.data.table.mapper;

import java.util.List;
import kr.co.finger.shinhandamoa.data.table.model.DamoaClientInfoPullHist;
import kr.co.finger.shinhandamoa.data.table.model.DamoaClientInfoPullHistExample;
import kr.co.finger.shinhandamoa.data.table.model.DamoaClientInfoPullHistKey;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface DamoaClientInfoPullHistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damoa_client_info_pull_hist
     *
     * @mbg.generated
     */
    long countByExample(DamoaClientInfoPullHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damoa_client_info_pull_hist
     *
     * @mbg.generated
     */
    int deleteByExample(DamoaClientInfoPullHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damoa_client_info_pull_hist
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(DamoaClientInfoPullHistKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damoa_client_info_pull_hist
     *
     * @mbg.generated
     */
    int insert(DamoaClientInfoPullHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damoa_client_info_pull_hist
     *
     * @mbg.generated
     */
    int insertSelective(DamoaClientInfoPullHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damoa_client_info_pull_hist
     *
     * @mbg.generated
     */
    List<DamoaClientInfoPullHist> selectByExampleWithRowbounds(DamoaClientInfoPullHistExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damoa_client_info_pull_hist
     *
     * @mbg.generated
     */
    List<DamoaClientInfoPullHist> selectByExample(DamoaClientInfoPullHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damoa_client_info_pull_hist
     *
     * @mbg.generated
     */
    DamoaClientInfoPullHist selectByPrimaryKey(DamoaClientInfoPullHistKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damoa_client_info_pull_hist
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DamoaClientInfoPullHist record, @Param("example") DamoaClientInfoPullHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damoa_client_info_pull_hist
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DamoaClientInfoPullHist record, @Param("example") DamoaClientInfoPullHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damoa_client_info_pull_hist
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DamoaClientInfoPullHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table damoa_client_info_pull_hist
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DamoaClientInfoPullHist record);
}