package kr.co.finger.shinhandamoa.data.table.mapper;

import java.util.List;
import kr.co.finger.shinhandamoa.data.table.model.FwCashReceiptMaster;
import kr.co.finger.shinhandamoa.data.table.model.FwCashReceiptMasterExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface FwCashReceiptMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_cash_receipt_master
     *
     * @mbg.generated
     */
    long countByExample(FwCashReceiptMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_cash_receipt_master
     *
     * @mbg.generated
     */
    int deleteByExample(FwCashReceiptMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_cash_receipt_master
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_cash_receipt_master
     *
     * @mbg.generated
     */
    int insert(FwCashReceiptMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_cash_receipt_master
     *
     * @mbg.generated
     */
    int insertSelective(FwCashReceiptMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_cash_receipt_master
     *
     * @mbg.generated
     */
    List<FwCashReceiptMaster> selectByExampleWithRowbounds(FwCashReceiptMasterExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_cash_receipt_master
     *
     * @mbg.generated
     */
    List<FwCashReceiptMaster> selectByExample(FwCashReceiptMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_cash_receipt_master
     *
     * @mbg.generated
     */
    FwCashReceiptMaster selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_cash_receipt_master
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FwCashReceiptMaster record, @Param("example") FwCashReceiptMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_cash_receipt_master
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FwCashReceiptMaster record, @Param("example") FwCashReceiptMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_cash_receipt_master
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FwCashReceiptMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_cash_receipt_master
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FwCashReceiptMaster record);
}