package kr.co.finger.shinhandamoa.data.table.mapper;

import java.util.List;
import kr.co.finger.shinhandamoa.data.table.model.VaSettleDet;
import kr.co.finger.shinhandamoa.data.table.model.VaSettleDetExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface VaSettleDetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_settle_det
     *
     * @mbg.generated
     */
    long countByExample(VaSettleDetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_settle_det
     *
     * @mbg.generated
     */
    int deleteByExample(VaSettleDetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_settle_det
     *
     * @mbg.generated
     */
    int insert(VaSettleDet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_settle_det
     *
     * @mbg.generated
     */
    int insertSelective(VaSettleDet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_settle_det
     *
     * @mbg.generated
     */
    List<VaSettleDet> selectByExampleWithRowbounds(VaSettleDetExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_settle_det
     *
     * @mbg.generated
     */
    List<VaSettleDet> selectByExample(VaSettleDetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_settle_det
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VaSettleDet record, @Param("example") VaSettleDetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table va_settle_det
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VaSettleDet record, @Param("example") VaSettleDetExample example);
}