package kr.co.finger.shinhandamoa.data.table.mapper;

import java.util.List;
import kr.co.finger.shinhandamoa.data.table.model.Webuser;
import kr.co.finger.shinhandamoa.data.table.model.WebuserExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface WebuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webuser
     *
     * @mbg.generated
     */
    long countByExample(WebuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webuser
     *
     * @mbg.generated
     */
    int deleteByExample(WebuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webuser
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String loginid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webuser
     *
     * @mbg.generated
     */
    int insert(Webuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webuser
     *
     * @mbg.generated
     */
    int insertSelective(Webuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webuser
     *
     * @mbg.generated
     */
    List<Webuser> selectByExampleWithRowbounds(WebuserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webuser
     *
     * @mbg.generated
     */
    List<Webuser> selectByExample(WebuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webuser
     *
     * @mbg.generated
     */
    Webuser selectByPrimaryKey(String loginid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webuser
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Webuser record, @Param("example") WebuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webuser
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Webuser record, @Param("example") WebuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Webuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Webuser record);
}