package kr.co.finger.shinhandamoa.data.table.mapper;

import java.util.List;
import kr.co.finger.shinhandamoa.data.table.model.Xcashhst;
import kr.co.finger.shinhandamoa.data.table.model.XcashhstExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface XcashhstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashhst
     *
     * @mbg.generated
     */
    long countByExample(XcashhstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashhst
     *
     * @mbg.generated
     */
    int deleteByExample(XcashhstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashhst
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cashhstId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashhst
     *
     * @mbg.generated
     */
    int insert(Xcashhst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashhst
     *
     * @mbg.generated
     */
    int insertSelective(Xcashhst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashhst
     *
     * @mbg.generated
     */
    List<Xcashhst> selectByExampleWithRowbounds(XcashhstExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashhst
     *
     * @mbg.generated
     */
    List<Xcashhst> selectByExample(XcashhstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashhst
     *
     * @mbg.generated
     */
    Xcashhst selectByPrimaryKey(String cashhstId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashhst
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Xcashhst record, @Param("example") XcashhstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashhst
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Xcashhst record, @Param("example") XcashhstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashhst
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Xcashhst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xcashhst
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Xcashhst record);
}