package kr.co.finger.shinhandamoa.data.table.mapper;

import java.util.List;
import kr.co.finger.shinhandamoa.data.table.model.Xdaysumsms;
import kr.co.finger.shinhandamoa.data.table.model.XdaysumsmsExample;
import kr.co.finger.shinhandamoa.data.table.model.XdaysumsmsKey;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface XdaysumsmsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumsms
     *
     * @mbg.generated
     */
    long countByExample(XdaysumsmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumsms
     *
     * @mbg.generated
     */
    int deleteByExample(XdaysumsmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumsms
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(XdaysumsmsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumsms
     *
     * @mbg.generated
     */
    int insert(Xdaysumsms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumsms
     *
     * @mbg.generated
     */
    int insertSelective(Xdaysumsms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumsms
     *
     * @mbg.generated
     */
    List<Xdaysumsms> selectByExampleWithRowbounds(XdaysumsmsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumsms
     *
     * @mbg.generated
     */
    List<Xdaysumsms> selectByExample(XdaysumsmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumsms
     *
     * @mbg.generated
     */
    Xdaysumsms selectByPrimaryKey(XdaysumsmsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumsms
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Xdaysumsms record, @Param("example") XdaysumsmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumsms
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Xdaysumsms record, @Param("example") XdaysumsmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumsms
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Xdaysumsms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumsms
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Xdaysumsms record);
}