package kr.co.finger.shinhandamoa.data.table.mapper;

import java.util.List;
import kr.co.finger.shinhandamoa.data.table.model.Xdaysumrcpetc;
import kr.co.finger.shinhandamoa.data.table.model.XdaysumrcpetcExample;
import kr.co.finger.shinhandamoa.data.table.model.XdaysumrcpetcKey;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface XdaysumrcpetcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumrcpetc
     *
     * @mbg.generated
     */
    long countByExample(XdaysumrcpetcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumrcpetc
     *
     * @mbg.generated
     */
    int deleteByExample(XdaysumrcpetcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumrcpetc
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(XdaysumrcpetcKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumrcpetc
     *
     * @mbg.generated
     */
    int insert(Xdaysumrcpetc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumrcpetc
     *
     * @mbg.generated
     */
    int insertSelective(Xdaysumrcpetc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumrcpetc
     *
     * @mbg.generated
     */
    List<Xdaysumrcpetc> selectByExampleWithRowbounds(XdaysumrcpetcExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumrcpetc
     *
     * @mbg.generated
     */
    List<Xdaysumrcpetc> selectByExample(XdaysumrcpetcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumrcpetc
     *
     * @mbg.generated
     */
    Xdaysumrcpetc selectByPrimaryKey(XdaysumrcpetcKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumrcpetc
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Xdaysumrcpetc record, @Param("example") XdaysumrcpetcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumrcpetc
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Xdaysumrcpetc record, @Param("example") XdaysumrcpetcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumrcpetc
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Xdaysumrcpetc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumrcpetc
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Xdaysumrcpetc record);
}