package kr.co.finger.shinhandamoa.data.table.mapper;

import java.util.List;
import kr.co.finger.shinhandamoa.data.table.model.Xdaysumnoti;
import kr.co.finger.shinhandamoa.data.table.model.XdaysumnotiExample;
import kr.co.finger.shinhandamoa.data.table.model.XdaysumnotiKey;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface XdaysumnotiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    long countByExample(XdaysumnotiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    int deleteByExample(XdaysumnotiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(XdaysumnotiKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    int insert(Xdaysumnoti record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    int insertSelective(Xdaysumnoti record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    List<Xdaysumnoti> selectByExampleWithRowbounds(XdaysumnotiExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    List<Xdaysumnoti> selectByExample(XdaysumnotiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    Xdaysumnoti selectByPrimaryKey(XdaysumnotiKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Xdaysumnoti record, @Param("example") XdaysumnotiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Xdaysumnoti record, @Param("example") XdaysumnotiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Xdaysumnoti record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xdaysumnoti
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Xdaysumnoti record);
}