package kr.co.finger.shinhandamoa.data.table.mapper;

import java.util.List;
import kr.co.finger.shinhandamoa.data.table.model.Xmonthsum;
import kr.co.finger.shinhandamoa.data.table.model.XmonthsumExample;
import kr.co.finger.shinhandamoa.data.table.model.XmonthsumKey;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface XmonthsumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmonthsum
     *
     * @mbg.generated
     */
    long countByExample(XmonthsumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmonthsum
     *
     * @mbg.generated
     */
    int deleteByExample(XmonthsumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmonthsum
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(XmonthsumKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmonthsum
     *
     * @mbg.generated
     */
    int insert(Xmonthsum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmonthsum
     *
     * @mbg.generated
     */
    int insertSelective(Xmonthsum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmonthsum
     *
     * @mbg.generated
     */
    List<Xmonthsum> selectByExampleWithRowbounds(XmonthsumExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmonthsum
     *
     * @mbg.generated
     */
    List<Xmonthsum> selectByExample(XmonthsumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmonthsum
     *
     * @mbg.generated
     */
    Xmonthsum selectByPrimaryKey(XmonthsumKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmonthsum
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Xmonthsum record, @Param("example") XmonthsumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmonthsum
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Xmonthsum record, @Param("example") XmonthsumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmonthsum
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Xmonthsum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmonthsum
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Xmonthsum record);
}