package kr.co.finger.shinhandamoa.data.table.mapper;

import java.util.List;
import kr.co.finger.shinhandamoa.data.table.model.Xnotimasreq;
import kr.co.finger.shinhandamoa.data.table.model.XnotimasreqExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface XnotimasreqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimasreq
     *
     * @mbg.generated
     */
    long countByExample(XnotimasreqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimasreq
     *
     * @mbg.generated
     */
    int deleteByExample(XnotimasreqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimasreq
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String notimasreqcd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimasreq
     *
     * @mbg.generated
     */
    int insert(Xnotimasreq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimasreq
     *
     * @mbg.generated
     */
    int insertSelective(Xnotimasreq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimasreq
     *
     * @mbg.generated
     */
    List<Xnotimasreq> selectByExampleWithRowbounds(XnotimasreqExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimasreq
     *
     * @mbg.generated
     */
    List<Xnotimasreq> selectByExample(XnotimasreqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimasreq
     *
     * @mbg.generated
     */
    Xnotimasreq selectByPrimaryKey(String notimasreqcd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimasreq
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Xnotimasreq record, @Param("example") XnotimasreqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimasreq
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Xnotimasreq record, @Param("example") XnotimasreqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimasreq
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Xnotimasreq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimasreq
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Xnotimasreq record);
}