package kr.co.finger.shinhandamoa.data.table.mapper;

import java.util.List;
import kr.co.finger.shinhandamoa.data.table.model.Xnotimas;
import kr.co.finger.shinhandamoa.data.table.model.XnotimasExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface XnotimasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimas
     *
     * @mbg.generated
     */
    long countByExample(XnotimasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimas
     *
     * @mbg.generated
     */
    int deleteByExample(XnotimasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimas
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String notimascd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimas
     *
     * @mbg.generated
     */
    int insert(Xnotimas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimas
     *
     * @mbg.generated
     */
    int insertSelective(Xnotimas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimas
     *
     * @mbg.generated
     */
    List<Xnotimas> selectByExampleWithRowbounds(XnotimasExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimas
     *
     * @mbg.generated
     */
    List<Xnotimas> selectByExample(XnotimasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimas
     *
     * @mbg.generated
     */
    Xnotimas selectByPrimaryKey(String notimascd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimas
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Xnotimas record, @Param("example") XnotimasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimas
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Xnotimas record, @Param("example") XnotimasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimas
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Xnotimas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xnotimas
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Xnotimas record);
}