package kr.co.finger.shinhandamoa.data.table.mapper;

import java.util.List;
import kr.co.finger.shinhandamoa.data.table.model.Xrcpdet;
import kr.co.finger.shinhandamoa.data.table.model.XrcpdetExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface XrcpdetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpdet
     *
     * @mbg.generated
     */
    long countByExample(XrcpdetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpdet
     *
     * @mbg.generated
     */
    int deleteByExample(XrcpdetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpdet
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String rcpdetcd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpdet
     *
     * @mbg.generated
     */
    int insert(Xrcpdet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpdet
     *
     * @mbg.generated
     */
    int insertSelective(Xrcpdet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpdet
     *
     * @mbg.generated
     */
    List<Xrcpdet> selectByExampleWithRowbounds(XrcpdetExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpdet
     *
     * @mbg.generated
     */
    List<Xrcpdet> selectByExample(XrcpdetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpdet
     *
     * @mbg.generated
     */
    Xrcpdet selectByPrimaryKey(String rcpdetcd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpdet
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Xrcpdet record, @Param("example") XrcpdetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpdet
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Xrcpdet record, @Param("example") XrcpdetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpdet
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Xrcpdet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xrcpdet
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Xrcpdet record);
}